// Generated by ts-to-zod
import { z } from 'zod';

export const folderContentInputSchema = z.object({
    id: z.string().optional(),
    pageToken: z.string().optional()
});

export const documentMetadataSchema = z.object({
    files: z.union([z.array(z.string()), z.undefined()]),
    folders: z.union([z.array(z.string()), z.undefined()])
});

export const documentSchema = z.object({
    id: z.string(),
    url: z.string(),
    title: z.string()
});

export const anonymousGoogledriveActionFetchdocumentOutputSchema = z.string();

export const anonymousGoogledriveActionFetchdocumentInputSchema = z.string();
