interface Metadata {
    uri: string;
    type: string;
}
interface DeferredNav {
    __deferred: {
        uri: string;
    };
}
export interface SapSuccessFactorsPerPerson {
    __metadata: Metadata;
    personIdExternal: string;
    lastModifiedDateTime: string;
    lastModifiedBy: string;
    createdDateTime: string;
    dateOfBirth: string | null;
    perPersonUuid: string;
    createdOn: string;
    lastModifiedOn: string;
    countryOfBirth: string | null;
    createdBy: string;
    regionOfBirth: string | null;
    personId: string;
    personalInfoNav: { results: PersonalInfoNav[] };
    emergencyContactNav: DeferredNav;
    secondaryAssignmentsNav: DeferredNav;
    personEmpTerminationInfoNav: DeferredNav;
    phoneNav: DeferredNav;
    employmentNav: DeferredNav;
    countryOfBirthNav: DeferredNav;
    personRerlationshipNav: DeferredNav;
    nationalIdNav: DeferredNav;
    userAccountNav: DeferredNav;
    personTypeUsageNav: DeferredNav;
    emailNav: DeferredNav;
    homeAddressNavDEFLT: DeferredNav;
}

export interface PersonalInfoNav {
    __metadata: Metadata;
    personIdExternal: string;
    startDate: string;
    lastModifiedDateTime: string;
    endDate: string;
    createdDateTime: string;
    suffix: string | null;
    attachmentId: string | null;
    preferredName: string | null;
    lastNameAlt1: string | null;
    firstName: string;
    nationality: string | null;
    salutation: string | null;
    maritalStatus: string | null;
    lastName: string;
    gender: string | null;
    firstNameAlt1: string | null;
    createdOn: string;
    middleNameAlt1: string | null;
    lastModifiedBy: string;
    lastModifiedOn: string;
    createdBy: string;
    middleName: string | null;
    nativePreferredLang: string | null;
    localNavAUS: DeferredNav;
    localNavBGD: DeferredNav;
    localNavHKG: DeferredNav;
    localNavMYS: DeferredNav;
    localNavAUT: DeferredNav;
    localNavLKA: DeferredNav;
    localNavPOL: DeferredNav;
    localNavCZE: DeferredNav;
    localNavTWN: DeferredNav;
    localNavARE: DeferredNav;
    localNavARG: DeferredNav;
    localNavCAN: DeferredNav;
    localNavNOR: DeferredNav;
    localNavOMN: DeferredNav;
    localNavPER: DeferredNav;
    localNavSGP: DeferredNav;
    localNavVEN: DeferredNav;
    localNavZAF: DeferredNav;
    localNavCHL: DeferredNav;
    localNavCHE: DeferredNav;
    localNavDNK: DeferredNav;
    localNavGTM: DeferredNav;
    localNavNZL: DeferredNav;
    salutationNav: DeferredNav;
    localNavCHN: DeferredNav;
    localNavVNM: DeferredNav;
    localNavIDN: DeferredNav;
    localNavPRT: DeferredNav;
    localNavCOL: DeferredNav;
    localNavHUN: DeferredNav;
    localNavSWE: DeferredNav;
    localNavESP: DeferredNav;
    localNavUSA: DeferredNav;
    nativePreferredLangNav: DeferredNav;
    maritalStatusNav: DeferredNav;
    localNavKOR: DeferredNav;
    personNav: SapSuccessFactorsComprehensiveEmployee;
    localNavBEL: DeferredNav;
    localNavFIN: DeferredNav;
    localNavDEU: DeferredNav;
    localNavFRA: DeferredNav;
    localNavEGY: DeferredNav;
    localNavITA: DeferredNav;
    localNavTUR: DeferredNav;
    localNavBRA: DeferredNav;
    localNavRUS: DeferredNav;
    localNavIND: DeferredNav;
    suffixNav: DeferredNav;
    localNavROU: DeferredNav;
    localNavQAT: DeferredNav;
    localNavSAU: DeferredNav;
    localNavNLD: DeferredNav;
    localNavMEX: DeferredNav;
    localNavIRL: DeferredNav;
    localNavTHA: DeferredNav;
    localNavJPN: DeferredNav;
    localNavPHL: DeferredNav;
    wfRequestNav: DeferredNav;
    localNavGBR: DeferredNav;
}

export interface SapSuccessFactorsLocation {
    __metadata: Metadata;
    externalCode: string;
    startDate: string;
    lastModifiedDateTime: string;
    endDate: string;
    standardHours: string | null;
    timezone: string;
    lastModifiedBy: string;
    createdDateTime: string;
    description: string | null;
    createdOn: string;
    lastModifiedOn: string;
    createdBy: string;
    name: string;
    geozoneFlx: string | null;
    entityOID: string;
    locationGroup: string | null;
    internalCode: string;
    objectId: string;
    status: string;
    addressNavDEFLT: AddressNavDeflt;
    descriptionTranslationNav: DeferredNav;
    locationGroupNav: DeferredNav;
    nameTranslationNav: DeferredNav;
    geozoneFlxNav: DeferredNav;
    companyFlxNav: DeferredNav;
}

interface AddressNavDeflt {
    __metadata: Metadata;
    addressId: string;
    country: string;
    zipCode: string | null;
    lastModifiedDateTime: string;
    city: string | null;
    endDate: string;
    county: string | null;
    createdDateTime: string;
    createdOn: string;
    province: string | null;
    address7: string | null;
    address6: string | null;
    address5: string | null;
    address4: string | null;
    state: string | null;
    address9: string | null;
    address8: string | null;
    address3: string | null;
    address2: string | null;
    address1: string | null;
    lastModifiedBy: string;
    lastModifiedOn: string;
    address10: string | null;
    address11: string | null;
    createdBy: string;
    startDate: string;
    stateNav: DeferredNav;
    address4Nav: DeferredNav;
    address6Nav: DeferredNav;
    countyNav: DeferredNav;
    cityNav: DeferredNav;
    provinceNav: DeferredNav;
    countryNav: DeferredNav;
}

export interface SapSuccessDepartment {
    __metadata: Metadata;
    externalCode: string;
    startDate: string;
    parent: string | null;
    description_ko_KR: string | null;
    lastModifiedDateTime: string;
    name_localized: string;
    endDate: string;
    entityUUID: string;
    name_ko_KR?: string;
    createdDateTime: string;
    description_ar_SA: string | null;
    description_pt_BR: string | null;
    description_es_ES: string | null;
    name_fi_FI: string | null;
    name_pt_BR: string | null;
    description_nl_NL: string | null;
    name_sv_SE: string | null;
    name_nl_NL: string | null;
    costCenter: string | null;
    name_da_DK: string | null;
    description_defaultValue: string | null;
    description_da_DK: string | null;
    name_ar_SA: string | null;
    name_de_DE: string | null;
    name_zh_TW: string | null;
    name: string;
    name_es_ES: string | null;
    description_en_US: string | null;
    description_sv_SE: string | null;
    entityOID: string | null;
    description_en_DEBUG: string | null;
    description_it_IT: string | null;
    description_ru_RU: string | null;
    status: string;
    name_ru_RU: string | null;
    description_ja_JP: string | null;
    description_fr_FR: string | null;
    name_pt_PT: string | null;
    name_it_IT: string | null;
    description: string | null;
    description_de_DE: string | null;
    name_fr_FR: string | null;
    name_en_DEBUG: string | null;
    name_ja_JP: string | null;
    createdOn: string;
    headOfUnit: string | null;
    name_en_US: string;
    description_zh_TW: string | null;
    name_zh_CN: string | null;
    name_defaultValue: string;
    description_en_GB: string | null;
    lastModifiedBy: string;
    description_fi_FI: string | null;
    description_nb_NO: string | null;
    name_en_GB: string | null;
    lastModifiedOn: string;
    name_nb_NO: string | null;
    description_zh_CN: string | null;
    createdBy: string;
    mdfSystemRecordId: string;
    description_localized: string | null;
    description_pt_PT: string | null;
    cust_toLegalEntity: DeferredNav;
    nameTranslationTextNav: DeferredNav;
    createdByNav: DeferredNav;
    headOfUnitNav: DeferredNav;
    divisionFlxNav: DeferredNav;
    descriptionTranslationTextNav: DeferredNav;
    statusNav: DeferredNav;
    descriptionTranslationNav: DeferredNav;
    cust_toDivision: DeferredNav;
    costCenterNav: DeferredNav;
    lastModifiedByNav: DeferredNav;
    nameTranslationNav: DeferredNav;
    toDepartmentApprenticeDetail: DeferredNav;
    parentNav: DeferredNav;
}

export interface SapSuccessFactorsComprehensiveEmployee {
    __metadata: Metadata;
    personIdExternal: string;
    lastModifiedDateTime: string;
    lastModifiedBy: string;
    createdDateTime: string;
    dateOfBirth: string;
    perPersonUuid: string;
    createdOn: string;
    lastModifiedOn: string;
    countryOfBirth: string;
    createdBy: string;
    regionOfBirth: string | null;
    personId: string;
    personalInfoNav: { results: PersonalInfoNav[] };
    emergencyContactNav: DeferredNav;
    secondaryAssignmentsNav: DeferredNav;
    personEmpTerminationInfoNav: PersonEmpTerminationInfoNav;
    phoneNav: { results: PhoneNav[] };
    employmentNav: { results: EmploymentNav[] };
    countryOfBirthNav: DeferredNav;
    personRerlationshipNav: DeferredNav;
    nationalIdNav: DeferredNav;
    userAccountNav: DeferredNav;
    personTypeUsageNav: DeferredNav;
    emailNav: { results: EmailNav[] };
    homeAddressNavDEFLT: { results: HomeAddressNavDeflt[] };
}

interface PersonEmpTerminationInfoNav {
    __metadata: Metadata;
    personIdExternal: string;
    latestTerminationDate: string | null;
    activeEmploymentsCount: number;
}

interface PhoneNav {
    __metadata: Metadata;
    phoneType: string;
    personIdExternal: string;
    extension: string | null;
    lastModifiedDateTime: string;
    lastModifiedBy: string;
    createdDateTime: string;
    createdOn: string;
    lastModifiedOn: string;
    areaCode: string;
    phoneNumber: string;
    createdBy: string;
    countryCode: string;
    isPrimary: boolean;
    phoneTypeNav: DeferredNav;
    personNav: DeferredNav;
}

export interface EmailNav {
    __metadata: Metadata;
    emailType: string;
    personIdExternal: string;
    emailAddress: string;
    lastModifiedDateTime: string;
    createdBy: string;
    isPrimary: boolean;
    lastModifiedBy: string;
    createdDateTime: string;
    createdOn: string;
    lastModifiedOn: string;
    emailTypeNav: DeferredNav;
    personNav: DeferredNav;
}

interface HomeAddressNavDeflt {
    __metadata: Metadata;
    addressType: string;
    personIdExternal: string;
    startDate: string;
    country: string;
    zipCode: string;
    lastModifiedDateTime: string;
    notes: string | null;
    city: string;
    endDate: string;
    county: string | null;
    createdDateTime: string;
    createdOn: string;
    address20: string | null;
    province: string | null;
    address7: string | null;
    address6: string | null;
    address5: string | null;
    address4: string | null;
    state: string;
    address9: string | null;
    address8: string | null;
    empUsersSysId: string | null;
    address3: string | null;
    address2: string | null;
    address1: string;
    lastModifiedBy: string;
    lastModifiedOn: string;
    address10: string | null;
    address11: string | null;
    address12: string | null;
    createdBy: string;
    address13: string | null;
    stateNav: DeferredNav;
    address12Nav: DeferredNav;
    personNav: DeferredNav;
    address4Nav: DeferredNav;
    address6Nav: DeferredNav;
    countyNav: DeferredNav;
    address8Nav: DeferredNav;
    cityNav: DeferredNav;
    provinceNav: DeferredNav;
    countryNav: DeferredNav;
    wfRequestNav: DeferredNav;
    address7Nav: DeferredNav;
    address3Nav: DeferredNav;
}

export interface EmploymentNav {
    __metadata: Metadata;
    personIdExternal: string;
    userId: string;
    lastModifiedDateTime: string;
    serviceDate: string;
    endDate: string | null;
    bonusPayExpirationDate: string | null;
    createdDateTime: string;
    employmentId: string;
    isContingentWorker: boolean;
    initialOptionGrant: string | null;
    initialStockGrant: string;
    employeeFirstEmployment: string | null;
    eligibleForStock: boolean;
    eligibleForSalContinuation: string | null;
    okToRehire: string | null;
    assignmentIdExternal: string;
    professionalServiceDate: string;
    salaryEndDate: string | null;
    seniorityDate: string;
    startDate: string;
    hiringNotCompleted: boolean;
    isECRecord: boolean;
    prevEmployeeId: string | null;
    regretTermination: string | null;
    createdOn: string;
    lastDateWorked: string | null;
    firstDateWorked: string;
    originalStartDate: string;
    payrollEndDate: string | null;
    benefitsEligibilityStartDate: string;
    StockEndDate: string | null;
    benefitsEndDate: string | null;
    assignmentClass: string;
    lastModifiedBy: string;
    lastModifiedOn: string;
    createdBy: string;
    paymentInformationNav: DeferredNav;
    photoNav: DeferredNav;
    compInfoNav: { results: CompanyNav[] };
    onboardingInfoNav: DeferredNav;
    empGlobalAssignmentNav: DeferredNav;
    empJobRelationshipNav: DeferredNav;
    personNav: DeferredNav;
    empWorkPermitNav: DeferredNav;
    workOrderNav: DeferredNav;
    userNav: DeferredNav;
    jobInfoNav: { results: JobInfoNav[] };
    wfRequestNav: DeferredNav;
    costDistributionNav: DeferredNav;
    empPayCompNonRecurringNav: DeferredNav;
}

export interface CompanyNav {
    __metadata: Metadata;
    userId: string;
    startDate: string;
    lastModifiedDateTime: string;
    effectiveLatestChange: boolean;
    endDate: string;
    customDouble6: string | null;
    createdDateTime: string;
    customDouble7: string | null;
    createdOn: string;
    customDouble5: string | null;
    bonusTarget: string | null;
    payrollSystemId: string | null;
    event: string;
    benefitsRate: string;
    isHighlyCompensatedEmployee: boolean;
    lastModifiedBy: string;
    eventReason: string;
    lastModifiedOn: string;
    payGroup: string;
    isEligibleForCar: boolean;
    createdBy: string;
    isInsider: boolean;
    isEligibleForBenefits: boolean;
    employmentNav: EmploymentNav;
    empPayCompRecurringNav: DeferredNav;
    eventReasonNav: DeferredNav;
    userNav: DeferredNav;
    payGroupNav: DeferredNav;
    wfRequestNav: DeferredNav;
    empCompensationGroupSumCalculatedNav: DeferredNav;
    eventNav: DeferredNav;
    empCompensationCalculatedNav: DeferredNav;
}

export interface JobInfoNav {
    __metadata: Metadata;
    seqNumber: string;
    userId: string;
    startDate: string;
    occupationalLevels: string | null;
    workscheduleCode: string;
    timeEventTypeGroupId: string | null;
    effectiveLatestChange: boolean;
    endDate: string;
    contractType: string | null;
    createdDateTime: string;
    jobCode: string;
    validFrom: string | null;
    fgtsDate: string | null;
    payScaleLevel: string | null;
    division: string;
    timeTypeProfileCode: string;
    eeoClass: string;
    probationaryPeriodMeasure: string | null;
    fromCurrency: string | null;
    eeo5JobCategory: string;
    flsaStatus: string;
    costCenter: string;
    residentVote: boolean;
    timeRecordingProfileCode: string;
    laborProtection: boolean;
    sickPaySupplementMeasure: string | null;
    exclExecutiveSector: boolean;
    isFulltimeEmployee: boolean;
    emplStatus: string;
    ineligibleStatutoryMinWage: boolean;
    guaranteedPayment: string | null;
    occupationGtm: string | null;
    occupationPer: string | null;
    payScaleType: string;
    countryOfCompany: string;
    eeo6JobCategory: string;
    createdOn: string;
    municipalInseeCode: string | null;
    creditForPreviousService: string | null;
    localJobTitle: string | null;
    healthRisk: boolean;
    serviceCostLevel: string | null;
    dismissalsNoticePeriodForEmployer: string | null;
    timeRecordingAdmissibilityCode: string;
    fte: string;
    payGrade: string;
    travelDistance: string | null;
    event: string;
    timeRecordingVariant: string;
    calculationBase: string | null;
    assedicCertObjectNum: string | null;
    degreeOfProductivity: string | null;
    assessmentStatus: string | null;
    managerId: string;
    spclRuleNonManualWorker: boolean;
    customString13: string | null;
    lastModifiedOn: string;
    dynamicBreakConfigCode: string | null;
    workerCategory: string | null;
    defaultOvertimeCompensationVariant: string;
    contractDate: string | null;
    businessUnit: string;
    lastModifiedDateTime: string;
    notes: string | null;
    harmfulAgentExposure: string | null;
    jobTitle: string;
    probationaryPeriod: string | null;
    sickPaySupplement: string | null;
    electoralCollegeForWorksCouncil: string | null;
    codeOfJobForEldp: string | null;
    familyRelationshipWithEmployer: string | null;
    exchangeRate: string | null;
    workPermitExpiry: string | null;
    currentWageLevel: string | null;
    holidayCalendarCode: string;
    empRelationship: string | null;
    standardHours: string;
    contractNumber: string | null;
    electoralCollegeForWorkersRepresentatives: string | null;
    jobGroup: string | null;
    eeo4JobCategory: string;
    eventReason: string;
    isCompetitionClauseActive: boolean;
    assedicCertInitialStateNum: string | null;
    fgtsPercent: string | null;
    toCurrency: string | null;
    position: string;
    payScaleArea: string;
    probationPeriodEndDate: string | null;
    timezone: string;
    workingDaysPerWeek: string;
    regularTemp: string;
    workLocation: string | null;
    contractReferenceForAed: string | null;
    isSideLineJobAllowed: boolean;
    company: string;
    department: string;
    eeo1JobCategory: string;
    periodIndicator: string | null;
    employeeClass: string;
    employmentType: string;
    lastModifiedBy: string;
    customString3: string | null;
    customString2: string | null;
    customString8: string | null;
    customString7: string | null;
    payScaleGroup: string | null;
    employeeWorkgroupMembership: string | null;
    positionEntryDate: string;
    sickPaySupplementPeriod: string | null;
    createdBy: string;
    contractId: string | null;
    location: string;
    paymentInLieuOfNotice: boolean;
    eeo5JobCategoryNav: DeferredNav;
    toCurrencyNav: DeferredNav;
    holidayCalendarCodeNav: DeferredNav;
    occupationalLevelsNav: DeferredNav;
    companyNav: CompanyNav;
    payScaleAreaNav: DeferredNav;
    departmentNav: DeferredNav;
    businessUnitNav: DeferredNav;
    fromCurrencyNav: DeferredNav;
    contractTypeNav: DeferredNav;
    payScaleTypeNav: DeferredNav;
    electoralCollegeForWorkersRepresentativesNav: DeferredNav;
    employeeWorkgroupMembershipNav: DeferredNav;
    customString7Nav: DeferredNav;
    costCenterNav: DeferredNav;
    harmfulAgentExposureNav: DeferredNav;
    flsaStatusNav: DeferredNav;
    employmentTypeNav: EmploymentTypeNav | null;
    userNav: DeferredNav;
    customString13Nav: DeferredNav;
    payScaleGroupNav: DeferredNav;
    timeTypeProfileCodeNav: DeferredNav;
    electoralCollegeForWorksCouncilNav: DeferredNav;
    divisionNav: DeferredNav;
    eeo6JobCategoryNav: DeferredNav;
    eeoClassNav: DeferredNav;
    workscheduleCodeNav: DeferredNav;
    sickPaySupplementNav: DeferredNav;
    employmentNav: DeferredNav;
    eeo4JobCategoryNav: DeferredNav;
    periodIndicatorNav: DeferredNav;
    workerCategoryNav: DeferredNav;
    countryOfCompanyNav: DeferredNav;
    probationaryPeriodMeasureNav: DeferredNav;
    occupationPerNav: DeferredNav;
    codeOfJobForEldpNav: DeferredNav;
    managerEmploymentNav: ManagerEmploymentNav;
    assessmentStatusNav: DeferredNav;
    customString8Nav: DeferredNav;
    familyRelationshipWithEmployerNav: DeferredNav;
    eventNav: DeferredNav;
    managerUserNav: DeferredNav;
    jobGroupNav: DeferredNav;
    locationNav: LocalNav;
    payScaleLevelNav: DeferredNav;
    occupationGtmNav: DeferredNav;
    regularTempNav: regularTempNav;
    eventReasonNav: DeferredNav;
    employeeClassNav: DeferredNav;
    jobCodeNav: DeferredNav;
    dismissalsNoticePeriodForEmployerNav: DeferredNav;
    sickPaySupplementMeasureNav: DeferredNav;
    emplStatusNav: DeferredNav;
    positionNav: DeferredNav;
    wfRequestNav: DeferredNav;
    eeo1JobCategoryNav: DeferredNav;
    empRelationshipNav: DeferredNav;
    payGradeNav: DeferredNav;
}

interface EmploymentTypeNav {
    __metadata: Metadata;
    id: string;
    minValue: string;
    externalCode: string;
    maxValue: string;
    optionValue: string;
    sortOrder: number;
    mdfExternalCode: string;
    status: string;
    parentPicklistOption: DeferredNav;
    picklistLabels: DeferredNav;
    picklist: DeferredNav;
    childPicklistOptions: DeferredNav;
}

interface ManagerEmploymentNav {
    __metadata: Metadata;
    personIdExternal: string;
    userId: string;
    lastModifiedDateTime: string;
    serviceDate: string;
    endDate: string | null;
    bonusPayExpirationDate: string | null;
    createdDateTime: string;
    employmentId: string;
    isContingentWorker: boolean;
    initialOptionGrant: string | null;
    initialStockGrant: string | null;
    employeeFirstEmployment: string | null;
    eligibleForStock: string | null;
    eligibleForSalContinuation: string | null;
    okToRehire: string | null;
    assignmentIdExternal: string;
    professionalServiceDate: string;
    salaryEndDate: string | null;
    seniorityDate: string;
    startDate: string;
    hiringNotCompleted: boolean;
    isECRecord: boolean;
    prevEmployeeId: string | null;
    regretTermination: string | null;
    createdOn: string;
    lastDateWorked: string | null;
    firstDateWorked: string;
    originalStartDate: string;
    payrollEndDate: string | null;
    benefitsEligibilityStartDate: string;
    StockEndDate: string | null;
    benefitsEndDate: string | null;
    assignmentClass: string;
    lastModifiedBy: string;
    lastModifiedOn: string;
    createdBy: string;
    paymentInformationNav: DeferredNav;
    photoNav: DeferredNav;
    compInfoNav: DeferredNav;
    onboardingInfoNav: DeferredNav;
    empGlobalAssignmentNav: DeferredNav;
    empJobRelationshipNav: DeferredNav;
    personNav: SapSuccessFactorsComprehensiveEmployee | null;
    empWorkPermitNav: DeferredNav;
    workOrderNav: DeferredNav;
    userNav: DeferredNav;
    jobInfoNav: DeferredNav;
    wfRequestNav: DeferredNav;
    costDistributionNav: DeferredNav;
    empPayCompNonRecurringNav: DeferredNav;
}

export interface LocalNav {
    __metadata: Metadata;
    externalCode: string;
    startDate: string;
    lastModifiedDateTime: string;
    endDate: string;
    standardHours: string;
    timezone: string;
    lastModifiedBy: string;
    createdDateTime: string;
    description: any;
    createdOn: string;
    lastModifiedOn: string;
    createdBy: string;
    name: string;
    geozoneFlx: string;
    entityOID: string;
    locationGroup: string;
    internalCode: string;
    objectId: string;
    status: string;
    addressNavDEFLT: AddressNavDeflt;
    descriptionTranslationNav: DeferredNav;
    locationGroupNav: DeferredNav;
    nameTranslationNav: DeferredNav;
    geozoneFlxNav: DeferredNav;
    companyFlxNav: DeferredNav;
}

interface regularTempNav {
    __metadata: Metadata;
    id: string;
    minValue: string;
    externalCode: string;
    maxValue: string;
    optionValue: string;
    sortOrder: number;
    mdfExternalCode: string;
    status: string;
    parentPicklistOption: DeferredNav;
    picklistLabels: DeferredNav;
    picklist: DeferredNav;
    childPicklistOptions: DeferredNav;
}
