import { z } from 'zod';
import { createAction } from 'nango';

const InputSchema = z.object({
    id: z.string().describe('To-Do ID. Example: "6a6174ad545a6c26e85e387e"'),
    title: z.string().optional().describe('Title of the to-do'),
    description: z.string().nullable().optional().describe('Description or notes'),
    dueDate: z.string().nullable().optional().describe('Due date in ISO 8601 or YYYY-MM-DD'),
    completed: z.boolean().optional().describe('Whether the to-do is completed'),
    archived: z.boolean().optional().describe('Whether the to-do is archived'),
    teamId: z.string().optional().describe('Team ID. Omit or empty for personal to-do'),
    userId: z.string().optional().describe('User ID'),
    repeat: z.string().nullable().optional().describe('Recurrence pattern, e.g. weekly, monthly')
});

const UserSchema = z
    .object({
        active: z.boolean().optional(),
        metadata: z.object({}).passthrough().optional(),
        roleCode: z.string().optional(),
        primaryEmail: z.string().nullable().optional(),
        emailAddresses: z.array(z.object({}).passthrough()).optional()
    })
    .passthrough();

const ProviderTodoSchema = z
    .object({
        _id: z.string(),
        userId: z.string().optional(),
        teamId: z.string().nullable().optional(),
        title: z.string().optional(),
        description: z.string().nullable().optional(),
        dueDate: z.string().nullable().optional(),
        originalDueDate: z.string().nullable().optional(),
        isPersonal: z.boolean().optional(),
        createdBy: z.unknown().nullable().optional(),
        repeat: z.string().nullable().optional(),
        seriesId: z.string().nullable().optional(),
        companyId: z.string().optional(),
        ordinal: z.number().optional(),
        userOrdinal: z.number().optional(),
        milestoneId: z.string().nullable().optional(),
        autoGenerated: z.boolean().optional(),
        dueDateChanged: z.boolean().optional(),
        comments: z.array(z.unknown()).optional(),
        archived: z.boolean().optional(),
        archivedDate: z.string().nullable().optional(),
        archivedByUserId: z.string().nullable().optional(),
        completed: z.boolean().optional(),
        completedDate: z.string().nullable().optional(),
        completedByUserId: z.string().nullable().optional(),
        deleted: z.boolean().optional(),
        deletedDate: z.string().nullable().optional(),
        deletedByUserId: z.string().nullable().optional(),
        imported: z.boolean().optional(),
        createdByUserId: z.string().optional(),
        createdDate: z.string().optional(),
        followers: z.array(z.string()).optional(),
        _version: z.number().optional(),
        user: UserSchema.optional(),
        createdByUser: UserSchema.optional()
    })
    .passthrough();

const OutputSchema = z.object({
    id: z.string(),
    userId: z.string().optional(),
    teamId: z.string().nullable().optional(),
    title: z.string().optional(),
    description: z.string().nullable().optional(),
    dueDate: z.string().nullable().optional(),
    originalDueDate: z.string().nullable().optional(),
    isPersonal: z.boolean().optional(),
    createdBy: z.unknown().nullable().optional(),
    repeat: z.string().nullable().optional(),
    seriesId: z.string().nullable().optional(),
    companyId: z.string().optional(),
    ordinal: z.number().optional(),
    userOrdinal: z.number().optional(),
    milestoneId: z.string().nullable().optional(),
    autoGenerated: z.boolean().optional(),
    dueDateChanged: z.boolean().optional(),
    comments: z.array(z.unknown()).optional(),
    archived: z.boolean().optional(),
    archivedDate: z.string().nullable().optional(),
    archivedByUserId: z.string().nullable().optional(),
    completed: z.boolean().optional(),
    completedDate: z.string().nullable().optional(),
    completedByUserId: z.string().nullable().optional(),
    deleted: z.boolean().optional(),
    deletedDate: z.string().nullable().optional(),
    deletedByUserId: z.string().nullable().optional(),
    imported: z.boolean().optional(),
    createdByUserId: z.string().optional(),
    createdDate: z.string().optional(),
    followers: z.array(z.string()).optional(),
    version: z.number().optional(),
    user: UserSchema.optional(),
    createdByUser: UserSchema.optional()
});

const action = createAction({
    description: 'Partially update a to-do.',
    version: '1.0.0',
    input: InputSchema,
    output: OutputSchema,
    scopes: [],

    exec: async (nango, input): Promise<z.infer<typeof OutputSchema>> => {
        const data: Record<string, unknown> = {};
        if (input.title !== undefined) {
            data['title'] = input.title;
        }
        if (input.description !== undefined) {
            data['description'] = input.description;
        }
        if (input.dueDate !== undefined) {
            data['dueDate'] = input.dueDate;
        }
        if (input.completed !== undefined) {
            data['completed'] = input.completed;
        }
        if (input.archived !== undefined) {
            data['archived'] = input.archived;
        }
        if (input.teamId !== undefined) {
            data['teamId'] = input.teamId;
        }
        if (input.userId !== undefined) {
            data['userId'] = input.userId;
        }
        if (input.repeat !== undefined) {
            data['repeat'] = input.repeat;
        }

        const response = await nango.patch({
            // https://api.public.ninety.io/v1/swagger
            endpoint: `/v1/todos/${encodeURIComponent(input.id)}`,
            data,
            retries: 10
        });

        if (response.status === 404) {
            throw new nango.ActionError({
                type: 'not_found',
                message: `To-Do with id ${input.id} not found`
            });
        }

        const providerTodo = ProviderTodoSchema.parse(response.data);

        return {
            id: providerTodo._id,
            userId: providerTodo.userId,
            teamId: providerTodo.teamId,
            title: providerTodo.title,
            description: providerTodo.description,
            dueDate: providerTodo.dueDate,
            originalDueDate: providerTodo.originalDueDate,
            isPersonal: providerTodo.isPersonal,
            createdBy: providerTodo.createdBy,
            repeat: providerTodo.repeat,
            seriesId: providerTodo.seriesId,
            companyId: providerTodo.companyId,
            ordinal: providerTodo.ordinal,
            userOrdinal: providerTodo.userOrdinal,
            milestoneId: providerTodo.milestoneId,
            autoGenerated: providerTodo.autoGenerated,
            dueDateChanged: providerTodo.dueDateChanged,
            comments: providerTodo.comments,
            archived: providerTodo.archived,
            archivedDate: providerTodo.archivedDate,
            archivedByUserId: providerTodo.archivedByUserId,
            completed: providerTodo.completed,
            completedDate: providerTodo.completedDate,
            completedByUserId: providerTodo.completedByUserId,
            deleted: providerTodo.deleted,
            deletedDate: providerTodo.deletedDate,
            deletedByUserId: providerTodo.deletedByUserId,
            imported: providerTodo.imported,
            createdByUserId: providerTodo.createdByUserId,
            createdDate: providerTodo.createdDate,
            followers: providerTodo.followers,
            version: providerTodo._version,
            user: providerTodo.user,
            createdByUser: providerTodo.createdByUser
        };
    }
});

export type NangoActionLocal = Parameters<(typeof action)['exec']>[0];
export default action;
