// Generated by ts-to-zod
import { z } from 'zod';

export const userSchema = z.object({
    id: z.string(),
    email: z.string(),
    firstName: z.string(),
    lastName: z.string()
});

export const createUserSchema = z.object({
    email: z.string()
});

export const miroCreateUserSchema = z.object({
    email: z.string(),
    org_id: z.string(),
    team_id: z.string(),
    role: z.union([z.literal('member'), z.literal('admin'), z.literal('team_guest')]).optional()
});
