// ---------------------------
// This file was generated by Nango (v0.62.0)
// You can version this file
// ---------------------------

export interface Employee {
    id: string;
    personIdExternal: string;
    firstName: string;
    lastName: string;
    preferredName: string;
    gender: string;
    nationality: string;
    maritalStatus: string | null;
    dateOfBirth: string | null;
    countryOfBirth: string | null;
    createdDateTime: string;
    lastModifiedDateTime: string;
}

export interface Location {
    id: string;
    externalCode: string;
    name: string;
    description: string | null;
    status: string;
    startDate: string;
    endDate: string;
    timezone: string;
    createdDateTime: string;
    lastModifiedDateTime: string;
    country: string;
    state: string | null;
    city: string | null;
    zipCode: string | null;
    addressLine1: string | null;
    addressLine2: string | null;
}

export interface Group {
    id: string;
    name: string;
    name_localized: string;
    name_en_US: string;
    name_defaultValue: string;
    description: string | null;
    startDate: string;
    endDate: string;
    parent: string | null;
    costCenter: string | null;
    headOfUnit: string | null;
    status: string;
    createdDateTime: string;
    lastModifiedDateTime: string;
    entityUUID: string;
}

export interface Person {
    id: string;
    firstName: string;
    lastName: string;
    email: string;
}

export interface Address {
    street: string;
    city: string;
    state: string;
    country: string;
    postalCode: string;
    type: 'HOME' | 'WORK';
}

export interface Phone {
    type: 'WORK' | 'HOME' | 'MOBILE';
    number: string;
}

export interface Email {
    type: 'WORK' | 'PERSONAL';
    address: string;
}

export interface StandardEmployee {
    id: string;
    firstName: string;
    lastName: string;
    email: string;
    displayName: string;
    employeeNumber: string;
    title: string;
    department: { id: string; name: string };
    employmentType: 'FULL_TIME' | 'PART_TIME' | 'CONTRACTOR' | 'INTERN' | 'TEMPORARY' | 'OTHER';
    employmentStatus: 'ACTIVE' | 'TERMINATED' | 'ON_LEAVE' | 'SUSPENDED' | 'PENDING';
    startDate: string;
    terminationDate?: string;
    terminationType?: string;
    manager: Person;
    workLocation: { name: string; type: 'OFFICE' | 'REMOTE' | 'HYBRID'; primaryAddress?: Address };
    addresses: Address[];
    phones: Phone[];
    emails: Email[];
    providerSpecific: { [key: string]: any };
    createdAt: string;
    updatedAt: string;
}
