// ---------------------------
// This file was generated by Nango (v0.56.1)
// You can version this file
// ---------------------------

export interface IdEntity {
    id: string;
}

export interface SuccessResponse {
    success: boolean;
}

export interface CreateUser {
    first_name: string;
    last_name: string;
    email: string;
}

export interface HarvestCreateUser {
    first_name: string;
    last_name: string;
    email: string;
    timezone?: string;
    has_access_to_all_future_projects?: boolean;
    is_contractor?: boolean;
    is_active?: boolean;
    weekly_capacity?: number;
    default_hourly_rate?: 'decimal';
    cost_rate?: 'decimal';
    roles?: string[];
    access_roles?:
        | 'administrator'
        | 'manager'
        | 'member'
        | 'project_creator'
        | 'billable_rates_manager'
        | 'managed_projects_invoice_drafter'
        | 'managed_projects_invoice_manager'
        | 'client_and_task_manager'
        | 'time_and_expenses_manager'
        | 'estimates_manager';
}

export interface User {
    id: string;
    email: string;
    firstName: string;
    lastName: string;
}
