// ---------------------------
// This file was generated by Nango (v0.68.1)
// You can version this file
// ---------------------------

export interface SyncMetadata_ring_central_users {
};

export interface User {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
};

export interface SyncMetadata_ring_central_contacts {
};

export interface Contact {
  id: string;
  firstName?: string | undefined;
  lastName?: string | undefined;
  email?: string | undefined;
  phoneNumbers?: ({  type: 'work' | 'mobile' | 'other';
  value: string;})[] | undefined;
  company?: string | undefined;
  jobTitle?: string | undefined;
  notes?: string | undefined;
};

export interface ActionInput_ring_central_createuser {
  firstName: string;
  lastName: string;
  email: string;
  active?: boolean | undefined;
  externalId?: string | undefined;
  phoneNumbers: ({  type: 'work' | 'mobile' | 'other';
  value: string;})[];
  photos: ({  type: 'photo';
  value: string;})[];
  addresses: ({  type: 'work';
  streetAddress?: string | undefined;
  locality?: string | undefined;
  region?: string | undefined;
  postalCode?: string | undefined;
  country?: string | undefined;})[];
  title?: string | undefined;
  "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"?: {  department: string;} | undefined;
};

export interface ActionOutput_ring_central_createuser {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
};

export interface ActionInput_ring_central_deleteuser {
  id: string;
};

export interface ActionOutput_ring_central_deleteuser {
  success: boolean;
};

export type ActionInput_ring_central_getcompanyinfo = void

export interface ActionOutput_ring_central_getcompanyinfo {
  id: string;
  name: string;
  status: string;
  serviceInfo: {  brand: {  id: string;
  name: string;};
  servicePlan: {  id: string;
  name: string;};};
  mainNumber?: string | undefined;
  operator: {  id?: string | undefined;
  extensionNumber?: string | undefined;};
};

export interface ActionInput_ring_central_createcontact {
  firstName?: string | undefined;
  lastName?: string | undefined;
  email?: string | undefined;
  phoneNumbers: ({  type: 'work' | 'mobile' | 'other';
  value: string;})[];
  company?: string | undefined;
  jobTitle?: string | undefined;
  notes?: string | undefined;
};

export interface ActionOutput_ring_central_createcontact {
  id: string;
  firstName?: string | undefined;
  lastName?: string | undefined;
  email?: string | undefined;
  phoneNumbers?: ({  type: 'work' | 'mobile' | 'other';
  value: string;})[] | undefined;
  company?: string | undefined;
  jobTitle?: string | undefined;
  notes?: string | undefined;
};
