// ---------------------------
// This file was generated by Nango (v0.53.0)
// You can version this file
// ---------------------------

export interface Employee {
    id: string;
    user_name: string | null;
    first_name?: string;
    last_name?: string;
    email: string;
    role: string;
    department: string;
    site: string;
    country?: string | null;
    external_id?: string;
    employment_relationship?: string;
    phone_number: string | null;
}

export interface Group {
    id: string;
    active: boolean;
    created_at: string | null;
    name: string;
}

export interface CompanyLocationState {
    name: string;
    abbrev: string;
    iso_code: string;
}

export interface Location {
    id: string;
    name: string;
    description: string | null;
    city: string | null;
    state: CompanyLocationState | null;
    country: { name: string; iso_code: string };
    zip_code: string;
    address: string;
    phone_number: string | null;
}
