// ---------------------------
// This file was generated by Nango (v0.62.0)
// You can version this file
// ---------------------------

export interface LinearIssue {
    id: string;
    assigneeId: string | null;
    creatorId: string | null;
    createdAt: string;
    updatedAt: string;
    description: string | null;
    dueDate: string | null;
    projectId: string | null;
    teamId: string;
    title: string;
    status: string;
    estimate: string | null;
}

export interface CreateIssue {
    teamId: string;
    title: string;
    description?: string;
    projectId?: string;
    milestoneId?: string;
    assigneeId?: string;
    priority?: number;
    parentId?: string;
    estimate?: number;
    dueDate?: string;
}

export interface LinearTeamBase {
    id: string;
    name: string;
}

export interface LinearTeam {
    id: string;
    name: string;
    description: string | null;
    createdAt: string;
    updatedAt: string;
}

export interface LinearUser {
    id: string;
    admin: boolean;
    email: string;
    firstName: string;
    lastName?: string;
    avatarUrl: string | null;
}

export interface LinearProject {
    id: string;
    url: string;
    name: string;
    description: string | null;
    createdAt: string;
    updatedAt: string;
    teamId: string;
}

export interface LinearRoadmap {
    id: string;
    name: string;
    description: string | null;
    createdAt: string;
    updatedAt: string;
    teamId: string;
    projectIds: string;
}

export interface LinearMilestone {
    id: string;
    name: string;
    progress: number;
    description: string | null;
    createdAt: string;
    updatedAt: string;
    status: string;
    project: { id: string; name: string };
}

export interface TeamsPaginatedResponse {
    teams: LinearTeamBase[];
    pageInfo: { hasNextPage: boolean; endCursor: string | null };
}

export interface FetchTeamsInput {
    after?: string;
    pageSize?: number;
}

export interface Entity {
    name: string;
}

export interface Field {
    [key: string]: Field | string;
}

export interface FieldResponse {
    fields: Field[];
}

export interface Model {
    name: string;
}

export interface ModelResponse {
    models: Model[];
}
