// ---------------------------
// This file was generated by Nango (v0.64.1)
// You can version this file
// ---------------------------

export interface SyncMetadata_oracle_hcm_unifiedemployees {
};

export interface StandardEmployee {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  displayName: string;
  employeeNumber: string;
  title: string;
  department: {  id: string;
  name: string;};
  employmentType: 'FULL_TIME' | 'PART_TIME' | 'CONTRACTOR' | 'INTERN' | 'TEMPORARY' | 'OTHER';
  employmentStatus: 'ACTIVE' | 'TERMINATED' | 'ON_LEAVE' | 'SUSPENDED' | 'PENDING';
  startDate: string;
  terminationDate: string;
  manager: {  id: string;
  firstName: string;
  lastName: string;
  email: string;};
  workLocation: {  name: string;
  type: 'OFFICE' | 'REMOTE' | 'HYBRID';
  primaryAddress: {  street: string;
  city: string;
  state: string;
  country: string;
  postalCode: string;
  type: 'WORK' | 'HOME';};};
  addresses: (string | string | string | string | string | 'WORK' | 'HOME')[];
  phones: ('WORK' | 'HOME' | 'MOBILE' | string)[];
  emails: ('WORK' | 'PERSONAL' | string)[];
  providerSpecific: {};
  createdAt: string;
  updatedAt: string;
};

export interface SyncMetadata_oracle_hcm_employees {
};

export interface Employee {
  id: string;
  personNumber: string;
  displayName: string;
  firstName: string;
  lastName: string;
  workEmail: string;
  title: string;
  departmentId: string;
  departmentName: string;
  assignmentStatusType: string;
  startDate: string;
  terminationDate: string;
  managerId: string;
  managerName: string;
  workLocationName: string;
  workLocationType: string;
  correspondenceLanguage: string | null;
  bloodType: string | null;
  dateOfBirth: string | null;
  dateOfDeath: string | null;
  countryOfBirth: string | null;
  regionOfBirth: string | null;
  townOfBirth: string | null;
  applicantNumber: string | null;
  createdBy: string;
  lastUpdatedBy: string;
  creationDate: string;
  lastUpdateDate: string;
  workLocationAddress: {  addressLine1: string | null;
  addressLine2: string | null;
  townOrCity: string | null;
  region2: string | null;
  country: string;
  postalCode: string | null;
  addressType: string;
  primaryFlag: boolean;};
  addresses: (string | null | string | null | string | null | string | null | string | string | null | string | boolean)[];
  phones: (string | string | boolean)[];
  emails: (string | string | boolean)[];
};
