import { createSync, type ProxyConfiguration } from 'nango';
import { z } from 'zod';

const CustomFieldSchema = z
    .object({
        id: z
            .string()
            .describe(
                "Unique record ID used for deduplication. Mirrors Constant Contact's custom_field_id, which is the only stable identifier of a custom field definition."
            ),
        custom_field_id: z
            .string()
            .describe("Constant Contact's unique identifier for the custom field definition. Use this ID when setting custom field values on a contact."),
        label: z.string().describe("Display label of the custom field, e.g. 'Favorite Color'."),
        name: z
            .string()
            .describe(
                'Machine-readable slug derived from the label. Regenerated by Constant Contact whenever the label is updated, so do not rely on it as a stable key.'
            ),
        type: z.string().describe("Data type of the custom field values, e.g. 'string'."),
        version: z.number().describe('Version number of the custom field definition.'),
        created_at: z.string().describe('ISO 8601 timestamp of when the custom field was created.'),
        updated_at: z.string().describe('ISO 8601 timestamp of when the custom field was last updated.')
    })
    .describe('A Constant Contact custom field definition that extends contacts with additional properties.');

const CustomFieldResponseSchema = z.object({
    custom_field_id: z.string(),
    label: z.string(),
    name: z.string(),
    type: z.string(),
    version: z.number(),
    created_at: z.string(),
    updated_at: z.string()
});

const sync = createSync({
    description: 'Sync contact custom field definitions.',
    version: '1.0.0',
    frequency: 'every hour',
    autoStart: true,
    models: {
        CustomField: CustomFieldSchema
    },

    exec: async (nango) => {
        // Full refresh: the endpoint has no changed-since filter and the dataset is
        // bounded (max 100 custom fields per account), so every run re-crawls the
        // complete collection between trackDeletesStart/trackDeletesEnd.
        await nango.trackDeletesStart('CustomField');

        const proxyConfig: ProxyConfiguration = {
            // https://v3.developer.constantcontact.com/api_reference/index.html
            endpoint: '/v3/contact_custom_fields',
            paginate: {
                type: 'link',
                link_path_in_response_body: '_links.next.href',
                response_path: 'custom_fields',
                limit_name_in_request: 'limit',
                limit: 100
            },
            retries: 3
        };

        for await (const batch of nango.paginate<unknown>(proxyConfig)) {
            const customFields = batch.map((item) => {
                // Throw on parse failure: skipping a record inside a delete-tracked
                // scan would falsely mark it as deleted.
                const customField = CustomFieldResponseSchema.parse(item);
                return {
                    id: customField.custom_field_id,
                    custom_field_id: customField.custom_field_id,
                    label: customField.label,
                    name: customField.name,
                    type: customField.type,
                    version: customField.version,
                    created_at: customField.created_at,
                    updated_at: customField.updated_at
                };
            });

            if (customFields.length > 0) {
                await nango.batchSave(customFields, 'CustomField');
            }
        }

        await nango.trackDeletesEnd('CustomField');
    }
});

export type NangoSyncLocal = Parameters<(typeof sync)['exec']>[0];
export default sync;
