// ---------------------------
// This file was generated by Nango (v0.53.0)
// You can version this file
// ---------------------------

export interface SuccessResponse {
    success: boolean;
}

export interface IdEntity {
    id: string;
}

export interface User {
    id: string;
    email: string;
    firstName: string;
    lastName: string;
}

export interface CreateUser {
    firstName: string;
    lastName: string;
    email: string;
}

export interface TrackingCode {
    type?: 'tracking_code';
    name?: string;
    value?: string;
}

export interface BoxCreateUser {
    firstName: string;
    lastName: string;
    email: string;
    address?: string;
    can_see_managed_users?: boolean;
    external_app_user_id?: string;
    is_exempt_from_device_limits?: boolean;
    is_exempt_from_login_verification?: boolean;
    is_external_collab_restricted?: boolean;
    is_platform_access_only?: boolean;
    is_sync_enabled?: boolean;
    job_title?: string;
    language?: string;
    phone?: string;
    role?: 'coadmin' | 'user';
    space_amount?: number;
    status?: 'active' | 'inactive' | 'cannot_delete_edit' | 'cannot_delete_edit_upload';
    timezone?: string;
    tracking_codes?: TrackingCode[];
}

export interface Enterprise {
    id: string;
    type: string;
    name: string;
}

export interface NotificationEmail {
    email: string;
    is_confirmed: boolean;
}

export interface CreatedUser {
    id: string;
    type: string;
    address?: string;
    avatar_url?: string;
    can_see_managed_users: boolean;
    created_at: string;
    enterprise: Enterprise;
    external_app_user_id?: string;
    hostname: string;
    is_exempt_from_device_limits: boolean;
    is_exempt_from_login_verification: boolean;
    is_external_collab_restricted: boolean;
    is_platform_access_only: boolean;
    is_sync_enabled: boolean;
    job_title?: string;
    language?: string;
    login: string;
    max_upload_size: number;
    modified_at: string;
    name: string;
    notification_email: NotificationEmail;
    phone?: string;
    role: string;
    space_amount: number;
    space_used: number;
    status: string;
    timezone?: string;
    tracking_codes?: TrackingCode[];
}

export interface BoxDeleteUser {
    id: string;
    force?: boolean;
    notify?: boolean;
}
