// ---------------------------
// This file was generated by Nango (v0.66.0)
// You can version this file
// ---------------------------

export interface SyncMetadata_teamtailor_candidates {
};

export interface TeamtailorCandidate {
  id: string;
  type: string;
  links: {  self: string;};
  attributes: {  connected: boolean;
  consent_future_jobs_at: Date;
  created_at: Date;
  updated_at: Date;
  email: string;
  facebook_id: string;
  facebook_profile: string;
  first_name: string;
  internal: boolean;
  last_name: string;
  linkedin_profile: string;
  linkedin_uid: string;
  linkedin_url: string;
  original_resume: string;
  phone: string;
  picture: string;
  pitch: string;
  referring_site: string;
  referring_url: string;
  referred: boolean;
  resume: string;
  sourced: boolean;
  tags: any[];
  unsubscribed: boolean;};
  relationships: {  activities: {  links: {  self: string;
  related: string;};};
  department: {  links: {  self: string;
  related: string;};};
  role: {  links: {  self: string;
  related: string;};};
  regions: {  links: {  self: string;
  related: string;};};
  job_applications: {  links: {  self: string;
  related: string;};};
  questions: {  links: {  self: string;
  related: string;};};
  answers: {  links: {  self: string;
  related: string;};};
  locations: {  links: {  self: string;
  related: string;};};
  uploads: {  links: {  self: string;
  related: string;};};
  custom_field_values: {  links: {  self: string;
  related: string;};};
  partner_results: {  links: {  self: string;
  related: string;};};};
};
