// ---------------------------
// This file was generated by Nango (v0.57.3)
// You can version this file
// ---------------------------

export interface SuccessResponse {
  success: boolean;
};

export interface TableView {
  id: string;
  name: string;
  type: string;
};

export interface TableField {
  id: string;
  description: string;
  name: string;
  type: string;
  options?: {  [key: string]: any;};
};

export interface Table {
  baseId: string;
  baseName: string;
  id: string;
  name: string;
  views: TableView[];
  fields: TableField[];
  primaryFieldId: string;
};

export interface Base {
  id: string;
  name: string;
  permissionLevel: 'none' | 'read' | 'comment' | 'edit' | 'create';
};

export interface BaseId {
  baseId: string;
};

export interface WebhookSpecification {
  options: {  filters: {  recordChangeScope?: string;
  dataTypes: string[];
  changeTypes?: string[];
  fromSources?: string[];
  sourceOptions?: {  formPageSubmission?: {  pageId: string;};
  formSubmission?: {  viewId: string;};};
  watchDataInFieldIds?: string[];
  watchSchemasOfFieldIds?: string[];};
  includes?: {  includeCellValuesInFieldIds?: string[] | 'all';
  "includePreviousCellValues:"?: boolean;
  includePreviousFieldDefinitions?: boolean;};};
};

export interface NotificationResult {
  success: boolean;
  error?: {  message: string;};
  completionTimestamp?: string;
  durationMs?: number;
  retryNumber?: number;
  willBeRetried?: boolean;
};

export interface Webhook {
  id: string;
  areNotificationsEnabled: boolean;
  cursorForNextPayload: number;
  isHookEnabled: boolean;
  lastSuccessfulNotificationTime: string | null;
  expirationTime?: string | undefined;
  specification: WebhookSpecification;
  lastNotificationResult: NotificationResult | null;
};

export interface WebhookResponse {
  webhooks: Webhook[];
};

export interface CreateWebhook {
  baseId: string;
  specification: WebhookSpecification;
};

export interface WebhookCreated {
  id: string;
  expirationTime: string;
};

export interface DeleteWebhook {
  baseId: string;
  webhookId: string;
};

export interface UserInformation {
  id: string;
  email: string | null;
};
