// Generated by ts-to-zod
import { z } from 'zod';

export const optionalBackfillSettingSchema = z.object({
    backfillPeriodMs: z.number()
});

export const attachmentsSchema = z.object({
    filename: z.string(),
    mimeType: z.string(),
    size: z.number(),
    attachmentId: z.string()
});

export const gmailEmailSchema = z.object({
    id: z.string(),
    sender: z.string(),
    recipients: z.union([z.string(), z.undefined()]).optional(),
    date: z.string(),
    subject: z.string(),
    body: z.string(),
    attachments: z.array(attachmentsSchema),
    threadId: z.string()
});

export const gmailEmailInputSchema = z.object({
    from: z.string(),
    to: z.string(),
    headers: z.union([z.record(z.string(), z.any()), z.undefined()]),
    subject: z.string(),
    body: z.string()
});

export const emailHeaderSchema = z.object({
    headerName: z.string(),
    headerValue: z.string()
});

export const gmailEmailSentOutputSchema = z.object({
    id: z.string(),
    threadId: z.string()
});

export const documentInputSchema = z.object({
    threadId: z.string(),
    attachmentId: z.string()
});

export const anonymousGooglemailActionFetchattachmentOutputSchema = z.string();
