import { z } from 'zod';
import { createAction } from 'nango';

const InputSchema = z.object({
    query: z.string().optional().describe('Search query to match message content. Example: "*"'),
    date_from: z.string().optional().describe('Start date to search from in YYYY-MM-DD format. Example: "2026-07-01"'),
    date_to: z.string().optional().describe('End date to search to in YYYY-MM-DD format. Example: "2026-07-21"'),
    tags: z.array(z.string()).optional().describe('Tags to filter by. Example: ["newsletter"]'),
    senders: z.array(z.string()).optional().describe('Senders to filter by. Example: ["sender@example.com"]')
});

const TimeSeriesItemSchema = z.object({
    time: z.string().describe('The hour as a UTC date string in YYYY-MM-DD HH:MM:SS format'),
    sent: z.number().describe('The number of emails that were sent during the hour'),
    hard_bounces: z.number().describe('The number of emails that hard bounced during the hour'),
    soft_bounces: z.number().describe('The number of emails that soft bounced during the hour'),
    rejects: z.number().describe('The number of emails that were rejected during the hour'),
    complaints: z.number().describe('The number of spam complaints received during the hour'),
    opens: z.number().describe('The number of emails opened during the hour'),
    unique_opens: z.number().describe('The number of unique opens generated by messages sent during the hour'),
    clicks: z.number().describe('The number of tracked URLs clicked during the hour'),
    unique_clicks: z.number().describe('The number of unique clicks generated by messages sent during the hour'),
    unsubs: z.number().describe('The number of unsubscribes during the hour')
});

const OutputSchema = z.object({
    stats: z.array(TimeSeriesItemSchema).describe('Aggregated hourly stats for matching messages')
});

const action = createAction({
    description: 'Search recently sent messages and return hourly send/open/click/bounce stats instead of individual messages.',
    version: '1.0.0',
    input: InputSchema,
    output: OutputSchema,
    scopes: [],

    exec: async (nango, input): Promise<z.infer<typeof OutputSchema>> => {
        const response = await nango.post({
            // https://mailchimp.com/developer/transactional/api/messages/search-messages-by-hour/
            endpoint: '/1.3/messages/search-time-series',
            data: {
                ...(input.query !== undefined && { query: input.query }),
                ...(input.date_from !== undefined && { date_from: input.date_from }),
                ...(input.date_to !== undefined && { date_to: input.date_to }),
                ...(input.tags !== undefined && { tags: input.tags }),
                ...(input.senders !== undefined && { senders: input.senders })
            },
            retries: 3
        });

        const providerResponse = z.array(TimeSeriesItemSchema).parse(response.data);

        return {
            stats: providerResponse
        };
    }
});

export type NangoActionLocal = Parameters<(typeof action)['exec']>[0];
export default action;
