// ---------------------------
// This file was generated by Nango (v0.68.1)
// You can version this file
// ---------------------------

export interface ActionInput_fireflies_addtolive {
  query: string;
  variables: {};
};

export interface ActionOutput_fireflies_addtolive {
  data: {};
};
