// ---------------------------
// This file was generated by Nango (v0.65.0)
// You can version this file
// ---------------------------

export interface FirefliesAddtoLiveInput {
    query: string;
    variables: Record<string, any>;
}

export interface FirefliesAddtoLiveResponse {
    data: Record<string, any>;
}
