// ---------------------------
// This file was generated by Nango (v0.68.1)
// You can version this file
// ---------------------------

export interface SyncMetadata_greenhouse_basic_applications {
};

export interface GreenhouseApplication {
  id: string;
  candidate_id: string;
  prospect: boolean;
  applied_at: Date;
  rejected_at: Date;
  last_activity_at: Date;
  location: {  address: string;};
  source: {  id: string;
  public_name: string;};
  credited_to: {  id: string;
  first_name: string;
  last_name: string;
  name: string;
  employee_id: string;};
  rejection_reason: {  id: string;
  name: string;
  type: {  id: string;
  name: string;};};
  rejection_details: {  custom_fields: {};
  keyed_custom_fields: {};};
  jobs: string[];
  job_post_id: string;
  status: string;
  current_stage: {  id: string;
  name: string;};
  answers: string[];
  prospective_office: {  primary_contact_user_id: string;
  parent_id: string;
  name: string;
  location: {  name: string;};
  id: string;
  external_id: string;
  child_ids: string[];};
  prospective_department: {  parent_id: string;
  name: string;
  id: string;
  external_id: string;
  child_ids: string[];};
  prospect_detail: {  prospect_pool: {  id: string;
  name: string;};
  prospect_stage: {  id: string;
  name: string;};
  prospect_owner: {  id: string;
  name: string;};};
  custom_fields: {};
  keyed_custom_fields: {};
  attachments: any[];
};

export interface SyncMetadata_greenhouse_basic_candidates {
};

export interface GreenhouseCandidate {
  id: string;
  first_name: string;
  last_name: string;
  company: string;
  title: string;
  created_at: Date;
  updated_at: Date;
  last_activity: Date;
  is_private: boolean;
  photo_url: string;
  attachments: any[];
  application_ids: string[];
  phone_numbers: string[];
  addresses: any[];
  email_addresses: string[];
  website_addresses: string[];
  social_media_addresses: string[];
  recruiter: {  id: string;
  first_name: string;
  last_name: string;
  name: string;
  employee_id: string;};
  coordinator: {  id: string;
  first_name: string;
  last_name: string;
  name: string;
  employee_id: string;};
  can_email: boolean;
  tags: string[];
  applications: string[];
  educations: string[];
  employments: string[];
  linked_user_ids: string;
  custom_fields: {};
  keyed_custom_fields: {};
};

export interface SyncMetadata_greenhouse_basic_jobs {
};

export interface GreenhouseJob {
  id: string;
  name: string;
  requisition_id: string;
  notes: string;
  confidential: boolean;
  status: string;
  created_at: Date;
  opened_at: Date;
  closed_at: Date;
  updated_at: Date;
  is_template: boolean;
  copied_from_id: string;
  departments: string[];
  offices: string[];
  custom_fields: {};
  keyed_custom_fields: {};
  hiring_team: {  hiring_managers: string[];
  recruiters: string[];
  coordinators: string[];
  sourcers: string[];};
  openings: string[];
};
