// Generated by ts-to-zod
import { z } from 'zod';

export const kustomerConversationSchema = z.object({
    type: z.string(),
    id: z.string(),
    attributes: z.record(z.any()),
    relationships: z.record(z.any()),
    links: z.record(z.any())
});
