// ---------------------------
// This file was generated by Nango (v0.53.0)
// You can version this file
// ---------------------------

export interface SuccessResponse {
    success: boolean;
}

export interface IdEntity {
    id: string;
}

export interface User {
    id: string;
    email: string;
    firstName: string;
    lastName: string;
}

export interface CreateUser {
    firstName: string;
    lastName: string;
    email: string;
}
