// Generated by ts-to-zod
import { z } from 'zod';

export const successResponseSchema = z.object({
    success: z.boolean()
});

export const idEntitySchema = z.object({
    id: z.string()
});

export const emailEntitySchema = z.object({
    email: z.string()
});

export const userSchema = z.object({
    id: z.string(),
    email: z.string(),
    firstName: z.string(),
    lastName: z.string()
});

export const createUserSchema = z.object({
    firstName: z.string(),
    lastName: z.string(),
    email: z.string()
});

export const gustoCreateUserSchema = z.object({
    firstName: z.string(),
    lastName: z.string(),
    email: z.string(),
    middleInitial: z.string().optional(),
    preferredFirstName: z.string().optional(),
    dateOfBirth: z.string(),
    ssn: z.string().optional(),
    selfOnboarding: z.boolean().optional()
});

export const gustoDeleteUserSchema = z.object({
    email: z.string(),
    effectiveDate: z.string().optional(),
    runTerminationPayroll: z.boolean().optional()
});
