// ---------------------------
// This file was generated by Nango (v0.56.1)
// You can version this file
// ---------------------------

export interface EvaluAgentGroup {
    id: string;
    name: string;
    level: string;
    active: boolean;
    parent: string;
    hasChildren: boolean;
    isCustomReportingGroup: boolean;
}

export interface EvaluAgentUser {
    id: string;
    forename?: string;
    surname?: string;
    email: string;
    username: string;
    startDate: Date;
    active: boolean;
    thirdPartyId: string | number;
}

export interface EvaluAgentRole {
    id: string;
    title: string;
    name: string;
}
