// ---------------------------
// This file was generated by Nango (v0.62.0)
// You can version this file
// ---------------------------

export interface ClariCopilotCall {
    id: string;
    source_id: string;
    title: string;
    users: any[];
    externalParticipants: any[];
    status: string;
    bot_not_join_reason: string[];
    type: string;
    time: string;
    icaluid: string;
    calendar_id: string;
    recurring_event_id: string;
    original_start_time: string;
    last_modified_time: string;
    audio_url: string;
    video_url: string;
    disposition: string;
    deal_name: string;
    deal_value: string;
    deal_close_date: string;
    deal_stage_before_call: string;
    account_name: string;
    contact_names: string[];
    crm_info: { source_crm: string; deal_id: string; account_id: string; contact_ids: string[] };
    bookmark_timestamps: string[];
    metrics: {
        talk_listen_ratio: number;
        num_questions_asked: number;
        num_questions_asked_by_reps: number;
        call_duration: number;
        total_speak_duration: number;
        longest_monologue_duration: number;
        longest_monologue_start_time: number;
        engaging_questions: number;
        categories: string[];
    };
    call_review_page_url: string;
    deal_stage_live: string;
    transcript: string[];
    summary: { full_summary: string; topics_discussed: string[]; key_action_items: string[] };
    competitor_sentiments: string[];
}
