// ---------------------------
// This file was generated by Nango (v0.57.0)
// You can version this file
// ---------------------------

export interface LinkedinVideoPost {
    text: string;
    videoURN: string;
    videoTitle: string;
    ownerId: string;
}

export interface CreateLinkedInPostWithVideoResponse {
    succcess: boolean;
}

export interface LinkedInMessageContent {
    format: string;
    fallback: string;
    formatVersion: number;
    content?: { string?: string };
}

export interface ContentClassification {
    classification: string;
}

export interface LinkedInActivityData {
    actor: string;
    createdAt: number;
    attachments: any[];
    author: string;
    messageContexts: any[];
    thread: string;
    message?: string;
    version?: number;
    contentCertificationToken?: string;
}

export interface LinkedInMessage {
    id: number;
    resourceId: string;
    method: string;
    owner: string;
    actor: string;
    activityId: string;
    processedAt: number;
    capturedAt: number;
    activityStatus: string;
    thread: string | null;
    author: string | null;
    createdAt: number | null;
    isDeleted: boolean;
    deletedAt?: number;
    activityData?: LinkedInActivityData;
    content?: LinkedInMessageContent | null;
    deliveredAt?: number;
    mailbox?: string;
    contentClassification?: ContentClassification | null;
    attachments?: any[];
    contentUrns?: any[];
    extensionContent?: any;
    messageContexts?: any[];
}
