// ---------------------------
// This file was generated by Nango (v0.64.1)
// You can version this file
// ---------------------------

export interface SyncMetadata_smartsheet_users {
};

export interface User {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
};

export interface ActionInput_smartsheet_createuser {
  firstName: string;
  lastName: string;
  email: string;
};

export interface ActionOutput_smartsheet_createuser {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
};

export interface ActionInput_smartsheet_deleteuser {
  id: string;
};

export interface ActionOutput_smartsheet_deleteuser {
  success: boolean;
};

export interface ActionInput_smartsheet_disableuser {
  id: string;
};

export interface ActionOutput_smartsheet_disableuser {
  success: boolean;
};
