// ---------------------------
// This file was generated by Nango (v0.63.0)
// You can version this file
// ---------------------------

export interface SyncMetadata_attio_people {
};

export interface AttioPerson {
  id: string;
  workspace_id: string;
  created_at: string;
  web_url: string;
  first_name: string;
  last_name: string;
  full_name: string;
  email_addresses: (string | string)[];
  phone_numbers: (string | string)[];
  job_title: (string | string | null | {  type: string;
  id: string | null;} | string | string)[];
  company_id: string;
  description: (string | string | null | {  type: string;
  id: string | null;})[];
  avatar_url: (string | string | null | {  type: string;
  id: string | null;})[];
  social_links: {  linkedin: string[];
  twitter: string[];
  facebook: string[];
  instagram: string[];
  angellist: string[];};
  location: {  line_1: string;
  line_2: string;
  city: string;
  state: string;
  postal_code: string;
  country_code: string;};
};

export interface SyncMetadata_attio_companies {
};

export interface AttioCompany {
  id: string;
  workspace_id: string;
  created_at: string;
  web_url: string;
  name: string;
  domains: (string | string)[];
  description: string;
  team_member_ids: string[];
  location: {  country_code: string;
  line_1: string | null;
  line_2: string | null;
  city: string;
  state: string;
  postal_code: string;};
  categories: string[];
  logo_url: string;
  twitter_follower_count: number;
  foundation_date: string;
  estimated_arr_usd: number;
  social_links: {  linkedin: string[];
  twitter: string[];
  facebook: string[];
  instagram: string[];
  angellist: string[];};
};

export interface SyncMetadata_attio_deals {
};

export interface AttioDeal {
  id: string;
  workspace_id: string;
  created_at: string;
  web_url: string;
  name: string;
  stage: string;
  stage_id: string;
  owner_id: string;
  value: number;
  currency: string;
  associated_people_ids: string[];
  associated_company_id: string;
};
