// ---------------------------
// This file was generated by Nango (v0.63.0)
// You can version this file
// ---------------------------

export interface SyncMetadata_expensify_users {
};

export interface ExpsensifyNullableUser {
  id: string;
  firstName: string | null;
  lastName: string | null;
  email: string;
};

export interface ActionInput_expensify_createuser {
  firstName: string;
  lastName: string;
  email: string;
};

export interface ActionOutput_expensify_createuser {
  id: string;
  firstName: string | null;
  lastName: string | null;
  email: string;
};

export interface ActionInput_expensify_disableuser {
  id: string;
  email: string;
};

export interface ActionOutput_expensify_disableuser {
  success: boolean;
};

/** @deprecated It is recommended to use a Model */
export type ActionInput_expensify_listpolicies = void

export interface ActionOutput_expensify_listpolicies {
  policies: (string | string | string | boolean | string | boolean | boolean | boolean | boolean | boolean | string | boolean | boolean | boolean | string | string | boolean | string | boolean | boolean | boolean | string | number | boolean)[];
};
