// ---------------------------
// This file was generated by Nango (v0.63.0)
// You can version this file
// ---------------------------

export interface SyncMetadata_gem_candidates {
};

export interface Candidate {
  id: string;
  first_name: string;
  last_name: string;
  company: string | null;
  title: string | null;
  attachments: (string | string | string | string)[];
  phone_numbers: (string | string)[];
  email_addresses: (string | string | boolean)[];
  social_media_addresses: (string)[];
  tags: string[];
  educations: (string | string | string | string | string | string)[];
  employments: (string | string | string | string | string)[];
  linked_user_ids: string[];
  created_at: string;
  updated_at: string | null;
  last_activity: string | null;
  deleted_at: string | null;
  is_private: boolean;
  applications: (string | string | string | string | null | string | {  id: string;
  public_name: string;} | string | {  id: string;
  name: string;
  type: {  id: string;
  name: string;};} | null | (string | string)[] | string | string | {  id: string;
  name: string;} | string | null)[];
  application_ids: string[];
};

export interface SyncMetadata_gem_jobposts {
};

export interface JobPost {
  id: string;
  title: string;
  active: boolean;
  live: boolean;
  first_published_at: string | null;
  job_id: string;
  content: string;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
};

export interface SyncMetadata_gem_jobstages {
};

export interface JobStage {
  id: string;
  name: string;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
  active: boolean;
  job_id: string;
  priority: number;
  interviews: (string | string | boolean | number | (string | string | string | string | string)[] | {  id: string;
  content: string;
  questions: (string | string)[];} | string | null | string)[];
};

export interface SyncMetadata_gem_users {
};

export interface TeamMemberUser {
  id: string;
  name: string;
  email: string;
};

export interface SyncMetadata_gem_locations {
};

export interface Location {
  id: string;
  name: string;
  location: {  name: string;};
  parent_id: string;
  child_ids: string[];
  parent_office_external_id: string;
  child_office_external_ids: string[];
  deleted_at: string;
};

export interface SyncMetadata_gem_applications {
};

export interface Application {
  id: string;
  candidate_id: string;
  applied_at: string;
  rejected_at: string | null;
  last_activity_at: string;
  source: {  id: string;
  public_name: string;};
  credited_to: string;
  rejection_reason: {  id: string;
  name: string;
  type: {  id: string;
  name: string;};} | null;
  jobs: (string | string)[];
  job_post_id: string;
  status: string;
  current_stage: {  id: string;
  name: string;};
  deleted_at: string | null;
};

export interface SyncMetadata_gem_jobs {
};

export interface Job {
  id: string;
  name: string;
  requisition_id: string;
  confidential: boolean;
  status: string;
  created_at: string;
  opened_at: string;
  closed_at: string | null;
  deleted_at: string | null;
  updated_at: string;
  is_template: boolean;
  departments: (string | string | string | string[] | string | string[] | string)[];
  offices: (string | string | {  name: string;} | string | string[] | string | string[] | string)[];
  hiring_team: {  hiring_managers: (string | string | string | string | string)[] | null;
  recruiters: (string | string | string | string | string)[] | null;
  coordinators: (string | string | string | string | string)[] | null;
  sourcers: (string | string | string | string | string)[] | null;};
};

export interface ActionInput_gem_createcandidate {
  created_by: string;
  first_name: string | null;
  last_name: string | null;
  nickname: string | null;
  emails: (string | boolean)[] | null;
  linked_in_handle: string | null;
  title: string | null;
  company: string | null;
  location: string | null;
  school: string | null;
  education_info: (string | null | string | null | string | null | string | null | string | null | string | null | string | null | string | null | string | null)[] | null;
  work_info: (string | null | string | null | string | null | string | null | boolean | null)[] | null;
  profile_urls: string[] | null;
  custom_fields: (string | string)[] | null;
  phone_number: string | null;
  project_ids: string[] | null;
  sourced_from: string | null;
  autofill: boolean;
};

export interface ActionOutput_gem_createcandidate {
  id: string;
  created_at: number;
  created_by: string;
  last_updated_at: number | null;
  candidate_greenhouse_id: string | null;
  first_name: string | null;
  last_name: string | null;
  nickname: string | null;
  weblink: string;
  emails: (string | boolean)[];
  phone_number: string | null;
  location: string | null;
  linked_in_handle: string | null;
  profiles: (string | string | string)[];
  company: string | null;
  title: string | null;
  school: string | null;
  education_info: (string | null | string | null | string | null | string | null | string | null | string | null | string | null | string | null | string | null)[];
  work_info: (string | null | string | null | string | null | string | null | boolean | null)[];
  custom_fields: (string | string | string | string | any | string | string[] | string | any)[];
  due_date: {  date: string;
  user_id: string;
  note: string | null;} | null;
  project_ids: string[] | null;
  sourced_from: string | null;
  gem_source: string | null;
};

export interface ActionInput_gem_uploadresume {
  candidate_id: string;
  user_id: string;
  resume_file: string;
};

export interface ActionOutput_gem_uploadresume {
  id: string;
  candidate_id: string;
  created_at: number;
  user_id: string;
  filename: string;
  download_url: string;
};

export interface ActionInput_gem_createnote {
  user_id: string;
  body: string;
  visibility: 'private' | 'public';
  candidate_id: string;
};

export interface ActionOutput_gem_createnote {
  id: string;
  created_at: string;
  body: string;
  user: {  id: string;
  name: string;
  first_name: string;
  last_name: string;
  employee_id: string;};
  private: boolean;
  visibility: 'public' | 'private';
};

export interface ActionInput_gem_updateapplication {
  source_id: string;
  application_id: string;
};

export interface ActionOutput_gem_updateapplication {
  id: string;
  candidate_id: string;
  applied_at: string;
  rejected_at: string | null;
  last_activity_at: string;
  source: {  id: string;
  public_name: string;};
  credited_to: string;
  rejection_reason: {  id: string;
  name: string;
  type: {  id: string;
  name: string;};} | null;
  jobs: (string | string)[];
  job_post_id: string;
  status: string;
  current_stage: {  id: string;
  name: string;};
  deleted_at: string | null;
};
