// ---------------------------
// This file was generated by Nango (v0.57.3)
// You can version this file
// ---------------------------

export interface OptionalBackfillSetting {
  backfillPeriodDays: number;
};

export interface IdEntity {
  id: string;
};

export interface SuccessResponse {
  success: boolean;
};

export interface ActionResponseError {
  message: string;
};

export interface CreateUser {
  firstName: string;
  lastName: string;
  email: string;
};

export interface ZoomCreateUser {
  firstName: string;
  lastName: string;
  email: string;
  action?: 'create' | 'autoCreate' | 'custCreate' | 'ssoCreate';
  display_name?: string;
  type?: 'basic' | 'licensed' | 'UnassignedWithoutMeetingsBasic' | 'None';
};

export interface User {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
};

export interface UserInformation {
  id: string;
  email: string;
};

export interface Meeting {
  id: string;
  topic: string;
  startTime: string;
  duration: number;
  timezone: string;
  joinUrl: string;
  createdAt: string;
};

export interface CreateMeeting {
  topic: string;
  type: 'instant' | 'scheduled' | 'recurringNoFixed' | 'recurring' | 'screenShareOnly';
  agenda?: string;
  default_password?: boolean;
  duration?: number;
  password?: string;
  pre_schedule?: boolean;
  recurrence?: {  end_date_time?: string;
  end_times?: number;
  monthly_day?: number;
  monthly_week?: number;
  monthly_week_day?: number;
  repeat_interval?: number;
  type?: 'daily' | 'weekly' | 'monthly';
  weekly_days?: 'sunday' | 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday';};
  settings?: {  host_video?: boolean;
  participant_video?: boolean;
  join_before_host?: boolean;
  mute_upon_entry?: boolean;
  approval_type?: 'automatic' | 'manually' | 'notRequired';
  registration_type?: 'registerOnceAttendAny' | 'registerEveryTime' | 'registerOnceSelectOccurrences';
  audio?: 'both' | 'telephony' | 'voip' | 'thirdParty';
  auto_recording?: 'local' | 'cloud' | 'none';
  waiting_room: boolean;};
  schedule_for?: string;
  start_time?: string;
  template_id?: string;
  timezone?: string;
};

export interface RecordingFile {
  id: string;
  deletedTime?: string;
  downloadUrl: string;
  filePath?: string;
  fileSize: number;
  fileType: 'MP4' | 'M4A' | 'CHAT' | 'TRANSCRIPT' | 'CSV' | 'TB' | 'CC' | 'CHAT_MESSAGE' | 'SUMMARY' | 'TIMELINE';
  fileExtension: 'MP4' | 'M4A' | 'TXT' | 'VTT' | 'CSV' | 'JSON' | 'JPG';
  meetingId: string;
  playUrl?: string;
  recordingEnd: string;
  recordingStart: string;
  recordingType: 'shared_screen_with_speaker_view(CC)' | 'shared_screen_with_speaker_view' | 'shared_screen_with_gallery_view' | 'active_speaker' | 'gallery_view' | 'shared_screen' | 'audio_only' | 'audio_transcript' | 'chat_file' | 'poll' | 'host_video' | 'closed_caption' | 'timeline' | 'thumbnail' | 'audio_interpretation' | 'summary' | 'summary_next_steps' | 'summary_smart_chapters' | 'sign_interpretation' | 'production_studio';
  status: 'completed';
  autoDelete?: boolean;
  autoDeleteDate?: string;
  playPasscode: string;
};
