// ---------------------------
// This file was generated by Nango (v0.56.1)
// You can version this file
// ---------------------------

export interface Account {
    id: number;
    name: string;
    product: string;
    href: string;
    app_href: string;
    hidden?: boolean;
}

export interface UserInformation {
    identity: { id: number; firstName: string; lastName: string; email: string };
    accounts: Account[];
}

export interface DockItem {
    id: number;
    title: string;
    name: string;
    enabled: boolean;
    position: number | null;
    url: string;
    app_url: string;
}

export interface BasecampProject {
    id: number;
    status: string;
    created_at: string;
    updated_at: string;
    name: string;
    description: string | null;
    purpose: string;
    clients_enabled: boolean;
    timesheet_enabled?: boolean;
    color?: string | null;
    last_needle_color?: string | null;
    last_needle_position?: string | null;
    previous_needle_position?: string | null;
    bookmark_url: string;
    url: string;
    app_url: string;
    dock: DockItem[];
    bookmarked: boolean;
}

export interface BasecampProjectsResponse {
    projects: BasecampProject[];
}

export interface BasecampTodolist {
    id: number;
    status?: string;
    visible_to_clients?: boolean;
    created_at?: string;
    updated_at?: string;
    title?: string;
    inherits_status?: boolean;
    type?: string;
    url?: string;
    app_url?: string;
    bookmark_url?: string;
    subscription_url?: string;
    comments_count?: number;
    comments_url?: string;
    position?: number;
    parent?: any;
    bucket?: any;
    creator?: any;
    description?: string;
    completed?: boolean;
    completed_ratio?: string;
    name?: string;
    todos_url?: string;
    groups_url?: string;
    app_todos_url?: string;
}

export interface BasecampTodolistsResponse {
    todolists: BasecampTodolist[];
}

export interface BasecampCreateTodoInput {
    projectId: number;
    todoListId: number;
    content: string;
    description?: string;
    due_on?: string;
    starts_on?: string;
    notify?: boolean;
    assigneeEmails?: string[];
    completionSubscriberEmails?: string[];
}

export interface BasecampFetchTodolistsInput {
    projectId: number;
    todoSetId: number;
}

export interface BasecampTodoParent {
    id: number;
    title: string;
    type: string;
    url: string;
    app_url: string;
}

export interface BasecampTodoBucket {
    id: number;
    name: string;
    type: string;
}

export interface BasecampTodoResponse {
    id: number;
    status: string;
    visible_to_clients: boolean;
    created_at: string;
    updated_at: string;
    title: string;
    inherits_status: boolean;
    type: string;
    url: string;
    app_url: string;
    bookmark_url: string;
    subscription_url: string;
    comments_count: number;
    comments_url: string;
    position: number;
    parent: BasecampTodoParent;
    bucket: BasecampTodoBucket;
    creator: any;
    description: string;
    completed: boolean;
    content: string;
    starts_on: string;
    due_on: string;
    assignees: any[];
    completion_subscribers: any[];
    completion_url: string;
}

export interface BasecampPerson {
    id: number;
    name: string;
    email_address: string;
    avatar_url?: string;
    admin?: boolean;
    owner?: boolean;
    created_at?: string;
    updated_at?: string;
    attachable_sgid?: string;
    personable_type?: string;
    title?: string | null;
    bio?: string | null;
    location?: string | null;
}

export interface BasecampTodo {
    id: string;
    content: string;
    description?: string | undefined;
    due_on?: string | undefined | null;
    completed: boolean;
    created_at: string;
    updated_at: string;
    bucket_id: number;
    assignees?: BasecampPerson[] | undefined;
}

export interface BasecampCompany {
    id: number;
    name: string;
}

export interface ClientSide {
    url: string;
    app_url: string;
}

export interface Project {
    projectId: number;
    todoSetId: number;
}

export interface TodosMetadata {
    projects: Project[];
}
