// Generated by ts-to-zod
import { z } from 'zod';

export const userSchema = z.object({
    id: z.string(),
    email: z.string(),
    firstName: z.string(),
    lastName: z.string()
});

export const createUserSchema = z.object({
    email: z.string()
});

export const trelloCreateUserSchema = z.object({
    email: z.string(),
    products: z.array(z.string()).optional()
});
