// ---------------------------
// This file was generated by Nango (v0.63.0)
// You can version this file
// ---------------------------

export interface SyncMetadata_dialpad_users {
};

export interface User {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
};

export interface ActionInput_dialpad_createuser {
  firstName: string;
  lastName: string;
  email: string;
  license: string;
  officeId: string;
  autoAssign: boolean;
};

export interface ActionOutput_dialpad_createuser {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
};

export interface ActionInput_dialpad_deleteuser {
  id: string;
};

export interface ActionOutput_dialpad_deleteuser {
  success: boolean;
};
