// ---------------------------
// This file was generated by Nango (v0.53.0)
// You can version this file
// ---------------------------

export interface ActionResponseError {
    message: string;
}

export interface OktaAddGroup {
    description?: string | undefined;
    name: string;
}

export interface OktaUserGroupProfile {
    description: string | null;
    name: string;
}

export interface OktaActiveDirectoryGroupProfile {
    description: string;
    dn: string;
    externalId: string;
    name: string;
    samAccountName: string;
    windowsDomainQualifiedName: string;
}

export interface Group {
    id: string;
    created: string;
    lastMembershipUpdated: string;
    lastUpdated: string;
    objectClass: string[];
    type: 'APP_GROUP' | 'BUILT_IN' | 'OKTA_GROUP';
    profile: OktaUserGroupProfile | OktaActiveDirectoryGroupProfile;
}

export interface OktaAssignRemoveUserGroup {
    groupId: string;
    userId: string;
}

export interface SuccessResponse {
    success: boolean;
}

export interface OktaCreateUser {
    firstName: string;
    lastName: string;
    email: string;
    login: string;
    mobilePhone?: string | undefined | null;
}

export interface User {
    id: string;
    status: string;
    created: string;
    activated: string;
    statusChanged: string;
    lastLogin: string | null;
    lastUpdated: string;
    passwordChanged: string | null;
    type: { id: string };
    profile: { firstName: string | null; lastName: string | null; mobilePhone: string | null; secondEmail: string | null; login: string; email: string };
}
