// Generated by ts-to-zod
import { z } from 'zod';

export const orgToSyncSchema = z.object({
    id: z.string(),
    path: z.string()
});

export const metadataSchema = z.object({
    orgsToSync: z.array(orgToSyncSchema)
});

export const organizationalUnitSchema = z.object({
    id: z.string(),
    name: z.string(),
    createdAt: z.string().nullable(),
    deletedAt: z.string().nullable(),
    description: z.string().nullable(),
    path: z.string().nullable(),
    parentPath: z.string().nullable(),
    parentId: z.string().nullable()
});

export const userSchema = z.object({
    id: z.string(),
    email: z.string(),
    displayName: z.string().nullable(),
    givenName: z.string().nullable(),
    familyName: z.string().nullable(),
    picture: z.union([z.string(), z.undefined()]).nullable(),
    type: z.string(),
    createdAt: z.string().nullable(),
    deletedAt: z.string().nullable(),
    phone: z.object({
        value: z.union([z.string(), z.undefined()]).nullable(),
        type: z.union([z.string(), z.undefined()]).nullable()
    }),
    organizationId: z.union([z.string(), z.undefined()]).nullable(),
    organizationPath: z.union([z.string(), z.undefined()]).nullable(),
    isAdmin: z.boolean().nullable(),
    department: z.string().nullable()
});

export const googleWorkspaceUserTokenSchema = z.object({
    id: z.string(),
    user_id: z.string(),
    app_name: z.string(),
    anonymous_app: z.boolean(),
    scopes: z.string()
});
