export interface SyncMetadata_brightcrowd_bookanalytics {
  bookIds: string[];
  timeframe?: any | undefined | any | undefined | any | undefined | 'all';
};

export interface BookAnalytics {
  id: string;
  email: {  notifications: ({  uri: string;
  topicUri: string;
  status: string;
  messageCount: number;
  openCount: number;
  clickCount: number;
  uniqueOpenCount: number;
  uniqueClickCount: number;
  bounceCount: number;})[];
  invitations: {  messageCount: number;
  uniqueOpenCount: number;
  uniqueClickCount: number;
  bounceCount: number;
  uniqueInvitationOpenUserCount: number;
  uniqueInvitationBounceUserCount: number;};
  web: {  dateRange: string;
  values: {  visitors: number;
  totalPageViews: number;
  sessions: number;
  socialClicks: number;};
  previousValues: {  visitors: number;
  totalPageViews: number;
  sessions: number;
  socialClicks: number;};};
  book: {  values: {  pagesCreated: number;
  pagesUpdated: number;
  taggedUsers: number;};
  previousValues: {  pagesCreated: number;
  pagesUpdated: number;
  taggedUsers: number;};};};
  web: {  dateRange: string;
  values: {  visitors: number;
  totalPageViews: number;
  sessions: number;
  socialClicks: number;};
  previousValues: {  visitors: number;
  totalPageViews: number;
  sessions: number;
  socialClicks: number;};};
  book: {  values: {  pagesCreated: number;
  pagesUpdated: number;
  taggedUsers: number;};
  previousValues: {  pagesCreated: number;
  pagesUpdated: number;
  taggedUsers: number;};};
};

export interface SyncMetadata_brightcrowd_books {
};

export interface Book {
  id: string;
  alias: string;
  name: string;
  pictureId: string | null;
  config: string | null;
  coverPictureId: string | null;
  bannerPictureId: string | null;
  affiliation: {  type: 'OtherAffiliation' | 'UniversityAffiliation' | 'CompanyAffiliation';
  organization?: string | null | undefined;
  major?: string | string[] | undefined;
  degree?: string | string[] | undefined;
  school?: string | string[] | undefined;
  graduationYear?: number | null | undefined;
  specialty?: string | string[] | undefined;
  category?: string | string[] | undefined;
  title?: string | undefined;
  startYear?: number | null | undefined;
  endYear?: number | null | undefined;
  office?: string | string[] | undefined;
  group?: string | string[] | undefined;} | null;
  questions: ({  id: string;
  type: string | null;
  name: string | null;
  description?: string | null | undefined;
  warning?: string | null | undefined;
  route: string | null;
  questionHeader: string | null;
  questionSubheader?: string | null | undefined;
  headline?: string | null | undefined;
  active: boolean;
  required: boolean;
  adminOnly: boolean;
  fields: ({  id: string;
  label: string;
  type: string;
  headline?: string | null | undefined;
  placeholder?: string | null | undefined;
  active: boolean;
  required: boolean;
  maxcount?: number | null | undefined;
  maxlength?: number | null | undefined;
  allowMentions: boolean;
  customizable: boolean;})[];})[];
  flags: string[];
  publishedAt?: string | null | undefined;
  closedAt?: string | null | undefined;
  lockedAt?: string | null | undefined;
  created: string;
  modified: string;
  frontMatter: {  sections: ({  uri: string;
  title: string;
  snippet: string;
  disabled?: boolean | undefined;})[];} | null;
  preface?: {  text: string | null;
  docId?: string | null | undefined;
  video?: string | null | undefined;
  pictures?: string[] | null | undefined;} | null;
};

export interface SyncMetadata_brightcrowd_booksbyid {
  bookIds: string[];
  timeframe?: any | undefined | any | undefined | any | undefined | 'all';
};

export interface BookById {
  id: string;
  alias: string;
  name: string;
  pictureId: string | null;
  config: string | null;
  coverPictureId: string | null;
  bannerPictureId: string | null;
  affiliation: {  type: 'OtherAffiliation' | 'UniversityAffiliation' | 'CompanyAffiliation';
  organization?: string | null | undefined;
  major?: string | string[] | undefined;
  degree?: string | string[] | undefined;
  school?: string | string[] | undefined;
  graduationYear?: number | null | undefined;
  specialty?: string | string[] | undefined;
  category?: string | string[] | undefined;
  title?: string | undefined;
  startYear?: number | null | undefined;
  endYear?: number | null | undefined;
  office?: string | string[] | undefined;
  group?: string | string[] | undefined;} | null;
  questions: ({  id: string;
  type: string | null;
  name: string | null;
  description?: string | null | undefined;
  warning?: string | null | undefined;
  route: string | null;
  questionHeader: string | null;
  questionSubheader?: string | null | undefined;
  headline?: string | null | undefined;
  active: boolean;
  required: boolean;
  adminOnly: boolean;
  fields: ({  id: string;
  label: string;
  type: string;
  headline?: string | null | undefined;
  placeholder?: string | null | undefined;
  active: boolean;
  required: boolean;
  maxcount?: number | null | undefined;
  maxlength?: number | null | undefined;
  allowMentions: boolean;
  customizable: boolean;})[];})[];
  flags: string[];
  publishedAt?: string | null | undefined;
  closedAt?: string | null | undefined;
  lockedAt?: string | null | undefined;
  created: string;
  modified: string;
  frontMatter: {  sections: ({  uri: string;
  title: string;
  snippet: string;
  disabled?: boolean | undefined;})[];} | null;
  preface?: {  text: string | null;
  docId?: string | null | undefined;
  video?: string | null | undefined;
  pictures?: string[] | null | undefined;} | null;
};

export interface SyncMetadata_brightcrowd_pages {
  bookIds: string[];
  timeframe?: any | undefined | any | undefined | any | undefined | 'all';
};

export interface Page {
  id: string;
  alias: string;
  name: string;
  status: 'draft' | 'published' | 'hidden';
  content: {  firstName: string;
  lastName: string;
  previousName?: string | null | undefined;
  suffix?: string | undefined;
  partnerFirstName?: string | null | undefined;
  partnerLastName?: string | null | undefined;
  pronouns?: string | undefined;
  pictureId?: string | null | undefined;
  audioId?: string | null | undefined;};
  pictures?: ({  type: 'profile' | 'content' | 'caption';
  id: string;
  caption?: string | null | undefined;})[] | null;
  videos?: ({  url: string;
  caption?: string | null | undefined;})[] | null;
  tagUsers?: string[] | null | undefined;
  homeTown?: string | null | undefined;
  currentCity?: string | null | undefined;
  campusResidence?: string | null | undefined;
  affiliations?: ({  type: 'OtherAffiliation' | 'UniversityAffiliation' | 'CompanyAffiliation';
  organization?: string | null | undefined;
  major?: string | string[] | undefined;
  degree?: string | string[] | undefined;
  school?: string | string[] | undefined;
  graduationYear?: number | null | undefined;
  specialty?: string | string[] | undefined;
  category?: string | string[] | undefined;
  title?: string | undefined;
  startYear?: number | null | undefined;
  endYear?: number | null | undefined;
  office?: string | string[] | undefined;
  group?: string | string[] | undefined;})[] | null;
  plan?: 'school' | 'work' | 'other' | undefined;
  created: string;
  modifiedByUserAt?: string | null | undefined;
  completedByUserAt?: string | null | undefined;
  externalId?: string | undefined;
};
