import { z } from 'zod';
import { createAction } from 'nango';

const InputSchema = z.object({
    first_name: z.string().optional().describe('The person\'s first name. Example: "James"'),
    last_name: z.string().optional().describe('The person\'s last name. Example: "Smith"'),
    full_name: z
        .string()
        .optional()
        .describe('The person\'s full name. Will split on whitespace to set first_name and last_name fields. Example: "James Smith"'),
    email: z.string().optional().describe('The person\'s primary email address. Example: "james.smith@acme.com"'),
    email2: z.string().optional().describe('The person\'s secondary email address. Example: "james.smith@acme-inc.com"'),
    home_email: z.string().optional().describe('The person\'s non-professional email address. Example: "james.smith@gmail.com"'),
    phone: z.string().optional().describe('The person\'s primary phone number. Example: "123-123-1234"'),
    home_phone: z.string().optional().describe('The person\'s home phone number. Example: "123-123-1234"'),
    mobile: z.string().optional().describe('The person\'s mobile phone number. Example: "123-123-1234"'),
    position: z.string().optional().describe('The person\'s professional position. Example: "VP of Operations"'),
    summary: z.string().optional().describe('Summary or notes on the person. Example: "Friendly, answers my calls."'),
    website: z.string().optional().describe('The person\'s website URL. Example: "http://www.james-smith.com"'),
    company_id: z.number().optional().describe('The ID of the company associated to this person. Example: 1'),
    company_name: z.string().optional().describe('Associates the company with this name to this person, creating it if none matches. Example: "Acme Inc."'),
    user_id: z.number().optional().describe('The ID of the user who owns this person record. Example: 1'),
    lead_status_id: z.number().optional().describe('The ID of the lead status to set for this person. Example: 1'),
    lead_source_id: z.number().optional().describe('The ID of the lead source to set for this person. Example: 1'),
    image_thumb_url: z.string().optional().describe('A link to the person\'s avatar. Example: "https://s3.amazonaws.com/avatar.png"'),
    predefined_contacts_tag_ids: z.array(z.number()).optional(),
    work_address_1: z.string().optional().describe('First line of work address. Example: "Suite 101"'),
    work_address_2: z.string().optional().describe('Second line of work address. Example: "123 Fake St."'),
    work_city: z.string().optional().describe('Work address city. Example: "Denver"'),
    work_state: z.string().optional().describe('Work address state. Example: "Colorado"'),
    work_country: z.string().optional().describe('Work address country. Example: "United States"'),
    work_postal_code: z.string().optional().describe('Work address postal code. Example: "11001"'),
    home_address_1: z.string().optional().describe('First line of home address. Example: "Suite 101"'),
    home_address_2: z.string().optional().describe('Second line of home address. Example: "123 Fake St."'),
    home_city: z.string().optional().describe('Home address city. Example: "Denver"'),
    home_state: z.string().optional().describe('Home address state. Example: "Colorado"'),
    home_country: z.string().optional().describe('Home address country. Example: "United States"'),
    home_postal_code: z.string().optional().describe('Home address postal code. Example: "11001"'),
    facebook_url: z.string().optional().describe('URL to person\'s Facebook profile. Example: "https://www.facebook.com/james.smith"'),
    linked_in_url: z.string().optional().describe('URL to person\'s LinkedIn profile. Example: "https://www.linkedin.com/in/james-smith-101"'),
    twitter: z.string().optional().describe('Person\'s Twitter username. Example: "james.smith"'),
    instant_message: z.string().optional().describe('Person\'s IM username. Example: "james_smith_20"'),
    relationship: z.string().optional().describe('The relationship of the person to the company. Example: "Owner"'),
    is_key_contact: z.boolean().optional().describe('Whether or not this person is a key contact for the company. Example: true'),
    unsubscribed: z.boolean().optional().describe('Whether or not the person has unsubscribed to newsletters. Example: false'),
    bounced: z.boolean().optional().describe('Whether or not the person has had emails sent to them bounce. Example: false'),
    shared_user_ids: z.array(z.number()).optional(),
    custom_fields: z.record(z.string(), z.unknown()).optional()
});

const ProviderPersonSchema = z.object({
    id: z.number(),
    first_name: z.string().nullable().optional(),
    last_name: z.string().nullable().optional(),
    full_name: z.string().nullable().optional(),
    email: z.string().nullable().optional(),
    email2: z.string().nullable().optional(),
    home_email: z.string().nullable().optional(),
    phone: z.string().nullable().optional(),
    home_phone: z.string().nullable().optional(),
    mobile: z.string().nullable().optional(),
    position: z.string().nullable().optional(),
    summary: z.string().nullable().optional(),
    website: z.string().nullable().optional(),
    company_id: z.number().nullable().optional(),
    company_name: z.string().nullable().optional(),
    user_id: z.number().nullable().optional(),
    lead_status_id: z.number().nullable().optional(),
    lead_source_id: z.number().nullable().optional(),
    image_thumb_url: z.string().nullable().optional(),
    predefined_contacts_tag_ids: z.array(z.number()).nullable().optional(),
    work_address_1: z.string().nullable().optional(),
    work_address_2: z.string().nullable().optional(),
    work_city: z.string().nullable().optional(),
    work_state: z.string().nullable().optional(),
    work_country: z.string().nullable().optional(),
    work_postal_code: z.string().nullable().optional(),
    home_address_1: z.string().nullable().optional(),
    home_address_2: z.string().nullable().optional(),
    home_city: z.string().nullable().optional(),
    home_state: z.string().nullable().optional(),
    home_country: z.string().nullable().optional(),
    home_postal_code: z.string().nullable().optional(),
    facebook_url: z.string().nullable().optional(),
    linked_in_url: z.string().nullable().optional(),
    twitter: z.string().nullable().optional(),
    instant_message: z.string().nullable().optional(),
    relationship: z.string().nullable().optional(),
    is_key_contact: z.boolean().nullable().optional(),
    unsubscribed: z.boolean().nullable().optional(),
    bounced: z.boolean().nullable().optional(),
    shared_user_ids: z.array(z.number()).nullable().optional(),
    custom_fields: z.record(z.string(), z.unknown()).nullable().optional(),
    created_at: z.string().nullable().optional(),
    updated_at: z.string().nullable().optional()
});

const OutputSchema = z.object({
    id: z.number(),
    first_name: z.string().optional(),
    last_name: z.string().optional(),
    full_name: z.string().optional(),
    email: z.string().optional(),
    email2: z.string().optional(),
    home_email: z.string().optional(),
    phone: z.string().optional(),
    home_phone: z.string().optional(),
    mobile: z.string().optional(),
    position: z.string().optional(),
    summary: z.string().optional(),
    website: z.string().optional(),
    company_id: z.number().optional(),
    company_name: z.string().optional(),
    user_id: z.number().optional(),
    lead_status_id: z.number().optional(),
    lead_source_id: z.number().optional(),
    image_thumb_url: z.string().optional(),
    predefined_contacts_tag_ids: z.array(z.number()).optional(),
    work_address_1: z.string().optional(),
    work_address_2: z.string().optional(),
    work_city: z.string().optional(),
    work_state: z.string().optional(),
    work_country: z.string().optional(),
    work_postal_code: z.string().optional(),
    home_address_1: z.string().optional(),
    home_address_2: z.string().optional(),
    home_city: z.string().optional(),
    home_state: z.string().optional(),
    home_country: z.string().optional(),
    home_postal_code: z.string().optional(),
    facebook_url: z.string().optional(),
    linked_in_url: z.string().optional(),
    twitter: z.string().optional(),
    instant_message: z.string().optional(),
    relationship: z.string().optional(),
    is_key_contact: z.boolean().optional(),
    unsubscribed: z.boolean().optional(),
    bounced: z.boolean().optional(),
    shared_user_ids: z.array(z.number()).optional(),
    custom_fields: z.record(z.string(), z.unknown()).optional(),
    created_at: z.string().optional(),
    updated_at: z.string().optional()
});

const action = createAction({
    description: 'Create a new person (contact)',
    version: '1.0.0',
    input: InputSchema,
    output: OutputSchema,

    exec: async (nango, input): Promise<z.infer<typeof OutputSchema>> => {
        // https://app.pipelinecrm.com/api/docs/introduction
        const response = await nango.post({
            endpoint: 'api/v3/people.json',
            data: {
                person: {
                    ...(input.first_name !== undefined && { first_name: input.first_name }),
                    ...(input.last_name !== undefined && { last_name: input.last_name }),
                    ...(input.full_name !== undefined && { full_name: input.full_name }),
                    ...(input.email !== undefined && { email: input.email }),
                    ...(input.email2 !== undefined && { email2: input.email2 }),
                    ...(input.home_email !== undefined && { home_email: input.home_email }),
                    ...(input.phone !== undefined && { phone: input.phone }),
                    ...(input.home_phone !== undefined && { home_phone: input.home_phone }),
                    ...(input.mobile !== undefined && { mobile: input.mobile }),
                    ...(input.position !== undefined && { position: input.position }),
                    ...(input.summary !== undefined && { summary: input.summary }),
                    ...(input.website !== undefined && { website: input.website }),
                    ...(input.company_id !== undefined && { company_id: input.company_id }),
                    ...(input.company_name !== undefined && { company_name: input.company_name }),
                    ...(input.user_id !== undefined && { user_id: input.user_id }),
                    ...(input.lead_status_id !== undefined && { lead_status_id: input.lead_status_id }),
                    ...(input.lead_source_id !== undefined && { lead_source_id: input.lead_source_id }),
                    ...(input.image_thumb_url !== undefined && { image_thumb_url: input.image_thumb_url }),
                    ...(input.predefined_contacts_tag_ids !== undefined && { predefined_contacts_tag_ids: input.predefined_contacts_tag_ids }),
                    ...(input.work_address_1 !== undefined && { work_address_1: input.work_address_1 }),
                    ...(input.work_address_2 !== undefined && { work_address_2: input.work_address_2 }),
                    ...(input.work_city !== undefined && { work_city: input.work_city }),
                    ...(input.work_state !== undefined && { work_state: input.work_state }),
                    ...(input.work_country !== undefined && { work_country: input.work_country }),
                    ...(input.work_postal_code !== undefined && { work_postal_code: input.work_postal_code }),
                    ...(input.home_address_1 !== undefined && { home_address_1: input.home_address_1 }),
                    ...(input.home_address_2 !== undefined && { home_address_2: input.home_address_2 }),
                    ...(input.home_city !== undefined && { home_city: input.home_city }),
                    ...(input.home_state !== undefined && { home_state: input.home_state }),
                    ...(input.home_country !== undefined && { home_country: input.home_country }),
                    ...(input.home_postal_code !== undefined && { home_postal_code: input.home_postal_code }),
                    ...(input.facebook_url !== undefined && { facebook_url: input.facebook_url }),
                    ...(input.linked_in_url !== undefined && { linked_in_url: input.linked_in_url }),
                    ...(input.twitter !== undefined && { twitter: input.twitter }),
                    ...(input.instant_message !== undefined && { instant_message: input.instant_message }),
                    ...(input.relationship !== undefined && { relationship: input.relationship }),
                    ...(input.is_key_contact !== undefined && { is_key_contact: input.is_key_contact }),
                    ...(input.unsubscribed !== undefined && { unsubscribed: input.unsubscribed }),
                    ...(input.bounced !== undefined && { bounced: input.bounced }),
                    ...(input.shared_user_ids !== undefined && { shared_user_ids: input.shared_user_ids }),
                    ...(input.custom_fields !== undefined && { custom_fields: input.custom_fields })
                }
            },
            retries: 10
        });

        const providerPerson = ProviderPersonSchema.parse(response.data);

        return {
            id: providerPerson.id,
            ...(providerPerson.first_name != null && { first_name: providerPerson.first_name }),
            ...(providerPerson.last_name != null && { last_name: providerPerson.last_name }),
            ...(providerPerson.full_name != null && { full_name: providerPerson.full_name }),
            ...(providerPerson.email != null && { email: providerPerson.email }),
            ...(providerPerson.email2 != null && { email2: providerPerson.email2 }),
            ...(providerPerson.home_email != null && { home_email: providerPerson.home_email }),
            ...(providerPerson.phone != null && { phone: providerPerson.phone }),
            ...(providerPerson.home_phone != null && { home_phone: providerPerson.home_phone }),
            ...(providerPerson.mobile != null && { mobile: providerPerson.mobile }),
            ...(providerPerson.position != null && { position: providerPerson.position }),
            ...(providerPerson.summary != null && { summary: providerPerson.summary }),
            ...(providerPerson.website != null && { website: providerPerson.website }),
            ...(providerPerson.company_id != null && { company_id: providerPerson.company_id }),
            ...(providerPerson.company_name != null && { company_name: providerPerson.company_name }),
            ...(providerPerson.user_id != null && { user_id: providerPerson.user_id }),
            ...(providerPerson.lead_status_id != null && { lead_status_id: providerPerson.lead_status_id }),
            ...(providerPerson.lead_source_id != null && { lead_source_id: providerPerson.lead_source_id }),
            ...(providerPerson.image_thumb_url != null && { image_thumb_url: providerPerson.image_thumb_url }),
            ...(providerPerson.predefined_contacts_tag_ids != null && { predefined_contacts_tag_ids: providerPerson.predefined_contacts_tag_ids }),
            ...(providerPerson.work_address_1 != null && { work_address_1: providerPerson.work_address_1 }),
            ...(providerPerson.work_address_2 != null && { work_address_2: providerPerson.work_address_2 }),
            ...(providerPerson.work_city != null && { work_city: providerPerson.work_city }),
            ...(providerPerson.work_state != null && { work_state: providerPerson.work_state }),
            ...(providerPerson.work_country != null && { work_country: providerPerson.work_country }),
            ...(providerPerson.work_postal_code != null && { work_postal_code: providerPerson.work_postal_code }),
            ...(providerPerson.home_address_1 != null && { home_address_1: providerPerson.home_address_1 }),
            ...(providerPerson.home_address_2 != null && { home_address_2: providerPerson.home_address_2 }),
            ...(providerPerson.home_city != null && { home_city: providerPerson.home_city }),
            ...(providerPerson.home_state != null && { home_state: providerPerson.home_state }),
            ...(providerPerson.home_country != null && { home_country: providerPerson.home_country }),
            ...(providerPerson.home_postal_code != null && { home_postal_code: providerPerson.home_postal_code }),
            ...(providerPerson.facebook_url != null && { facebook_url: providerPerson.facebook_url }),
            ...(providerPerson.linked_in_url != null && { linked_in_url: providerPerson.linked_in_url }),
            ...(providerPerson.twitter != null && { twitter: providerPerson.twitter }),
            ...(providerPerson.instant_message != null && { instant_message: providerPerson.instant_message }),
            ...(providerPerson.relationship != null && { relationship: providerPerson.relationship }),
            ...(providerPerson.is_key_contact != null && { is_key_contact: providerPerson.is_key_contact }),
            ...(providerPerson.unsubscribed != null && { unsubscribed: providerPerson.unsubscribed }),
            ...(providerPerson.bounced != null && { bounced: providerPerson.bounced }),
            ...(providerPerson.shared_user_ids != null && { shared_user_ids: providerPerson.shared_user_ids }),
            ...(providerPerson.custom_fields != null && { custom_fields: providerPerson.custom_fields }),
            ...(providerPerson.created_at != null && { created_at: providerPerson.created_at }),
            ...(providerPerson.updated_at != null && { updated_at: providerPerson.updated_at })
        };
    }
});

export type NangoActionLocal = Parameters<(typeof action)['exec']>[0];
export default action;
