// ---------------------------
// This file was generated by Nango (v0.58.3)
// You can version this file
// ---------------------------

export interface CancellationDetails {
    comment: string | null;
    feedback: string | null;
    reason: string | null;
}

export interface Issuer {
    type: string;
}

export interface InvoiceSettings {
    issuer: Issuer;
    account_tax_ids: null | string | string[];
}

export interface Plan {
    id: string;
    object: string;
    active: boolean;
    aggregate_usage: any;
    amount: number;
    amount_decimal: string;
    billing_scheme: string;
    created: number;
    currency: string;
    discounts: any;
    interval: string;
    interval_count: number;
    livemode: boolean;
    nickname: any;
    product: string;
    tiers_mode: any;
    transform_usage: any;
    trial_period_days: any;
    usage_type: string;
}

export interface Recurring {
    aggregate_usage: any;
    interval: string;
    interval_count: number;
    trial_period_days: any;
    usage_type: string;
}

export interface Price {
    id: string;
    object: string;
    active: boolean;
    billing_scheme: string;
    created: number;
    currency: string;
    custom_unit_amount: any;
    livemode: boolean;
    lookup_key: any;
    nickname: any;
    product: string;
    recurring: Recurring;
    tax_behavior: string;
    tiers_mode: any;
    transform_quantity: any;
    type: string;
    unit_amount: number;
    unit_amount_decimal: string;
}

export interface Item {
    id: string;
    billing_thresholds: string | null;
    created: number;
    plan: Plan;
    price: Price;
    quantity: number;
    subscription: string;
    tax_rates: string[];
}

export interface PaymentSettings {
    payment_method_options: string | null;
    payment_method_types: string | null;
    save_default_payment_method: string;
}

export interface EndBehavior {
    missing_payment_method: string;
}

export interface TrialSettings {
    end_behavior: EndBehavior;
}

export interface Subscription {
    id: string;
    automatic_tax: { enabled: boolean; liability: boolean | string | null; disabled_reason: string | null };
    billing_cycle_anchor: number;
    billing_thresholds: string | null;
    cancel_at: string | null;
    cancel_at_period_end: boolean;
    canceled_at: string | null;
    cancellation_details: CancellationDetails;
    collection_method: string;
    created: number;
    currency: string;
    current_period_end: number;
    current_period_start: number;
    customer: string;
    days_until_due: number | null;
    default_payment_method: string | null;
    description: string | null;
    discount: string | null;
    discounts: string[] | null;
    ended_at: string | null;
    invoice_settings: InvoiceSettings;
    items: Item[];
    latest_invoice: string;
    livemode: boolean;
    next_pending_invoice_item_invoice: string | null;
    on_behalf_of: string | null;
    pause_collection: string | null;
    payment_settings: PaymentSettings;
    pending_invoice_item_interval: string | null;
    pending_setup_intent: string | null;
    schedule: string | null;
    start_date: number;
    status: string;
    transfer_data: string | null;
    trial_end: string | null;
    trial_settings: TrialSettings;
    trial_start: string | null;
}
