import { z } from 'zod';
import { ProxyConfiguration, createAction } from 'nango';

const InputSchema = z
    .object({
        name: z.string().describe('The name of the automation rule.'),
        code: z.string().describe('The logic of the rule as JavaScript-like code. Example: if (eq(ticket.subject, "x")) { Action("addTags", {tags: "y"}) }'),
        description: z.string().nullable().optional().describe('The description of the rule.'),
        priority: z.number().optional().describe('Order of execution. Rules with higher priorities are executed first.'),
        event_types: z.string().optional().describe('Comma-separated events that trigger the rule, e.g. "ticket-created,ticket-updated".'),
        deactivated_datetime: z.string().nullable().optional().describe('ISO 8601 datetime when the rule was deactivated. Pass null for an active rule.')
    })
    .describe('Input for creating a Gorgias automation rule.');

const ProviderRuleSchema = z.object({
    id: z.number(),
    code: z.string(),
    code_ast: z.record(z.string(), z.unknown()),
    created_datetime: z.string().optional(),
    deactivated_datetime: z.string().nullable().optional(),
    description: z.string().nullable().optional(),
    event_types: z.string().nullable().optional(),
    name: z.string(),
    priority: z.number().nullable().optional(),
    updated_datetime: z.string().optional(),
    uri: z.string().optional()
});

const OutputSchema = z
    .object({
        id: z.number().describe('The unique ID of the created rule.'),
        name: z.string().describe('The name of the automation rule.'),
        code: z.string().describe('The logic of the rule as JavaScript-like code.'),
        code_ast: z.record(z.string(), z.unknown()).describe('The parsed AST representation of the rule code, generated by the server.'),
        created_datetime: z.string().optional().describe('ISO 8601 datetime when the rule was created.'),
        deactivated_datetime: z.string().nullable().optional().describe('ISO 8601 datetime when the rule was deactivated. Null when the rule is active.'),
        description: z.string().nullable().optional().describe('The description of the rule.'),
        event_types: z.string().nullable().optional().describe('Comma-separated events that trigger the rule.'),
        priority: z.number().nullable().optional().describe('Order of execution. Rules with higher priorities are executed first.'),
        updated_datetime: z.string().optional().describe('ISO 8601 datetime when the rule was last updated.'),
        uri: z.string().optional().describe('API URI of the rule resource.')
    })
    .describe('The created Gorgias automation rule.');

/**
 * @tags: [write]
 * @tagReason: Creates a new automation rule on the Gorgias provider.
 * @pitfalls: The `code` field uses a restricted Gorgias DSL with helpers like `eq()` and `Action()`, not arbitrary JavaScript; the server auto-assigns a `priority` value when it is omitted.
 */
const action = createAction({
    description: 'Create an automation rule with JavaScript-like condition/action code.',
    version: '1.0.0',
    input: InputSchema,
    output: OutputSchema,
    scopes: ['rules:write'],

    exec: async (nango, input): Promise<z.infer<typeof OutputSchema>> => {
        const config: ProxyConfiguration = {
            // https://developers.gorgias.com/reference/create-rule
            endpoint: '/api/rules',
            data: {
                name: input.name,
                code: input.code,
                ...(input.description !== undefined && { description: input.description }),
                ...(input.priority !== undefined && { priority: input.priority }),
                ...(input.event_types !== undefined && { event_types: input.event_types }),
                ...(input.deactivated_datetime !== undefined && { deactivated_datetime: input.deactivated_datetime })
            },
            retries: 3
        };

        const response = await nango.post(config);

        const rule = ProviderRuleSchema.parse(response.data);

        return {
            id: rule.id,
            name: rule.name,
            code: rule.code,
            code_ast: rule.code_ast,
            ...(rule.created_datetime !== undefined && { created_datetime: rule.created_datetime }),
            ...(rule.deactivated_datetime !== undefined && { deactivated_datetime: rule.deactivated_datetime }),
            ...(rule.description !== undefined && { description: rule.description }),
            ...(rule.event_types !== undefined && { event_types: rule.event_types }),
            ...(rule.priority !== undefined && { priority: rule.priority }),
            ...(rule.updated_datetime !== undefined && { updated_datetime: rule.updated_datetime }),
            ...(rule.uri !== undefined && { uri: rule.uri })
        };
    }
});

export type NangoActionLocal = Parameters<(typeof action)['exec']>[0];
export default action;
