// ---------------------------
// This file was generated by Nango (v0.62.0)
// You can version this file
// ---------------------------

export interface WildixPbxColleague {
    id: string;
    name: string;
    extension: string;
    email: string;
    mobilePhone: string;
    licenseType: string;
    language: string;
}
