// ---------------------------
// This file was generated by Nango (v0.56.1)
// You can version this file
// ---------------------------

export interface AshbyCandidate {
    id: string;
    createdAt: Date;
    name: string;
    primaryEmailAddress: { value: string; type: string; isPrimary: boolean };
    emailAddresses: string[];
    primaryPhoneNumber: { value: string; type: string; isPrimary: boolean };
    phoneNumbers: string[];
    socialLinks: string[];
    tags: string[];
    position: string;
    company: string;
    school: string;
    applicationIds: string[];
    resumeFileHandle: { id: string; name: string; handle: string };
    fileHandles: string[];
    customFields: string[];
    profileUrl: string;
    source: { id: string; title: string; isArchived: boolean; sourceType: { id: string; title: string; isArchived: boolean } };
    creditedToUser: { id: string; firstName: string; lastName: string; email: string; globalRole: string; isEnabled: boolean; updatedAt: Date };
}

export interface AshbyJob {
    id: string;
    title: string;
    confidential: boolean;
    status: string;
    employmentType: string;
    locationId: string;
    departmentId: string;
    defaultInterviewPlanId: string;
    interviewPlanIds: string[];
    customFields: string[];
    jobPostingIds: string[];
    customRequisitionId: string;
    hiringTeam: string[];
    updatedAt: Date;
    location: {
        id: string;
        name: string;
        isArchived: boolean;
        address: { postalAddress: { addressCountry: string; addressRegion: string; addressLocality: string } };
        isRemote: boolean;
    };
    openings: string[];
}

export interface AshbyCreateApplicationResponse {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    status: string;
    customFields: string[];
    candidate: {
        id: string;
        name: string;
        primaryEmailAddress: { value: string; type: string; isPrimary: boolean };
        primaryPhoneNumber: { value: string; type: string; isPrimary: boolean };
    };
    currentInterviewStage: { id: string; title: string; type: string; orderInInterviewPlan: number; interviewPlanId: string };
    source: { id: string; title: string; isArchived: boolean; sourceType: { id: string; title: string; isArchived: boolean } };
    archiveReason: { id: string; text: string; reasonType: string; isArchived: boolean };
    job: { id: string; title: string; locationId: string; departmentId: string };
    creditedToUser: { id: string; firstName: string; lastName: string; email: string; globalRole: string; isEnabled: boolean; updatedAt: Date };
    hiringTeam: string[];
    appliedViaJobPostingId: string;
}

export interface InterviewStageListResponse {
    id: string;
    title: string;
    type: string;
    orderInInterviewPlan: number;
    interviewStageGroupId?: string;
    interviewPlanId: string;
}

export interface StagesResponse {
    stages: InterviewStageListResponse[];
}

export interface InterviewStageList {
    interviewPlanId: string;
}

export interface AshbyCreateNoteResponse {
    id: string;
    createdAt: Date;
    content: string;
    author: { id: string; firstName: string; lastName: string; email: string };
}

export interface AshbyCreateCandidateInput {
    candidateId: string;
    jobId: string;
    interviewPlanId: string | undefined;
    interviewStageId: string | undefined;
    sourceId: string | undefined;
    creditedToUserId: string | undefined;
}

export interface NoteObject {
    value: string;
    type: string;
}

export interface AshbyCreateNoteInput {
    candidateId: string;
    note: string | NoteObject;
    sendNotifications: boolean | undefined;
}

export interface ChangeStage {
    applicationId: string;
    interviewStageId: string;
    archiveReasonId?: string;
}

export interface ChangeSource {
    applicationId: string;
    sourceId: string;
}

export interface CreateCandidate {
    name: string;
    email?: string;
    phoneNumber?: string;
    linkedInUrl?: string;
    githubUrl?: string;
    website?: string;
    alternateEmailAddresses?: string[];
    sourceId?: string;
    creditedToUserId?: string;
    location?: { city?: string; region?: string; country?: string };
    createdAt?: Date;
}

export interface EmailAddressObject {
    value: string;
    type: string;
    isPrimary: boolean;
}

export interface PrimaryNumberObject {
    value: string;
    type: string;
    isPrimary: boolean;
}

export interface PhoneNumbersObject {
    value: string;
    type: string;
    isPrimary: boolean;
}

export interface SocialLinksObject {
    type: string;
    url: string;
}

export interface TagsObject {
    id: string;
    title: string;
    isArchived: boolean;
}

export interface FileaHandlesObject {
    id: string;
    name: string;
    handle: string;
}

export interface LocationComponentsObject {
    type: string;
    name: string;
}

export interface AshbyCreateCandidateResponse {
    id: string;
    createdAt?: Date;
    updatedAt?: Date;
    name: string;
    primaryEmailAddress?: { value: string; type: string; isPrimary: boolean };
    emailAddresses?: EmailAddressObject[];
    primaryPhoneNumber?: PrimaryNumberObject[];
    phoneNumbers: PhoneNumbersObject[];
    socialLinks: SocialLinksObject[];
    tags: TagsObject[];
    position?: string | null;
    company?: string | null;
    applicationIds: string[];
    resumeFileHandle?: { id: string; name: string; handle: string };
    fileHandles: FileaHandlesObject[];
    customFields?: Record<string, any>[];
    profileUrl: string;
    source?: { id: string; title: string; isArchived: boolean; sourceType?: { id: string; title: string; isArchived: string } };
    creditedToUser?: { id: string; firstName: string; lastName: string; email: string; globalRole: string; isEnabled: boolean; updatedAt: Date };
    timezone?: string;
    primaryLocation?: { id: string; locationSummary: string; locationComponents: LocationComponentsObject[] };
}

export interface HiringTeamObject {
    email: string;
    firstName: string;
    lastName: string;
    role: string;
    userId: string;
}

export interface AshByApplicationSuccessObject {
    id: string;
    createdAt: Date;
    updatedAt: Date;
    status: string;
    customFields: Record<string, any>[];
    candidate: { id: string; name: string; primaryEmailAddress?: { value: string; type: any; isPrimary: string }; primaryPhoneNumber?: Record<string, any> };
    currentInterviewStage: { id: string; title: string; type: string; orderInInterviewPlan: number; interviewStageGroupId?: string; interviewPlanId: string };
    source?: { id: string; title: string; isArchived: boolean; sourceType: { id: string; title: string; isArchived: boolean } };
    archiveReason?: { id: string; text: string; reasonType: string; isArchived: boolean };
    archivedAt?: Date;
    job: { id: string; title: string; locationId: string; departmentId: string };
    creditedToUser?: { id: string; firstName: string; lastName: string; email?: string; globalRole: string; isEnabled: boolean; updatedAt: Date };
    hiringTeam: HiringTeamObject[];
    appliedViaJobPostingId?: string;
}

export interface AshbyResponse {
    success: boolean;
    errors?: string[];
    results?: AshByApplicationSuccessObject | AshbyCreateCandidateResponse | InterviewStageListResponse;
    moreDataAvailable?: boolean;
}

export interface UpdateApplication {
    applicationId: string;
    sourceId?: string;
    creditedToUserId?: string;
    createdAt?: Date;
    sendNotifications?: boolean;
}

export interface ApplicationHistoryObject {
    stageId: string;
    stageNumber: number;
    enteredStageAt: Date;
    applicationHistoryId?: string;
    archiveReasonId?: string;
}

export interface UpdateAshbyApplication {
    applicationId: string;
    sourceId?: string;
    interviewStageId?: string;
    archiveReasonId?: string;
    applicationHistory?: ApplicationHistoryObject[];
}

export interface UpdateHistory {
    applicationId: string;
    applicationHistory: ApplicationHistoryObject[];
}

/** @deprecated It is recommended to use a Model */
export type Anonymous_ashby_action_applicationupdate_input = ChangeSource | ChangeStage | UpdateHistory;
