export interface SyncMetadata_ashby_candidates {
  candidatelastsyncToken?: string | undefined;
};

export interface AshbyCandidate {
  id: string;
  createdAt: Date;
  name: string;
  primaryEmailAddress: {  value: string;
  type: string;
  isPrimary: boolean;};
  emailAddresses: string[];
  primaryPhoneNumber: {  value: string;
  type: string;
  isPrimary: boolean;};
  phoneNumbers: string[];
  socialLinks: string[];
  tags: string[];
  position: string;
  company: string;
  school: string;
  applicationIds: string[];
  resumeFileHandle: {  id: string;
  name: string;
  handle: string;};
  fileHandles: string[];
  customFields: string[];
  profileUrl: string;
  source: {  id: string;
  title: string;
  isArchived: boolean;
  sourceType: {  id: string;
  title: string;
  isArchived: boolean;};};
  creditedToUser: {  id: string;
  firstName: string;
  lastName: string;
  email: string;
  globalRole: string;
  isEnabled: boolean;
  updatedAt: Date;};
};

export interface SyncMetadata_ashby_jobs {
  jobslastsyncToken?: string | undefined;
};

export interface AshbyJob {
  id: string;
  title: string;
  confidential: boolean;
  status: string;
  employmentType: string;
  locationId: string;
  departmentId: string;
  defaultInterviewPlanId: string;
  interviewPlanIds: string[];
  customFields: string[];
  jobPostingIds: string[];
  customRequisitionId: string;
  hiringTeam: string[];
  updatedAt: Date;
  location: {  id: string;
  name: string;
  isArchived: boolean;
  address: {  postalAddress: {  addressCountry: string;
  addressRegion: string;
  addressLocality: string;};};
  isRemote: boolean;};
  openings: string[];
};

export interface ActionInput_ashby_applicationchangesource {
  applicationId: string;
  sourceId: string;
};

export interface ActionOutput_ashby_applicationchangesource {
  success: boolean;
  errors: string[];
  results?: {  id: string;
  createdAt: Date;
  updatedAt: Date;
  status: string;
  customFields: ({})[];
  candidate: {  id: string;
  name: string;
  primaryEmailAddress?: {  value: string;
  type?: any | undefined;
  isPrimary: string;};
  primaryPhoneNumber?: {} | undefined;};
  currentInterviewStage: {  id: string;
  title: string;
  type: string;
  orderInInterviewPlan: number;
  interviewStageGroupId?: string | undefined;
  interviewPlanId: string;};
  source?: {  id: string;
  title: string;
  isArchived: boolean;
  sourceType: {  id: string;
  title: string;
  isArchived: boolean;};} | undefined;
  archiveReason?: {  id: string;
  text: string;
  reasonType: string;
  isArchived: boolean;} | undefined;
  archivedAt?: Date | undefined;
  job: {  id: string;
  title: string;
  locationId: string;
  departmentId: string;};
  creditedToUser?: {  id: string;
  firstName: string;
  lastName: string;
  email?: string | undefined;
  globalRole: string;
  isEnabled: boolean;
  updatedAt: Date;};
  hiringTeam: ({  email: string;
  firstName: string;
  lastName: string;
  role: string;
  userId: string;})[];
  appliedViaJobPostingId?: string | undefined;} | {  id: string;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
  name: string;
  primaryEmailAddress?: {  value: string;
  type: string;
  isPrimary: boolean;} | undefined;
  emailAddresses: ({  value: string;
  type: string;
  isPrimary: boolean;})[];
  primaryPhoneNumber: ({  value: string;
  type: string;
  isPrimary: boolean;})[];
  phoneNumbers: ({  value: string;
  type: string;
  isPrimary: boolean;})[];
  socialLinks: ({  type: string;
  url: string;})[];
  tags: ({  id: string;
  title: string;
  isArchived: boolean;})[];
  position?: string | null | undefined;
  company?: string | null | undefined;
  applicationIds: string[];
  resumeFileHandle?: {  id: string;
  name: string;
  handle: string;} | undefined;
  fileHandles: ({  id: string;
  name: string;
  handle: string;})[];
  customFields: ({})[];
  profileUrl: string;
  source?: {  id: string;
  title: string;
  isArchived: boolean;
  sourceType?: {  id: string;
  title: string;
  isArchived: string;} | undefined;};
  creditedToUser?: {  id: string;
  firstName: string;
  lastName: string;
  email: string;
  globalRole: string;
  isEnabled: boolean;
  updatedAt: Date;} | undefined;
  timezone?: string | undefined;
  primaryLocation?: {  id: string;
  locationSummary: string;
  locationComponents: ({  type: string;
  name: string;})[];} | undefined;} | {  id: string;
  title: string;
  type: string;
  orderInInterviewPlan: number;
  interviewStageGroupId?: string | undefined;
  interviewPlanId: string;};
  moreDataAvailable?: boolean | undefined;
};

export interface ActionInput_ashby_applicationchangestage {
  applicationId: string;
  interviewStageId: string;
  archiveReasonId?: string | undefined;
};

export interface ActionOutput_ashby_applicationchangestage {
  success: boolean;
  errors: string[];
  results?: {  id: string;
  createdAt: Date;
  updatedAt: Date;
  status: string;
  customFields: ({})[];
  candidate: {  id: string;
  name: string;
  primaryEmailAddress?: {  value: string;
  type?: any | undefined;
  isPrimary: string;};
  primaryPhoneNumber?: {} | undefined;};
  currentInterviewStage: {  id: string;
  title: string;
  type: string;
  orderInInterviewPlan: number;
  interviewStageGroupId?: string | undefined;
  interviewPlanId: string;};
  source?: {  id: string;
  title: string;
  isArchived: boolean;
  sourceType: {  id: string;
  title: string;
  isArchived: boolean;};} | undefined;
  archiveReason?: {  id: string;
  text: string;
  reasonType: string;
  isArchived: boolean;} | undefined;
  archivedAt?: Date | undefined;
  job: {  id: string;
  title: string;
  locationId: string;
  departmentId: string;};
  creditedToUser?: {  id: string;
  firstName: string;
  lastName: string;
  email?: string | undefined;
  globalRole: string;
  isEnabled: boolean;
  updatedAt: Date;};
  hiringTeam: ({  email: string;
  firstName: string;
  lastName: string;
  role: string;
  userId: string;})[];
  appliedViaJobPostingId?: string | undefined;} | {  id: string;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
  name: string;
  primaryEmailAddress?: {  value: string;
  type: string;
  isPrimary: boolean;} | undefined;
  emailAddresses: ({  value: string;
  type: string;
  isPrimary: boolean;})[];
  primaryPhoneNumber: ({  value: string;
  type: string;
  isPrimary: boolean;})[];
  phoneNumbers: ({  value: string;
  type: string;
  isPrimary: boolean;})[];
  socialLinks: ({  type: string;
  url: string;})[];
  tags: ({  id: string;
  title: string;
  isArchived: boolean;})[];
  position?: string | null | undefined;
  company?: string | null | undefined;
  applicationIds: string[];
  resumeFileHandle?: {  id: string;
  name: string;
  handle: string;} | undefined;
  fileHandles: ({  id: string;
  name: string;
  handle: string;})[];
  customFields: ({})[];
  profileUrl: string;
  source?: {  id: string;
  title: string;
  isArchived: boolean;
  sourceType?: {  id: string;
  title: string;
  isArchived: string;} | undefined;};
  creditedToUser?: {  id: string;
  firstName: string;
  lastName: string;
  email: string;
  globalRole: string;
  isEnabled: boolean;
  updatedAt: Date;} | undefined;
  timezone?: string | undefined;
  primaryLocation?: {  id: string;
  locationSummary: string;
  locationComponents: ({  type: string;
  name: string;})[];} | undefined;} | {  id: string;
  title: string;
  type: string;
  orderInInterviewPlan: number;
  interviewStageGroupId?: string | undefined;
  interviewPlanId: string;};
  moreDataAvailable?: boolean | undefined;
};

export interface ActionInput_ashby_applicationupdate {
  0: {  applicationId: string;
  sourceId: string;};
  1: {  applicationId: string;
  interviewStageId: string;
  archiveReasonId?: string | undefined;};
  2: {  applicationId: string;
  applicationHistory: ({  stageId: string;
  stageNumber: number;
  enteredStageAt: Date;
  applicationHistoryId?: string | undefined;
  archiveReasonId?: string | undefined;})[];};
};

export interface ActionOutput_ashby_applicationupdate {
  success: boolean;
  errors: string[];
  results?: {  id: string;
  createdAt: Date;
  updatedAt: Date;
  status: string;
  customFields: ({})[];
  candidate: {  id: string;
  name: string;
  primaryEmailAddress?: {  value: string;
  type?: any | undefined;
  isPrimary: string;};
  primaryPhoneNumber?: {} | undefined;};
  currentInterviewStage: {  id: string;
  title: string;
  type: string;
  orderInInterviewPlan: number;
  interviewStageGroupId?: string | undefined;
  interviewPlanId: string;};
  source?: {  id: string;
  title: string;
  isArchived: boolean;
  sourceType: {  id: string;
  title: string;
  isArchived: boolean;};} | undefined;
  archiveReason?: {  id: string;
  text: string;
  reasonType: string;
  isArchived: boolean;} | undefined;
  archivedAt?: Date | undefined;
  job: {  id: string;
  title: string;
  locationId: string;
  departmentId: string;};
  creditedToUser?: {  id: string;
  firstName: string;
  lastName: string;
  email?: string | undefined;
  globalRole: string;
  isEnabled: boolean;
  updatedAt: Date;};
  hiringTeam: ({  email: string;
  firstName: string;
  lastName: string;
  role: string;
  userId: string;})[];
  appliedViaJobPostingId?: string | undefined;} | {  id: string;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
  name: string;
  primaryEmailAddress?: {  value: string;
  type: string;
  isPrimary: boolean;} | undefined;
  emailAddresses: ({  value: string;
  type: string;
  isPrimary: boolean;})[];
  primaryPhoneNumber: ({  value: string;
  type: string;
  isPrimary: boolean;})[];
  phoneNumbers: ({  value: string;
  type: string;
  isPrimary: boolean;})[];
  socialLinks: ({  type: string;
  url: string;})[];
  tags: ({  id: string;
  title: string;
  isArchived: boolean;})[];
  position?: string | null | undefined;
  company?: string | null | undefined;
  applicationIds: string[];
  resumeFileHandle?: {  id: string;
  name: string;
  handle: string;} | undefined;
  fileHandles: ({  id: string;
  name: string;
  handle: string;})[];
  customFields: ({})[];
  profileUrl: string;
  source?: {  id: string;
  title: string;
  isArchived: boolean;
  sourceType?: {  id: string;
  title: string;
  isArchived: string;} | undefined;};
  creditedToUser?: {  id: string;
  firstName: string;
  lastName: string;
  email: string;
  globalRole: string;
  isEnabled: boolean;
  updatedAt: Date;} | undefined;
  timezone?: string | undefined;
  primaryLocation?: {  id: string;
  locationSummary: string;
  locationComponents: ({  type: string;
  name: string;})[];} | undefined;} | {  id: string;
  title: string;
  type: string;
  orderInInterviewPlan: number;
  interviewStageGroupId?: string | undefined;
  interviewPlanId: string;};
  moreDataAvailable?: boolean | undefined;
};

export interface ActionInput_ashby_applicationupdatehistory {
  applicationId: string;
  applicationHistory: ({  stageId: string;
  stageNumber: number;
  enteredStageAt: Date;
  applicationHistoryId?: string | undefined;
  archiveReasonId?: string | undefined;})[];
};

export interface ActionOutput_ashby_applicationupdatehistory {
  success: boolean;
  errors: string[];
  results?: {  id: string;
  createdAt: Date;
  updatedAt: Date;
  status: string;
  customFields: ({})[];
  candidate: {  id: string;
  name: string;
  primaryEmailAddress?: {  value: string;
  type?: any | undefined;
  isPrimary: string;};
  primaryPhoneNumber?: {} | undefined;};
  currentInterviewStage: {  id: string;
  title: string;
  type: string;
  orderInInterviewPlan: number;
  interviewStageGroupId?: string | undefined;
  interviewPlanId: string;};
  source?: {  id: string;
  title: string;
  isArchived: boolean;
  sourceType: {  id: string;
  title: string;
  isArchived: boolean;};} | undefined;
  archiveReason?: {  id: string;
  text: string;
  reasonType: string;
  isArchived: boolean;} | undefined;
  archivedAt?: Date | undefined;
  job: {  id: string;
  title: string;
  locationId: string;
  departmentId: string;};
  creditedToUser?: {  id: string;
  firstName: string;
  lastName: string;
  email?: string | undefined;
  globalRole: string;
  isEnabled: boolean;
  updatedAt: Date;};
  hiringTeam: ({  email: string;
  firstName: string;
  lastName: string;
  role: string;
  userId: string;})[];
  appliedViaJobPostingId?: string | undefined;} | {  id: string;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
  name: string;
  primaryEmailAddress?: {  value: string;
  type: string;
  isPrimary: boolean;} | undefined;
  emailAddresses: ({  value: string;
  type: string;
  isPrimary: boolean;})[];
  primaryPhoneNumber: ({  value: string;
  type: string;
  isPrimary: boolean;})[];
  phoneNumbers: ({  value: string;
  type: string;
  isPrimary: boolean;})[];
  socialLinks: ({  type: string;
  url: string;})[];
  tags: ({  id: string;
  title: string;
  isArchived: boolean;})[];
  position?: string | null | undefined;
  company?: string | null | undefined;
  applicationIds: string[];
  resumeFileHandle?: {  id: string;
  name: string;
  handle: string;} | undefined;
  fileHandles: ({  id: string;
  name: string;
  handle: string;})[];
  customFields: ({})[];
  profileUrl: string;
  source?: {  id: string;
  title: string;
  isArchived: boolean;
  sourceType?: {  id: string;
  title: string;
  isArchived: string;} | undefined;};
  creditedToUser?: {  id: string;
  firstName: string;
  lastName: string;
  email: string;
  globalRole: string;
  isEnabled: boolean;
  updatedAt: Date;} | undefined;
  timezone?: string | undefined;
  primaryLocation?: {  id: string;
  locationSummary: string;
  locationComponents: ({  type: string;
  name: string;})[];} | undefined;} | {  id: string;
  title: string;
  type: string;
  orderInInterviewPlan: number;
  interviewStageGroupId?: string | undefined;
  interviewPlanId: string;};
  moreDataAvailable?: boolean | undefined;
};

export interface ActionInput_ashby_createapplication {
  candidateId: string;
  jobId: string;
  interviewPlanId: string;
  interviewStageId: string;
  sourceId: string;
  creditedToUserId: string;
};

export interface ActionOutput_ashby_createapplication {
  id: string;
  createdAt: Date;
  updatedAt: Date;
  status: string;
  customFields: string[];
  candidate: {  id: string;
  name: string;
  primaryEmailAddress: {  value: string;
  type: string;
  isPrimary: boolean;};
  primaryPhoneNumber: {  value: string;
  type: string;
  isPrimary: boolean;};};
  currentInterviewStage: {  id: string;
  title: string;
  type: string;
  orderInInterviewPlan: number;
  interviewPlanId: string;};
  source: {  id: string;
  title: string;
  isArchived: boolean;
  sourceType: {  id: string;
  title: string;
  isArchived: boolean;};};
  archiveReason: {  id: string;
  text: string;
  reasonType: string;
  isArchived: boolean;};
  job: {  id: string;
  title: string;
  locationId: string;
  departmentId: string;};
  creditedToUser: {  id: string;
  firstName: string;
  lastName: string;
  email: string;
  globalRole: string;
  isEnabled: boolean;
  updatedAt: Date;};
  hiringTeam: string[];
  appliedViaJobPostingId: string;
};

export interface ActionInput_ashby_createcandidate {
  name: string;
  email?: string | undefined;
  phoneNumber?: string | undefined;
  linkedInUrl?: string | undefined;
  githubUrl?: string | undefined;
  website?: string | undefined;
  alternateEmailAddresses: string[];
  sourceId?: string | undefined;
  creditedToUserId?: string | undefined;
  location?: {  city?: string | undefined;
  region?: string | undefined;
  country?: string | undefined;};
  createdAt?: Date | undefined;
};

export interface ActionOutput_ashby_createcandidate {
  success: boolean;
  errors: string[];
  results?: {  id: string;
  createdAt: Date;
  updatedAt: Date;
  status: string;
  customFields: ({})[];
  candidate: {  id: string;
  name: string;
  primaryEmailAddress?: {  value: string;
  type?: any | undefined;
  isPrimary: string;};
  primaryPhoneNumber?: {} | undefined;};
  currentInterviewStage: {  id: string;
  title: string;
  type: string;
  orderInInterviewPlan: number;
  interviewStageGroupId?: string | undefined;
  interviewPlanId: string;};
  source?: {  id: string;
  title: string;
  isArchived: boolean;
  sourceType: {  id: string;
  title: string;
  isArchived: boolean;};} | undefined;
  archiveReason?: {  id: string;
  text: string;
  reasonType: string;
  isArchived: boolean;} | undefined;
  archivedAt?: Date | undefined;
  job: {  id: string;
  title: string;
  locationId: string;
  departmentId: string;};
  creditedToUser?: {  id: string;
  firstName: string;
  lastName: string;
  email?: string | undefined;
  globalRole: string;
  isEnabled: boolean;
  updatedAt: Date;};
  hiringTeam: ({  email: string;
  firstName: string;
  lastName: string;
  role: string;
  userId: string;})[];
  appliedViaJobPostingId?: string | undefined;} | {  id: string;
  createdAt?: Date | undefined;
  updatedAt?: Date | undefined;
  name: string;
  primaryEmailAddress?: {  value: string;
  type: string;
  isPrimary: boolean;} | undefined;
  emailAddresses: ({  value: string;
  type: string;
  isPrimary: boolean;})[];
  primaryPhoneNumber: ({  value: string;
  type: string;
  isPrimary: boolean;})[];
  phoneNumbers: ({  value: string;
  type: string;
  isPrimary: boolean;})[];
  socialLinks: ({  type: string;
  url: string;})[];
  tags: ({  id: string;
  title: string;
  isArchived: boolean;})[];
  position?: string | null | undefined;
  company?: string | null | undefined;
  applicationIds: string[];
  resumeFileHandle?: {  id: string;
  name: string;
  handle: string;} | undefined;
  fileHandles: ({  id: string;
  name: string;
  handle: string;})[];
  customFields: ({})[];
  profileUrl: string;
  source?: {  id: string;
  title: string;
  isArchived: boolean;
  sourceType?: {  id: string;
  title: string;
  isArchived: string;} | undefined;};
  creditedToUser?: {  id: string;
  firstName: string;
  lastName: string;
  email: string;
  globalRole: string;
  isEnabled: boolean;
  updatedAt: Date;} | undefined;
  timezone?: string | undefined;
  primaryLocation?: {  id: string;
  locationSummary: string;
  locationComponents: ({  type: string;
  name: string;})[];} | undefined;} | {  id: string;
  title: string;
  type: string;
  orderInInterviewPlan: number;
  interviewStageGroupId?: string | undefined;
  interviewPlanId: string;};
  moreDataAvailable?: boolean | undefined;
};

export interface ActionInput_ashby_createnote {
  candidateId: string;
  note: string | {  value: string;
  type: string;};
  sendNotifications: boolean;
};

export interface ActionOutput_ashby_createnote {
  id: string;
  createdAt: Date;
  content: string;
  author: {  id: string;
  firstName: string;
  lastName: string;
  email: string;};
};

export interface ActionInput_ashby_interviewstage {
  interviewPlanId: string;
};

export interface ActionOutput_ashby_interviewstage {
  stages: ({  id: string;
  title: string;
  type: string;
  orderInInterviewPlan: number;
  interviewStageGroupId?: string | undefined;
  interviewPlanId: string;})[];
};
