// ---------------------------
// This file was generated by Nango (v0.57.3)
// You can version this file
// ---------------------------

export interface ConversationAssignee {
    id: string;
    email: string;
    first_name: string;
    last_name: string;
    is_admin: boolean;
    is_available: boolean;
    is_blocked: boolean;
    custom_fields: Record<string, any>;
}

export interface ConversationRecipient {
    name: string;
    handle: string;
    role: 'from' | 'to' | 'cc' | 'bcc';
}

export interface Conversation {
    id: string;
    subject: string;
    status: 'archived' | 'unassigned' | 'deleted' | 'assigned';
    assignee: ConversationAssignee | null;
    recipient: ConversationRecipient | null;
    tags: {
        id: string;
        name: string;
        description: string | null;
        highlight: string | null;
        is_private: boolean;
        is_visible_in_conversation_lists: boolean;
        created_at: string;
        updated_at: string;
    }[];
    links: { id: string; name: string; type: string; external_url: string; custom_fields: Record<string, any> }[];
    custom_fields: Record<string, any>;
    created_at: string;
    waiting_since: string;
    is_private: boolean;
    scheduled_reminders: { created_at: string; scheduled_at: string; updated_at: string }[];
}

export interface QueryParams {
    limit?: number;
    page_token?: string;
    sort_by?: string;
    sort_order?: 'asc' | 'desc';
}

export interface SingleConversation {
    id: string;
    query?: QueryParams;
}

export interface RecipientsObj {
    _links: { related: { contact: string } };
    name: string;
    handle: string;
    role: 'from' | 'to' | 'cc' | 'bcc';
}

export interface AttachmentObj {
    id: string;
    filename: string;
    url: string;
    content_type: string;
    size: number;
    metadata: { is_inline: boolean; cid: string };
}

export interface AuthorObj {
    _links: { self: string; related: { inboxes: string; conversations: string } };
    id: string;
    email: string;
    username: string;
    first_name: string;
    last_name: string;
    is_admin: boolean;
    is_blocked: boolean;
    custom_fields: Record<string, any>;
}

export interface SignatureObj {
    _links?: { related?: { owner?: string } };
    id?: string;
    name?: string;
    body?: string;
    sender_info?: string;
    is_visible_for_all_teammate_channels?: boolean;
    is_default?: boolean;
    is_private?: boolean;
    channel_ids?: string[];
}

export interface FrontMessages {
    _links: { self: string; related: { conversation: string; message_replied_to?: string; message_seen: string } };
    id: string;
    version?: string | null;
    blurb: string;
    error_type: string | null;
    type:
        | 'call'
        | 'custom'
        | 'email'
        | 'facebook'
        | 'front_chat'
        | 'googleplay'
        | 'intercom'
        | 'internal'
        | 'phone-call'
        | 'sms'
        | 'tweet'
        | 'tweet_dm'
        | 'whatsapp'
        | 'yalo_wha';
    is_draft: boolean;
    is_inbound: boolean;
    draft_mode: string | null;
    created_at: number;
    subject: string;
    author: AuthorObj | null;
    recipients: RecipientsObj[];
    body: string;
    text: string;
    attachments?: AttachmentObj[];
    signature?: SignatureObj | null;
    metadata?: {
        intercom_url?: string;
        duration?: number;
        have_been_answered?: boolean;
        external_id?: string;
        twitter_url?: string;
        is_retweet?: boolean;
        have_been_retweeted?: boolean;
        have_been_favorited?: boolean;
        thread_ref?: string;
        headers?: Record<string, any>;
        chat_visitor_url?: string;
    };
}

export interface FrontMessageOutput {
    messages: FrontMessages[];
}
