import { z } from 'zod';
import { createAction } from 'nango';

const InputSchema = z
    .object({
        Name: z.string().describe('Full name of the contact. Required. Example: "ABC Customer"'),
        FirstName: z.string().optional().describe('First name of the contact. Example: "John"'),
        LastName: z.string().optional().describe('Last name of the contact. Example: "Smith"'),
        EmailAddress: z.string().optional().describe('Email address of the contact. Example: "john.smith@example.com"'),
        ContactNumber: z.string().optional().describe('Customer or supplier number for the contact. Example: "CUST-001"'),
        AccountNumber: z.string().optional().describe('Account number for the contact. Example: "ACC-001"'),
        TaxNumber: z.string().optional().describe('Tax number for the contact. Example: "12-3456789"'),
        BankAccountDetails: z.string().optional().describe('Bank account number for the contact. Example: "123-456-789"'),
        IsCustomer: z.boolean().optional().describe('Whether the contact is a customer. Defaults to false if omitted.'),
        IsSupplier: z.boolean().optional().describe('Whether the contact is a supplier. Defaults to false if omitted.')
    })
    .describe('Input for creating a Xero contact.');

const ProviderContactSchema = z.object({
    ContactID: z.string(),
    Name: z.string(),
    ContactNumber: z.string().nullish(),
    AccountNumber: z.string().nullish(),
    ContactStatus: z.string().nullish(),
    FirstName: z.string().nullish(),
    LastName: z.string().nullish(),
    EmailAddress: z.string().nullish(),
    TaxNumber: z.string().nullish(),
    BankAccountDetails: z.string().nullish(),
    IsCustomer: z.boolean().nullish(),
    IsSupplier: z.boolean().nullish()
});

const ProviderResponseSchema = z.object({
    Contacts: z.array(ProviderContactSchema)
});

const OutputSchema = z
    .object({
        contactId: z.string().describe('Unique identifier for the contact generated by Xero. Example: "27e853de-cfdc-4bf3-85e9-3979ee2bcaba"'),
        name: z.string().describe('Full name of the contact. Example: "ABC Customer"'),
        contactNumber: z.string().optional().describe('Customer or supplier number for the contact. Example: "CUST-001"'),
        accountNumber: z.string().optional().describe('Account number for the contact. Example: "ACC-001"'),
        contactStatus: z.string().optional().describe('Status of the contact. Example: "ACTIVE" or "ARCHIVED".'),
        firstName: z.string().optional().describe('First name of the contact. Example: "John"'),
        lastName: z.string().optional().describe('Last name of the contact. Example: "Smith"'),
        emailAddress: z.string().optional().describe('Email address of the contact. Example: "john.smith@example.com"'),
        taxNumber: z.string().optional().describe('Tax number for the contact. Example: "12-3456789"'),
        bankAccountDetails: z.string().optional().describe('Bank account number for the contact. Example: "123-456-789"'),
        isCustomer: z.boolean().optional().describe('Whether the contact is a customer.'),
        isSupplier: z.boolean().optional().describe('Whether the contact is a supplier.')
    })
    .describe('Output representing a created Xero contact.');

/**
 * @tags: [write]
 * @tagReason: Creates a new contact record in Xero.
 * @pitfalls: Contact names must be unique across all active contacts; attempting to create a contact with an existing name returns a validation error.
 */
const action = createAction({
    description: 'Create a contact in Xero.',
    version: '3.0.2',
    input: InputSchema,
    output: OutputSchema,
    scopes: ['accounting.contacts'],

    exec: async (nango, input): Promise<z.infer<typeof OutputSchema>> => {
        const tenantId = await resolveTenantId(nango);

        const response = await nango.put({
            // https://developer.xero.com/documentation/api/accounting/contacts
            endpoint: 'api.xro/2.0/Contacts',
            headers: {
                'xero-tenant-id': tenantId
            },
            data: {
                Contacts: [input]
            },
            retries: 3
        });

        const parsed = ProviderResponseSchema.parse(response.data);
        const contacts = parsed.Contacts;

        const contact = contacts.find(() => true);

        if (!contact) {
            throw new nango.ActionError({
                type: 'no_contacts_created',
                message: 'Xero did not return any created contacts.'
            });
        }

        return {
            contactId: contact.ContactID,
            name: contact.Name,
            ...(contact.ContactNumber != null && { contactNumber: contact.ContactNumber }),
            ...(contact.AccountNumber != null && { accountNumber: contact.AccountNumber }),
            ...(contact.ContactStatus != null && { contactStatus: contact.ContactStatus }),
            ...(contact.FirstName != null && { firstName: contact.FirstName }),
            ...(contact.LastName != null && { lastName: contact.LastName }),
            ...(contact.EmailAddress != null && { emailAddress: contact.EmailAddress }),
            ...(contact.TaxNumber != null && { taxNumber: contact.TaxNumber }),
            ...(contact.BankAccountDetails != null && { bankAccountDetails: contact.BankAccountDetails }),
            ...(contact.IsCustomer != null && { isCustomer: contact.IsCustomer }),
            ...(contact.IsSupplier != null && { isSupplier: contact.IsSupplier })
        };
    }
});

async function resolveTenantId(nango: Parameters<(typeof action)['exec']>[0]): Promise<string> {
    const connection = await nango.getConnection();

    const connectionConfigSchema = z.object({
        tenant_id: z.string().optional()
    });
    const connectionConfig = connectionConfigSchema.parse(connection.connection_config || {});

    if (connectionConfig.tenant_id) {
        return connectionConfig.tenant_id;
    }

    const metadataSchema = z.object({
        tenantId: z.string().optional()
    });
    const metadata = metadataSchema.parse(connection.metadata || {});

    if (metadata.tenantId) {
        return metadata.tenantId;
    }

    const connectionsResponse = await nango.get({
        // https://developer.xero.com/documentation/api/overview/connections
        endpoint: 'connections',
        retries: 10
    });

    const connectionsSchema = z.array(
        z.object({
            tenantId: z.string()
        })
    );

    const connections = connectionsSchema.parse(connectionsResponse.data || []);

    if (connections.length === 0) {
        throw new nango.ActionError({
            type: 'missing_tenant',
            message: 'No Xero tenants found for this connection.'
        });
    }

    if (connections.length > 1) {
        throw new nango.ActionError({
            type: 'multiple_tenants',
            message: 'Multiple tenants found. Please use the get-tenants action to set the chosen tenantId in the metadata.'
        });
    }

    const connectionEntry = connections.find(() => true);

    if (!connectionEntry || connectionEntry.tenantId.length === 0) {
        throw new nango.ActionError({
            type: 'missing_tenant',
            message: 'Unable to resolve xero-tenant-id.'
        });
    }

    return connectionEntry.tenantId;
}

export type NangoActionLocal = Parameters<(typeof action)['exec']>[0];
export default action;
