// ---------------------------
// This file was generated by Nango (v0.57.3)
// You can version this file
// ---------------------------

export interface FileMetadata {
  siteId: string;
  id: string;
  name: string;
  etag: string;
  cTag: string;
  is_folder: boolean;
  mime_type: string | null;
  path: string;
  raw_source: Record<string, any>;
  updated_at: string;
  download_url: string | null;
  created_at: string;
  blob_size: number;
};

export interface UserFileMetadata {
  siteId: string;
  id: string;
  name: string;
  etag: string;
  cTag: string;
  is_folder: boolean;
  mime_type: string | null;
  path: string;
  raw_source: Record<string, any>;
  updated_at: string;
  download_url: string | null;
  created_at: string;
  blob_size: number;
};

export interface SelectedUserFileMetadata {
  siteId: string;
  id: string;
  name: string;
  etag: string;
  cTag: string;
  is_folder: boolean;
  mime_type: string | null;
  path: string;
  raw_source: Record<string, any>;
  updated_at: string;
  download_url: string | null;
  created_at: string;
  blob_size: number;
};

export interface Site {
  id: string;
  name: string;
  createdDateTime: string;
  webUrl: string;
};

export interface PickedFile {
  siteId: string;
  fileIds: string[];
};

export interface SharepointMetadata {
  sharedSites: string[];
  pickedFiles: PickedFile[];
};

export interface SharepointSites {
  sitesToSync: Site[];
};

export interface FetchFileInput {
  siteId: string;
  itemId: string;
};

export interface FetchFile {
  id: string;
  download_url: string | null;
};
