import { z } from 'zod';
import { createAction } from 'nango';
import type { ProxyConfiguration } from 'nango';

const SubscriptionItemInputSchema = z.object({
    item_price_id: z.string().describe('The unique identifier of the item price. Example: "basic-plan-monthly"'),
    quantity: z.number().optional().describe('The quantity of the item purchased. Example: 1')
});

const InputSchema = z.object({
    customer_id: z.string().describe('The unique identifier of the customer. Example: "AzqOd0VMyVlxMaL6"'),
    subscription_items: z.array(SubscriptionItemInputSchema).describe('List of subscription items to create.'),
    auto_collection: z
        .enum(['on', 'off'])
        .optional()
        .describe('Defines whether payments need to be collected automatically. Defaults to "off" to skip payment requirement.'),
    id: z.string().optional().describe('A unique identifier for the subscription. If not provided, it is autogenerated.')
});

const SubscriptionItemSchema = z
    .object({
        item_price_id: z.string(),
        quantity: z.number().optional()
    })
    .passthrough();

const SubscriptionSchema = z
    .object({
        id: z.string(),
        customer_id: z.string(),
        status: z.string(),
        deleted: z.boolean(),
        subscription_items: z.array(SubscriptionItemSchema).optional()
    })
    .passthrough();

const OutputSchema = SubscriptionSchema;

const action = createAction({
    description: 'Create a subscription for a customer (Product Catalog 2.0).',
    version: '1.0.0',
    input: InputSchema,
    output: OutputSchema,

    exec: async (nango, input): Promise<z.infer<typeof OutputSchema>> => {
        const params: Record<string, string | number> = {
            auto_collection: input.auto_collection ?? 'off'
        };

        if (input.id !== undefined) {
            params['id'] = input.id;
        }

        let index = 0;
        for (const item of input.subscription_items) {
            params[`subscription_items[item_price_id][${index}]`] = item.item_price_id;
            if (item.quantity !== undefined) {
                params[`subscription_items[quantity][${index}]`] = item.quantity;
            }
            index++;
        }

        const config: ProxyConfiguration = {
            // https://apidocs.chargebee.com/docs/api/subscriptions#create_a_subscription_for_items
            endpoint: `/api/v2/customers/${encodeURIComponent(input.customer_id)}/subscription_for_items`,
            params,
            retries: 3
        };

        const response = await nango.post(config);

        const rawData = response.data;
        if (!rawData || typeof rawData !== 'object' || Array.isArray(rawData) || !('subscription' in rawData)) {
            throw new nango.ActionError({
                type: 'invalid_response',
                message: 'Unexpected response from Chargebee API'
            });
        }

        const subscription = SubscriptionSchema.parse(rawData.subscription);
        return subscription;
    }
});

export type NangoActionLocal = Parameters<(typeof action)['exec']>[0];
export default action;
