import { createSync } from 'nango';
import { z } from 'zod';

const OdataEnvelopeSchema = z.object({
    value: z.array(z.unknown())
});

const CheckpointSchema = z.object({
    skip: z.number().int().min(0)
});

const PurchaseOrderHeaderSchema = z
    .object({
        dataAreaId: z.string(),
        PurchaseOrderNumber: z.string(),
        PurchaseOrderName: z.string().nullish(),
        PurchaseOrderStatus: z.string().nullish(),
        OrderVendorAccountNumber: z.string().nullish(),
        InvoiceVendorAccountNumber: z.string().nullish(),
        CurrencyCode: z.string().nullish(),
        AccountingDate: z.string().nullish(),
        RequestedDeliveryDate: z.string().nullish(),
        ConfirmedDeliveryDate: z.string().nullish(),
        VendorOrderReference: z.string().nullish(),
        ProjectId: z.string().nullish(),
        PaymentTermsName: z.string().nullish(),
        DocumentApprovalStatus: z.string().nullish(),
        DeliveryAddressName: z.string().nullish(),
        DeliveryAddressCity: z.string().nullish(),
        DeliveryAddressStateId: z.string().nullish(),
        DeliveryAddressZipCode: z.string().nullish(),
        DeliveryAddressCountryRegionId: z.string().nullish(),
        DeliveryAddressCountryRegionISOCode: z.string().nullish(),
        FormattedDeliveryAddress: z.string().nullish(),
        PurchaseOrderPoolId: z.string().nullish(),
        TotalDiscountPercentage: z.number().nullish(),
        ArePricesIncludingSalesTax: z.string().nullish(),
        SalesTaxGroupCode: z.string().nullish(),
        LanguageId: z.string().nullish(),
        ReasonCode: z.string().nullish(),
        ReasonComment: z.string().nullish(),
        VendorPostingProfileId: z.string().nullish(),
        CashDiscountCode: z.string().nullish(),
        CashDiscountPercentage: z.number().nullish(),
        PaymentScheduleName: z.string().nullish(),
        ContactPersonId: z.string().nullish(),
        Email: z.string().nullish(),
        URL: z.string().nullish(),
        DefaultReceivingWarehouseId: z.string().nullish(),
        DefaultReceivingSiteId: z.string().nullish(),
        BuyerGroupId: z.string().nullish(),
        PurchaseOrderHeaderCreationMethod: z.string().nullish(),
        IsChangeManagementActive: z.string().nullish(),
        IsConsolidatedInvoiceTarget: z.string().nullish(),
        IsDeliveredDirectly: z.string().nullish(),
        IsDeliveryAddressOrderSpecific: z.string().nullish(),
        IsDeliveryAddressPrivate: z.string().nullish(),
        IsOneTimeVendor: z.string().nullish(),
        DeliveryTermsId: z.string().nullish(),
        TransportationModeId: z.string().nullish(),
        ShippingCarrierId: z.string().nullish(),
        ShippingCarrierServiceId: z.string().nullish(),
        ShipCalendarId: z.string().nullish(),
        BankDocumentType: z.string().nullish(),
        InvoiceType: z.string().nullish(),
        NumberSequenceGroupId: z.string().nullish(),
        ConfirmingPurchaseOrderCode: z.string().nullish(),
        FiscalDocumentOperationTypeId: z.string().nullish(),
        VendorInvoiceDeclarationId: z.string().nullish(),
        VendorTransactionSettlementType: z.string().nullish(),
        RequesterPersonnelNumber: z.string().nullish(),
        OrdererPersonnelNumber: z.string().nullish(),
        IntrastatTransactionCode: z.string().nullish(),
        IntrastatTransportModeCode: z.string().nullish(),
        IntrastatStatisticsProcedureCode: z.string().nullish(),
        EUSalesListCode: z.string().nullish(),
        ImportDeclarationNumber: z.string().nullish(),
        ZakatContractNumber: z.string().nullish(),
        GSTSelfBilledInvoiceApprovalNumber: z.string().nullish(),
        TradeEndCustomerAccount: z.string().nullish(),
        OverrideSalesTax: z.string().nullish(),
        TaxExemptNumber: z.string().nullish(),
        ReplenishmentWarehouseId: z.string().nullish(),
        ReplenishmentServiceCategoryId: z.string().nullish(),
        ExpectedStoreReceiptDate: z.string().nullish(),
        ExpectedStoreAvailableSalesDate: z.string().nullish(),
        ExpectedCrossDockingDate: z.string().nullish(),
        RequestedShipDate: z.string().nullish(),
        ConfirmedShipDate: z.string().nullish(),
        FixedDueDate: z.string().nullish(),
        DeliveryAddressLocationId: z.string().nullish(),
        DeliveryAddressLatitude: z.number().nullish(),
        DeliveryAddressLongitude: z.number().nullish(),
        DeliveryAddressTimeZone: z.string().nullish(),
        DeliveryAddressStreet: z.string().nullish(),
        DeliveryAddressStreetNumber: z.string().nullish(),
        DeliveryAddressPostBox: z.string().nullish(),
        DeliveryBuildingCompliment: z.string().nullish(),
        DeliveryAddressDistrictName: z.string().nullish(),
        DeliveryAddressCountyId: z.string().nullish(),
        DeliveryAddressDunsNumber: z.string().nullish(),
        DeliveryCityInKana: z.string().nullish(),
        DeliveryStreetInKana: z.string().nullish(),
        InvoiceAddressStreet: z.string().nullish(),
        InvoiceAddressStreetNumber: z.string().nullish(),
        InvoiceAddressCity: z.string().nullish(),
        InvoiceAddressState: z.string().nullish(),
        InvoiceAddressZipCode: z.string().nullish(),
        InvoiceAddressCountryRegionId: z.string().nullish(),
        InvoiceAddressCounty: z.string().nullish(),
        FormattedInvoiceAddress: z.string().nullish(),
        AttentionInformation: z.string().nullish(),
        AccountingDistributionTemplateName: z.string().nullish(),
        MultilineDiscountVendorGroupCode: z.string().nullish(),
        LineDiscountVendorGroupCode: z.string().nullish(),
        TotalDiscountVendorGroupCode: z.string().nullish(),
        PriceVendorGroupCode: z.string().nullish(),
        PurchaseRebateVendorGroupId: z.string().nullish(),
        ChargeVendorGroupId: z.string().nullish(),
        DeliveryModeId: z.string().nullish(),
        TransportationTemplateId: z.string().nullish(),
        TransportationRoutePlanId: z.string().nullish(),
        ShippingCarrierServiceGroupId: z.string().nullish(),
        FinTagDisplayValue: z.string().nullish()
    })
    .passthrough();

const PurchaseOrderSchema = z.object({
    id: z.string(),
    dataAreaId: z.string(),
    PurchaseOrderNumber: z.string(),
    PurchaseOrderName: z.string().optional(),
    PurchaseOrderStatus: z.string().optional(),
    OrderVendorAccountNumber: z.string().optional(),
    InvoiceVendorAccountNumber: z.string().optional(),
    CurrencyCode: z.string().optional(),
    AccountingDate: z.string().optional(),
    RequestedDeliveryDate: z.string().optional(),
    ConfirmedDeliveryDate: z.string().optional(),
    VendorOrderReference: z.string().optional(),
    ProjectId: z.string().optional(),
    PaymentTermsName: z.string().optional(),
    DocumentApprovalStatus: z.string().optional(),
    DeliveryAddressName: z.string().optional(),
    DeliveryAddressCity: z.string().optional(),
    DeliveryAddressStateId: z.string().optional(),
    DeliveryAddressZipCode: z.string().optional(),
    DeliveryAddressCountryRegionId: z.string().optional(),
    DeliveryAddressCountryRegionISOCode: z.string().optional(),
    FormattedDeliveryAddress: z.string().optional(),
    PurchaseOrderPoolId: z.string().optional(),
    TotalDiscountPercentage: z.number().optional(),
    ArePricesIncludingSalesTax: z.string().optional(),
    SalesTaxGroupCode: z.string().optional(),
    LanguageId: z.string().optional(),
    ReasonCode: z.string().optional(),
    ReasonComment: z.string().optional(),
    VendorPostingProfileId: z.string().optional(),
    CashDiscountCode: z.string().optional(),
    CashDiscountPercentage: z.number().optional(),
    PaymentScheduleName: z.string().optional(),
    ContactPersonId: z.string().optional(),
    Email: z.string().optional(),
    URL: z.string().optional(),
    DefaultReceivingWarehouseId: z.string().optional(),
    DefaultReceivingSiteId: z.string().optional(),
    BuyerGroupId: z.string().optional(),
    PurchaseOrderHeaderCreationMethod: z.string().optional(),
    IsChangeManagementActive: z.string().optional(),
    IsConsolidatedInvoiceTarget: z.string().optional(),
    IsDeliveredDirectly: z.string().optional(),
    IsDeliveryAddressOrderSpecific: z.string().optional(),
    IsDeliveryAddressPrivate: z.string().optional(),
    IsOneTimeVendor: z.string().optional(),
    DeliveryTermsId: z.string().optional(),
    TransportationModeId: z.string().optional(),
    ShippingCarrierId: z.string().optional(),
    ShippingCarrierServiceId: z.string().optional(),
    ShipCalendarId: z.string().optional(),
    BankDocumentType: z.string().optional(),
    InvoiceType: z.string().optional(),
    NumberSequenceGroupId: z.string().optional(),
    ConfirmingPurchaseOrderCode: z.string().optional(),
    FiscalDocumentOperationTypeId: z.string().optional(),
    VendorInvoiceDeclarationId: z.string().optional(),
    VendorTransactionSettlementType: z.string().optional(),
    RequesterPersonnelNumber: z.string().optional(),
    OrdererPersonnelNumber: z.string().optional(),
    IntrastatTransactionCode: z.string().optional(),
    IntrastatTransportModeCode: z.string().optional(),
    IntrastatStatisticsProcedureCode: z.string().optional(),
    EUSalesListCode: z.string().optional(),
    ImportDeclarationNumber: z.string().optional(),
    ZakatContractNumber: z.string().optional(),
    GSTSelfBilledInvoiceApprovalNumber: z.string().optional(),
    TradeEndCustomerAccount: z.string().optional(),
    OverrideSalesTax: z.string().optional(),
    TaxExemptNumber: z.string().optional(),
    ReplenishmentWarehouseId: z.string().optional(),
    ReplenishmentServiceCategoryId: z.string().optional(),
    ExpectedStoreReceiptDate: z.string().optional(),
    ExpectedStoreAvailableSalesDate: z.string().optional(),
    ExpectedCrossDockingDate: z.string().optional(),
    RequestedShipDate: z.string().optional(),
    ConfirmedShipDate: z.string().optional(),
    FixedDueDate: z.string().optional(),
    DeliveryAddressLocationId: z.string().optional(),
    DeliveryAddressLatitude: z.number().optional(),
    DeliveryAddressLongitude: z.number().optional(),
    DeliveryAddressTimeZone: z.string().optional(),
    DeliveryAddressStreet: z.string().optional(),
    DeliveryAddressStreetNumber: z.string().optional(),
    DeliveryAddressPostBox: z.string().optional(),
    DeliveryBuildingCompliment: z.string().optional(),
    DeliveryAddressDistrictName: z.string().optional(),
    DeliveryAddressCountyId: z.string().optional(),
    DeliveryAddressDunsNumber: z.string().optional(),
    DeliveryCityInKana: z.string().optional(),
    DeliveryStreetInKana: z.string().optional(),
    InvoiceAddressStreet: z.string().optional(),
    InvoiceAddressStreetNumber: z.string().optional(),
    InvoiceAddressCity: z.string().optional(),
    InvoiceAddressState: z.string().optional(),
    InvoiceAddressZipCode: z.string().optional(),
    InvoiceAddressCountryRegionId: z.string().optional(),
    InvoiceAddressCounty: z.string().optional(),
    FormattedInvoiceAddress: z.string().optional(),
    AttentionInformation: z.string().optional(),
    AccountingDistributionTemplateName: z.string().optional(),
    MultilineDiscountVendorGroupCode: z.string().optional(),
    LineDiscountVendorGroupCode: z.string().optional(),
    TotalDiscountVendorGroupCode: z.string().optional(),
    PriceVendorGroupCode: z.string().optional(),
    PurchaseRebateVendorGroupId: z.string().optional(),
    ChargeVendorGroupId: z.string().optional(),
    DeliveryModeId: z.string().optional(),
    TransportationTemplateId: z.string().optional(),
    TransportationRoutePlanId: z.string().optional(),
    ShippingCarrierServiceGroupId: z.string().optional(),
    FinTagDisplayValue: z.string().optional()
});

const sync = createSync({
    description: 'Sync purchase order headers.',
    version: '1.0.0',
    frequency: 'every hour',
    autoStart: true,
    checkpoint: CheckpointSchema,
    models: {
        PurchaseOrder: PurchaseOrderSchema
    },

    exec: async (nango) => {
        const checkpoint = CheckpointSchema.safeParse(await nango.getCheckpoint());
        let skip = checkpoint.success ? checkpoint.data.skip : 0;
        const limit = 10;
        let hasMore = true;

        if (skip === 0) {
            await nango.trackDeletesStart('PurchaseOrder');
        }

        while (hasMore) {
            const response = await nango.get({
                // https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/data-entities/odata
                endpoint: '/data/PurchaseOrderHeadersV2',
                params: {
                    $top: String(limit),
                    $skip: String(skip),
                    'cross-company': 'true',
                    $orderby: 'dataAreaId asc,PurchaseOrderNumber asc'
                },
                retries: 3
            });

            const envelope = OdataEnvelopeSchema.safeParse(response.data);
            if (!envelope.success) {
                throw new Error(`Failed to parse OData response: ${envelope.error.message}`);
            }

            const pageRecords: z.infer<typeof PurchaseOrderSchema>[] = [];

            for (const raw of envelope.data.value) {
                const parsed = PurchaseOrderHeaderSchema.safeParse(raw);
                if (!parsed.success) {
                    throw new Error(`Failed to parse purchase order: ${parsed.error.message}`);
                }

                const header = parsed.data;
                const id = `${header.dataAreaId}|${header.PurchaseOrderNumber}`;

                pageRecords.push({
                    id,
                    dataAreaId: header.dataAreaId,
                    PurchaseOrderNumber: header.PurchaseOrderNumber,
                    ...(header.PurchaseOrderName != null && { PurchaseOrderName: header.PurchaseOrderName }),
                    ...(header.PurchaseOrderStatus != null && { PurchaseOrderStatus: header.PurchaseOrderStatus }),
                    ...(header.OrderVendorAccountNumber != null && { OrderVendorAccountNumber: header.OrderVendorAccountNumber }),
                    ...(header.InvoiceVendorAccountNumber != null && { InvoiceVendorAccountNumber: header.InvoiceVendorAccountNumber }),
                    ...(header.CurrencyCode != null && { CurrencyCode: header.CurrencyCode }),
                    ...(header.AccountingDate != null && { AccountingDate: header.AccountingDate }),
                    ...(header.RequestedDeliveryDate != null && { RequestedDeliveryDate: header.RequestedDeliveryDate }),
                    ...(header.ConfirmedDeliveryDate != null && { ConfirmedDeliveryDate: header.ConfirmedDeliveryDate }),
                    ...(header.VendorOrderReference != null && { VendorOrderReference: header.VendorOrderReference }),
                    ...(header.ProjectId != null && { ProjectId: header.ProjectId }),
                    ...(header.PaymentTermsName != null && { PaymentTermsName: header.PaymentTermsName }),
                    ...(header.DocumentApprovalStatus != null && { DocumentApprovalStatus: header.DocumentApprovalStatus }),
                    ...(header.DeliveryAddressName != null && { DeliveryAddressName: header.DeliveryAddressName }),
                    ...(header.DeliveryAddressCity != null && { DeliveryAddressCity: header.DeliveryAddressCity }),
                    ...(header.DeliveryAddressStateId != null && { DeliveryAddressStateId: header.DeliveryAddressStateId }),
                    ...(header.DeliveryAddressZipCode != null && { DeliveryAddressZipCode: header.DeliveryAddressZipCode }),
                    ...(header.DeliveryAddressCountryRegionId != null && { DeliveryAddressCountryRegionId: header.DeliveryAddressCountryRegionId }),
                    ...(header.DeliveryAddressCountryRegionISOCode != null && {
                        DeliveryAddressCountryRegionISOCode: header.DeliveryAddressCountryRegionISOCode
                    }),
                    ...(header.FormattedDeliveryAddress != null && { FormattedDeliveryAddress: header.FormattedDeliveryAddress }),
                    ...(header.PurchaseOrderPoolId != null && { PurchaseOrderPoolId: header.PurchaseOrderPoolId }),
                    ...(header.TotalDiscountPercentage != null && { TotalDiscountPercentage: header.TotalDiscountPercentage }),
                    ...(header.ArePricesIncludingSalesTax != null && { ArePricesIncludingSalesTax: header.ArePricesIncludingSalesTax }),
                    ...(header.SalesTaxGroupCode != null && { SalesTaxGroupCode: header.SalesTaxGroupCode }),
                    ...(header.LanguageId != null && { LanguageId: header.LanguageId }),
                    ...(header.ReasonCode != null && { ReasonCode: header.ReasonCode }),
                    ...(header.ReasonComment != null && { ReasonComment: header.ReasonComment }),
                    ...(header.VendorPostingProfileId != null && { VendorPostingProfileId: header.VendorPostingProfileId }),
                    ...(header.CashDiscountCode != null && { CashDiscountCode: header.CashDiscountCode }),
                    ...(header.CashDiscountPercentage != null && { CashDiscountPercentage: header.CashDiscountPercentage }),
                    ...(header.PaymentScheduleName != null && { PaymentScheduleName: header.PaymentScheduleName }),
                    ...(header.ContactPersonId != null && { ContactPersonId: header.ContactPersonId }),
                    ...(header.Email != null && { Email: header.Email }),
                    ...(header.URL != null && { URL: header.URL }),
                    ...(header.DefaultReceivingWarehouseId != null && { DefaultReceivingWarehouseId: header.DefaultReceivingWarehouseId }),
                    ...(header.DefaultReceivingSiteId != null && { DefaultReceivingSiteId: header.DefaultReceivingSiteId }),
                    ...(header.BuyerGroupId != null && { BuyerGroupId: header.BuyerGroupId }),
                    ...(header.PurchaseOrderHeaderCreationMethod != null && { PurchaseOrderHeaderCreationMethod: header.PurchaseOrderHeaderCreationMethod }),
                    ...(header.IsChangeManagementActive != null && { IsChangeManagementActive: header.IsChangeManagementActive }),
                    ...(header.IsConsolidatedInvoiceTarget != null && { IsConsolidatedInvoiceTarget: header.IsConsolidatedInvoiceTarget }),
                    ...(header.IsDeliveredDirectly != null && { IsDeliveredDirectly: header.IsDeliveredDirectly }),
                    ...(header.IsDeliveryAddressOrderSpecific != null && { IsDeliveryAddressOrderSpecific: header.IsDeliveryAddressOrderSpecific }),
                    ...(header.IsDeliveryAddressPrivate != null && { IsDeliveryAddressPrivate: header.IsDeliveryAddressPrivate }),
                    ...(header.IsOneTimeVendor != null && { IsOneTimeVendor: header.IsOneTimeVendor }),
                    ...(header.DeliveryTermsId != null && { DeliveryTermsId: header.DeliveryTermsId }),
                    ...(header.TransportationModeId != null && { TransportationModeId: header.TransportationModeId }),
                    ...(header.ShippingCarrierId != null && { ShippingCarrierId: header.ShippingCarrierId }),
                    ...(header.ShippingCarrierServiceId != null && { ShippingCarrierServiceId: header.ShippingCarrierServiceId }),
                    ...(header.ShipCalendarId != null && { ShipCalendarId: header.ShipCalendarId }),
                    ...(header.BankDocumentType != null && { BankDocumentType: header.BankDocumentType }),
                    ...(header.InvoiceType != null && { InvoiceType: header.InvoiceType }),
                    ...(header.NumberSequenceGroupId != null && { NumberSequenceGroupId: header.NumberSequenceGroupId }),
                    ...(header.ConfirmingPurchaseOrderCode != null && { ConfirmingPurchaseOrderCode: header.ConfirmingPurchaseOrderCode }),
                    ...(header.FiscalDocumentOperationTypeId != null && { FiscalDocumentOperationTypeId: header.FiscalDocumentOperationTypeId }),
                    ...(header.VendorInvoiceDeclarationId != null && { VendorInvoiceDeclarationId: header.VendorInvoiceDeclarationId }),
                    ...(header.VendorTransactionSettlementType != null && { VendorTransactionSettlementType: header.VendorTransactionSettlementType }),
                    ...(header.RequesterPersonnelNumber != null && { RequesterPersonnelNumber: header.RequesterPersonnelNumber }),
                    ...(header.OrdererPersonnelNumber != null && { OrdererPersonnelNumber: header.OrdererPersonnelNumber }),
                    ...(header.IntrastatTransactionCode != null && { IntrastatTransactionCode: header.IntrastatTransactionCode }),
                    ...(header.IntrastatTransportModeCode != null && { IntrastatTransportModeCode: header.IntrastatTransportModeCode }),
                    ...(header.IntrastatStatisticsProcedureCode != null && { IntrastatStatisticsProcedureCode: header.IntrastatStatisticsProcedureCode }),
                    ...(header.EUSalesListCode != null && { EUSalesListCode: header.EUSalesListCode }),
                    ...(header.ImportDeclarationNumber != null && { ImportDeclarationNumber: header.ImportDeclarationNumber }),
                    ...(header.ZakatContractNumber != null && { ZakatContractNumber: header.ZakatContractNumber }),
                    ...(header.GSTSelfBilledInvoiceApprovalNumber != null && { GSTSelfBilledInvoiceApprovalNumber: header.GSTSelfBilledInvoiceApprovalNumber }),
                    ...(header.TradeEndCustomerAccount != null && { TradeEndCustomerAccount: header.TradeEndCustomerAccount }),
                    ...(header.OverrideSalesTax != null && { OverrideSalesTax: header.OverrideSalesTax }),
                    ...(header.TaxExemptNumber != null && { TaxExemptNumber: header.TaxExemptNumber }),
                    ...(header.ReplenishmentWarehouseId != null && { ReplenishmentWarehouseId: header.ReplenishmentWarehouseId }),
                    ...(header.ReplenishmentServiceCategoryId != null && { ReplenishmentServiceCategoryId: header.ReplenishmentServiceCategoryId }),
                    ...(header.ExpectedStoreReceiptDate != null && { ExpectedStoreReceiptDate: header.ExpectedStoreReceiptDate }),
                    ...(header.ExpectedStoreAvailableSalesDate != null && { ExpectedStoreAvailableSalesDate: header.ExpectedStoreAvailableSalesDate }),
                    ...(header.ExpectedCrossDockingDate != null && { ExpectedCrossDockingDate: header.ExpectedCrossDockingDate }),
                    ...(header.RequestedShipDate != null && { RequestedShipDate: header.RequestedShipDate }),
                    ...(header.ConfirmedShipDate != null && { ConfirmedShipDate: header.ConfirmedShipDate }),
                    ...(header.FixedDueDate != null && { FixedDueDate: header.FixedDueDate }),
                    ...(header.DeliveryAddressLocationId != null && { DeliveryAddressLocationId: header.DeliveryAddressLocationId }),
                    ...(header.DeliveryAddressLatitude != null && { DeliveryAddressLatitude: header.DeliveryAddressLatitude }),
                    ...(header.DeliveryAddressLongitude != null && { DeliveryAddressLongitude: header.DeliveryAddressLongitude }),
                    ...(header.DeliveryAddressTimeZone != null && { DeliveryAddressTimeZone: header.DeliveryAddressTimeZone }),
                    ...(header.DeliveryAddressStreet != null && { DeliveryAddressStreet: header.DeliveryAddressStreet }),
                    ...(header.DeliveryAddressStreetNumber != null && { DeliveryAddressStreetNumber: header.DeliveryAddressStreetNumber }),
                    ...(header.DeliveryAddressPostBox != null && { DeliveryAddressPostBox: header.DeliveryAddressPostBox }),
                    ...(header.DeliveryBuildingCompliment != null && { DeliveryBuildingCompliment: header.DeliveryBuildingCompliment }),
                    ...(header.DeliveryAddressDistrictName != null && { DeliveryAddressDistrictName: header.DeliveryAddressDistrictName }),
                    ...(header.DeliveryAddressCountyId != null && { DeliveryAddressCountyId: header.DeliveryAddressCountyId }),
                    ...(header.DeliveryAddressDunsNumber != null && { DeliveryAddressDunsNumber: header.DeliveryAddressDunsNumber }),
                    ...(header.DeliveryCityInKana != null && { DeliveryCityInKana: header.DeliveryCityInKana }),
                    ...(header.DeliveryStreetInKana != null && { DeliveryStreetInKana: header.DeliveryStreetInKana }),
                    ...(header.InvoiceAddressStreet != null && { InvoiceAddressStreet: header.InvoiceAddressStreet }),
                    ...(header.InvoiceAddressStreetNumber != null && { InvoiceAddressStreetNumber: header.InvoiceAddressStreetNumber }),
                    ...(header.InvoiceAddressCity != null && { InvoiceAddressCity: header.InvoiceAddressCity }),
                    ...(header.InvoiceAddressState != null && { InvoiceAddressState: header.InvoiceAddressState }),
                    ...(header.InvoiceAddressZipCode != null && { InvoiceAddressZipCode: header.InvoiceAddressZipCode }),
                    ...(header.InvoiceAddressCountryRegionId != null && { InvoiceAddressCountryRegionId: header.InvoiceAddressCountryRegionId }),
                    ...(header.InvoiceAddressCounty != null && { InvoiceAddressCounty: header.InvoiceAddressCounty }),
                    ...(header.FormattedInvoiceAddress != null && { FormattedInvoiceAddress: header.FormattedInvoiceAddress }),
                    ...(header.AttentionInformation != null && { AttentionInformation: header.AttentionInformation }),
                    ...(header.AccountingDistributionTemplateName != null && { AccountingDistributionTemplateName: header.AccountingDistributionTemplateName }),
                    ...(header.MultilineDiscountVendorGroupCode != null && { MultilineDiscountVendorGroupCode: header.MultilineDiscountVendorGroupCode }),
                    ...(header.LineDiscountVendorGroupCode != null && { LineDiscountVendorGroupCode: header.LineDiscountVendorGroupCode }),
                    ...(header.TotalDiscountVendorGroupCode != null && { TotalDiscountVendorGroupCode: header.TotalDiscountVendorGroupCode }),
                    ...(header.PriceVendorGroupCode != null && { PriceVendorGroupCode: header.PriceVendorGroupCode }),
                    ...(header.PurchaseRebateVendorGroupId != null && { PurchaseRebateVendorGroupId: header.PurchaseRebateVendorGroupId }),
                    ...(header.ChargeVendorGroupId != null && { ChargeVendorGroupId: header.ChargeVendorGroupId }),
                    ...(header.DeliveryModeId != null && { DeliveryModeId: header.DeliveryModeId }),
                    ...(header.TransportationTemplateId != null && { TransportationTemplateId: header.TransportationTemplateId }),
                    ...(header.TransportationRoutePlanId != null && { TransportationRoutePlanId: header.TransportationRoutePlanId }),
                    ...(header.ShippingCarrierServiceGroupId != null && { ShippingCarrierServiceGroupId: header.ShippingCarrierServiceGroupId }),
                    ...(header.FinTagDisplayValue != null && { FinTagDisplayValue: header.FinTagDisplayValue })
                });
            }

            if (pageRecords.length > 0) {
                await nango.batchSave(pageRecords, 'PurchaseOrder');
            }

            skip += envelope.data.value.length;
            await nango.saveCheckpoint({ skip });

            hasMore = envelope.data.value.length === limit;
        }

        await nango.clearCheckpoint();
        await nango.trackDeletesEnd('PurchaseOrder');
    }
});

export type NangoSyncLocal = Parameters<(typeof sync)['exec']>[0];
export default sync;
