// ---------------------------
// This file was generated by Nango (v0.56.1)
// You can version this file
// ---------------------------

export interface WorkableCandidate {
    id: string;
    name: string;
    firstname: string;
    lastname: string;
    headline: string;
    account: { subdomain: string; name: string };
    job: { shortcode: string; title: string };
    stage: string;
    disqualified: boolean;
    disqualification_reason: string;
    hired_at: Date;
    sourced: boolean;
    profile_url: string;
    address: string;
    phone: string;
    email: string;
    domain: string;
    created_at: Date;
    updated_at: Date;
}

export interface WorkableJobsCandidate {
    id: string;
    name: string;
    firstname: string;
    lastname: string;
    headline: string;
    account: { subdomain: string; name: string };
    job: { shortcode: string; title: string };
    stage: string;
    disqualified: boolean;
    disqualification_reason: string;
    hired_at: Date;
    sourced: boolean;
    profile_url: string;
    address: string;
    phone: string;
    email: string;
    domain: string;
    created_at: Date;
    updated_at: Date;
}

export interface WorkableCandidateActivity {
    id: string;
    action: string;
    stage_name: string;
    created_at: Date;
    body: string;
    member: { id: string; name: string };
    rating: Record<string, any>;
}

export interface WorkableCandidateOffer {
    id: string;
    candidate: { id: string; name: string };
    created_at: Date;
    document_variables: any[];
    documents: any[];
    state: string;
}

export interface WorkableJob {
    id: string;
    title: string;
    full_title: string;
    shortcode: string;
    code: string;
    state: string;
    sample: boolean;
    department: string;
    department_hierarchy: any[];
    url: string;
    application_url: string;
    shortlink: string;
    location: {
        location_str: string;
        country: string;
        country_code: string;
        region: string;
        region_code: string;
        city: string;
        zip_code: string;
        telecommuting: boolean;
        workplace_type: string;
    };
    locations: any[];
    salary: { salary_from: number; salary_to: number; salary_currency: string };
    created_at: Date;
}

export interface WorkableJobQuestion {
    id: string;
    body: string;
    type: string;
    required: boolean;
    single_answer: boolean;
    choices: { id: string; body: string };
    supported_file_types: any[];
    max_file_size: number;
}

export interface WorkableMember {
    id: string;
    name: string;
    headline: string;
    email: string;
    role: string;
}

export interface WorkableCreateCandidateResponse {
    status: string;
    candidate: {
        id: string;
        name: string;
        firstname: string;
        lastname: string;
        headline: string;
        account: { subdomain: string; name: string };
        job: { shortcode: string; title: string };
        stage: string;
        disqualified: boolean;
        disqualification_reason: string;
        hired_at: Date;
        sourced: boolean;
        profile_url: string;
        address: string;
        phone: string;
        email: string;
        domain: string;
        created_at: Date;
        updated_at: Date;
        image_url: string;
        outbound_mailbox: string;
        uploader_id: string;
        cover_letter: string;
        summary: string;
        education_entries: any[];
        experience_entries: any[];
        skills: any[];
        answers: any[];
        resume_url: string;
        tags: any[];
        location: { location_str: string; country: string; country_code: string; region: string; region_code: string; city: string; zip_code: string };
    };
}

export interface WorkableCreateCommentResponse {
    id: string;
}

export interface EducationEntry {
    school: string;
    degree: string | undefined;
    field_of_study: string | undefined;
    start_date: string | undefined;
    end_date: string | undefined;
}

export interface ExperienceEntry {
    title: string;
    summary: string | undefined;
    start_date: string | undefined;
    end_date: string | undefined;
    current: boolean | undefined;
    company: string | undefined;
    industry: string | undefined;
}

export interface Answer {
    question_key: string;
    body: string | undefined;
    choices: string[];
    checked: boolean | undefined;
    date: string | undefined;
    number: number | undefined;
    file: { name: string; data: string };
}

export interface SocialProfile {
    type: string;
    name: string | undefined;
    username: string | undefined;
    url: string;
}

export interface WorkableCreateCandidateInput {
    shortcode: string;
    candidate: {
        name: string;
        firstname: string;
        lastname: string;
        email: string;
        headline: string | undefined;
        summary: string | undefined;
        address: string | undefined;
        phone: string | undefined;
        cover_letter: string | undefined;
        education_entries: EducationEntry[] | undefined;
        experience_entries: ExperienceEntry[] | undefined;
        answers: Answer[] | undefined;
        skills: string[] | undefined;
        tags: string[] | undefined;
        disqualified: boolean | undefined;
        disqualification_reason: string | undefined;
        disqualified_at: string | undefined;
        social_profiles: SocialProfile[] | undefined;
    };
    domain: string | undefined;
    recruiter_key: string | undefined;
}

export interface Attachment {
    name: string;
    data: string;
}

export interface WorkableCreateCommentInput {
    id: string;
    member_id: string;
    comment: { body: string; policy: string[] | undefined; attachment: Attachment | undefined };
}
