import { z } from 'zod';
import { createAction } from 'nango';

const OrganizationsResponseSchema = z.object({
    code: z.number(),
    organizations: z.array(z.object({ organization_id: z.string() })).optional()
});

const LineItemInputSchema = z.object({
    item_id: z.string().describe('ID of a purchase-capable item. Example: "260815000000111052"'),
    rate: z.number().describe('Purchase rate per unit. Example: 50'),
    quantity: z.number().describe('Quantity ordered. Example: 2'),
    description: z.string().optional().describe('Description for the line item.'),
    unit: z.string().optional().describe('Unit of measurement. Example: "qty"')
});

const InputSchema = z
    .object({
        organization_id: z
            .string()
            .optional()
            .describe(
                'Zoho Inventory organization ID. If omitted and only one organization exists, it is used automatically. Required when multiple organizations exist.'
            ),
        vendor_id: z.string().describe('Vendor (contact) ID the purchase order is addressed to. Example: "260815000000098001"'),
        line_items: z.array(LineItemInputSchema).min(1).describe('At least one line item is required.'),
        purchaseorder_number: z.string().optional().describe('Purchase order number. Example: "PO-001"'),
        date: z.string().optional().describe('Purchase order date. Format: YYYY-MM-DD. Example: "2026-10-09"'),
        delivery_date: z.string().optional().describe('Expected delivery date. Format: YYYY-MM-DD. Example: "2026-10-16"'),
        reference_number: z.string().optional().describe('Reference number for the purchase order.'),
        notes: z.string().optional().describe('Notes for the purchase order.'),
        terms: z.string().optional().describe('Terms and conditions.'),
        currency_id: z.string().optional().describe('Currency ID. Example: "260815000000000097"')
    })
    .describe('Input for creating a Zoho Inventory purchase order for a vendor.');

const ProviderLineItemSchema = z.object({
    line_item_id: z.string().nullish(),
    item_id: z.string().nullish(),
    name: z.string().nullish(),
    description: z.string().nullish(),
    rate: z.number().nullish(),
    purchase_rate: z.number().nullish(),
    quantity: z.number().nullish(),
    unit: z.string().nullish()
});

const ProviderPurchaseOrderSchema = z.object({
    purchaseorder_id: z.string().nullish(),
    purchaseorder_number: z.string().nullish(),
    status: z.string().nullish(),
    vendor_id: z.string().nullish(),
    vendor_name: z.string().nullish(),
    date: z.string().nullish(),
    delivery_date: z.string().nullish(),
    total: z.number().nullish(),
    line_items: z.array(ProviderLineItemSchema).nullish()
});

const ProviderResponseSchema = z.object({
    code: z.number(),
    message: z.string(),
    purchaseorder: ProviderPurchaseOrderSchema.nullish()
});

const LineItemOutputSchema = z.object({
    line_item_id: z.string().optional().describe('Unique ID of the line item within the purchase order.'),
    item_id: z.string().optional().describe('ID of the item ordered.'),
    name: z.string().optional().describe('Item name.'),
    description: z.string().optional().describe('Description for the line item.'),
    rate: z.number().optional().describe('Purchase rate per unit.'),
    quantity: z.number().optional().describe('Quantity ordered.'),
    unit: z.string().optional().describe('Unit of measurement.')
});

const OutputSchema = z
    .object({
        id: z.string().optional().describe('Unique ID generated by Zoho for the purchase order.'),
        purchaseorder_number: z.string().optional().describe('Purchase order number assigned by Zoho.'),
        status: z.string().optional().describe('Purchase order status. Newly created purchase orders are "draft".'),
        vendor_id: z.string().optional().describe('Vendor (contact) ID the purchase order is addressed to.'),
        vendor_name: z.string().optional().describe('Vendor display name.'),
        date: z.string().optional().describe('Purchase order date.'),
        delivery_date: z.string().optional().describe('Expected delivery date.'),
        total: z.number().optional().describe('Total amount of the purchase order.'),
        line_items: z.array(LineItemOutputSchema).optional().describe('Line items on the purchase order.')
    })
    .describe('The newly created purchase order, including its ID, number, status, vendor, dates, total, and line items.');

/**
 * @tags: [read, write]
 * @tagReason: Reads the organization when organization_id is omitted, then creates a purchase order.
 * @pitfalls: Each line item's item_id must reference an item created with item_type "sales_and_purchases"; items holding only sales information are rejected with error code 29032. Newly created purchase orders start in "draft" status rather than being issued.
 */
const action = createAction({
    description: 'Create a new purchase order for a vendor in Zoho Inventory.',
    version: '1.0.0',
    input: InputSchema,
    output: OutputSchema,
    scopes: ['ZohoInventory.purchaseorders.CREATE', 'ZohoInventory.settings.READ'],

    exec: async (nango, input): Promise<z.infer<typeof OutputSchema>> => {
        let organizationId = input.organization_id;
        if (!organizationId) {
            const orgResponse = await nango.get({
                // https://www.zoho.com/inventory/api/v1/organizations/#list-organizations
                endpoint: '/inventory/v1/organizations',
                retries: 3
            });
            const orgData = OrganizationsResponseSchema.parse(orgResponse.data);
            if (orgData.code !== 0) {
                throw new nango.ActionError({
                    type: 'provider_error',
                    message: 'Failed to retrieve organizations from Zoho Inventory.'
                });
            }
            if (!orgData.organizations || orgData.organizations.length === 0) {
                throw new nango.ActionError({
                    type: 'not_found',
                    message: 'No organizations found for this Zoho Inventory account.'
                });
            }
            if (orgData.organizations.length > 1) {
                throw new nango.ActionError({
                    type: 'multiple_organizations',
                    message: `Multiple organizations found (${orgData.organizations.map((o) => o.organization_id).join(', ')}). Provide organization_id in the action input.`
                });
            }
            const singleOrg = orgData.organizations[0];
            if (!singleOrg) {
                throw new nango.ActionError({
                    type: 'not_found',
                    message: 'No organizations found for this Zoho Inventory account.'
                });
            }
            organizationId = singleOrg.organization_id;
        }

        const requestBody: Record<string, unknown> = {
            vendor_id: input.vendor_id,
            line_items: input.line_items.map((item) => ({
                item_id: item.item_id,
                rate: item.rate,
                quantity: item.quantity,
                ...(item.description !== undefined && { description: item.description }),
                ...(item.unit !== undefined && { unit: item.unit })
            }))
        };

        if (input.purchaseorder_number !== undefined) {
            requestBody['purchaseorder_number'] = input.purchaseorder_number;
        }

        if (input.date !== undefined) {
            requestBody['date'] = input.date;
        }

        if (input.delivery_date !== undefined) {
            requestBody['delivery_date'] = input.delivery_date;
        }

        if (input.reference_number !== undefined) {
            requestBody['reference_number'] = input.reference_number;
        }

        if (input.notes !== undefined) {
            requestBody['notes'] = input.notes;
        }

        if (input.terms !== undefined) {
            requestBody['terms'] = input.terms;
        }

        if (input.currency_id !== undefined) {
            requestBody['currency_id'] = input.currency_id;
        }

        const response = await nango.post({
            // https://www.zoho.com/inventory/api/v1/purchaseorders/#create-a-purchase-order
            endpoint: '/inventory/v1/purchaseorders',
            params: {
                organization_id: organizationId
            },
            data: requestBody,
            // Creating a purchase order is not idempotent: a retry after a lost response would create a duplicate order.
            // eslint-disable-next-line @nangohq/custom-integrations-linting/proxy-call-retries
            retries: 0
        });

        const providerResponse = ProviderResponseSchema.safeParse(response.data);

        if (!providerResponse.success) {
            throw new nango.ActionError({
                type: 'invalid_response',
                message: 'Failed to parse provider response.',
                details: providerResponse.error.message
            });
        }

        const data = providerResponse.data;

        if (data.code !== 0) {
            throw new nango.ActionError({
                type: 'provider_error',
                message: data.message,
                code: data.code
            });
        }

        const po = data.purchaseorder;

        if (!po) {
            throw new nango.ActionError({
                type: 'missing_purchase_order',
                message: 'Purchase order data missing from provider response.'
            });
        }

        return {
            ...(po.purchaseorder_id != null && { id: po.purchaseorder_id }),
            ...(po.purchaseorder_number != null && { purchaseorder_number: po.purchaseorder_number }),
            ...(po.status != null && { status: po.status }),
            ...(po.vendor_id != null && { vendor_id: po.vendor_id }),
            ...(po.vendor_name != null && { vendor_name: po.vendor_name }),
            ...(po.date != null && { date: po.date }),
            ...(po.delivery_date != null && { delivery_date: po.delivery_date }),
            ...(po.total != null && { total: po.total }),
            ...(po.line_items != null && {
                line_items: po.line_items.map((lineItem) => {
                    const rate = lineItem.rate != null ? lineItem.rate : lineItem.purchase_rate;
                    return {
                        ...(lineItem.line_item_id != null && { line_item_id: lineItem.line_item_id }),
                        ...(lineItem.item_id != null && { item_id: lineItem.item_id }),
                        ...(lineItem.name != null && { name: lineItem.name }),
                        ...(lineItem.description != null && { description: lineItem.description }),
                        ...(rate != null && { rate }),
                        ...(lineItem.quantity != null && { quantity: lineItem.quantity }),
                        ...(lineItem.unit != null && { unit: lineItem.unit })
                    };
                })
            })
        };
    }
});

export type NangoActionLocal = Parameters<(typeof action)['exec']>[0];
export default action;
