// ---------------------------
// This file was generated by Nango (v0.64.1)
// You can version this file
// ---------------------------

export interface ActionInput_unanet_createlead {
  federalAgency: {  city: string;
  state: string;
  country: string;
  zip: string;
  companyId: number;
  name: string;
  externalId: string;
  acronym: string;
  address1: string;
  address2: string;
  address3: string;
  isHeadquarters: boolean;
  parentCompanyId: number;
  parentCompanyName: string;
  childCount: number;
  addrLat: number;
  addrLong: number;};
  name: string;
  dueDate: string;
  postedDate: string;
  solicitationNumber: string;
  naicsCategory: string | string[];
  city: string;
  state: string;
  country: string;
  description: string;
};

export interface ActionOutput_unanet_createlead {
  federalAgency: {  city: string;
  state: string;
  country: string;
  zip: string;
  companyId: number;
  name: string;
  externalId: string;
  acronym: string;
  address1: string;
  address2: string;
  address3: string;
  isHeadquarters: boolean;
  parentCompanyId: number;
  parentCompanyName: string;
  childCount: number;
  addrLat: number;
  addrLong: number;};
  name: string;
  dueDate: string;
  postedDate: string;
  solicitationNumber: string;
  naicsCategory: string | string[];
  city: string;
  state: string;
  country: string;
  description: string;
  createdAt: string;
  updatedAt: string;
  id: string;
};

export interface ActionInput_unanet_updatelead {
  federalAgency: {  city: string;
  state: string;
  country: string;
  zip: string;
  companyId: number;
  name: string;
  externalId: string;
  acronym: string;
  address1: string;
  address2: string;
  address3: string;
  isHeadquarters: boolean;
  parentCompanyId: number;
  parentCompanyName: string;
  childCount: number;
  addrLat: number;
  addrLong: number;};
  name: string;
  dueDate: string;
  postedDate: string;
  solicitationNumber: string;
  naicsCategory: string | string[];
  city: string;
  state: string;
  country: string;
  description: string;
  id: string;
};

export interface ActionOutput_unanet_updatelead {
  federalAgency: {  city: string;
  state: string;
  country: string;
  zip: string;
  companyId: number;
  name: string;
  externalId: string;
  acronym: string;
  address1: string;
  address2: string;
  address3: string;
  isHeadquarters: boolean;
  parentCompanyId: number;
  parentCompanyName: string;
  childCount: number;
  addrLat: number;
  addrLong: number;};
  name: string;
  dueDate: string;
  postedDate: string;
  solicitationNumber: string;
  naicsCategory: string | string[];
  city: string;
  state: string;
  country: string;
  description: string;
  createdAt: string;
  updatedAt: string;
  id: string;
};

/** @deprecated It is recommended to use a Model */
export type ActionInput_unanet_getleads = void

export interface ActionOutput_unanet_getleads {
  federalAgency: {  city: string;
  state: string;
  country: string;
  zip: string;
  companyId: number;
  name: string;
  externalId: string;
  acronym: string;
  address1: string;
  address2: string;
  address3: string;
  isHeadquarters: boolean;
  parentCompanyId: number;
  parentCompanyName: string;
  childCount: number;
  addrLat: number;
  addrLong: number;};
  name: string;
  dueDate: string;
  postedDate: string;
  solicitationNumber: string;
  naicsCategory: string | string[];
  city: string;
  state: string;
  country: string;
  description: string;
  createdAt: string;
  updatedAt: string;
  id: string;
};

export interface ActionInput_unanet_getschema {
  name: string;
};

export interface ActionOutput_unanet_getschema {
  PropertyName: string;
  Group: string | null;
  Label: string;
  Description: string | null;
  Enabled: boolean;
  ReadOnly: boolean;
  Required: boolean;
  DefaultValue: string | null;
  DataType: number;
  MaxLength: number | null;
  UnicodeSupported: boolean;
  Searchable: boolean;
  ArrayType: string | null;
  IsPrimaryKey: boolean;
  IsExternalId: boolean;
  ObjectEndpoint: string | null;
  IsHidden: boolean;
  IsIncludedInResponse: boolean;
  SchemaEndpoint: string | null;
  SortOrder: number;
  CustomSort: boolean;
};

export interface ActionInput_unanet_getcompany {
  name: string;
};

export interface ActionOutput_unanet_getcompany {
  0: {  name: string;
  externalId: string;
  federalAgency: {  city: string;
  state: string;
  country: string;
  zip: string;
  companyId: number;
  name: string;
  externalId: string;
  acronym: string;
  address1: string;
  address2: string;
  address3: string;
  isHeadquarters: boolean;
  parentCompanyId: number;
  parentCompanyName: string;
  childCount: number;
  addrLat: number;
  addrLong: number;};
  shortName: string;
  description: string;
  id: string;};
  1: null;
};

export interface ActionInput_unanet_createcompany {
  name: string;
  federalAgency: {  city: string;
  state: string;
  country: string;
  zip: string;
  companyId: number;
  name: string;
  externalId: string;
  acronym: string;
  address1: string;
  address2: string;
  address3: string;
  isHeadquarters: boolean;
  parentCompanyId: number;
  parentCompanyName: string;
  childCount: number;
  addrLat: number;
  addrLong: number;};
};

export interface ActionOutput_unanet_createcompany {
  name: string;
  externalId: string;
  federalAgency: {  city: string;
  state: string;
  country: string;
  zip: string;
  companyId: number;
  name: string;
  externalId: string;
  acronym: string;
  address1: string;
  address2: string;
  address3: string;
  isHeadquarters: boolean;
  parentCompanyId: number;
  parentCompanyName: string;
  childCount: number;
  addrLat: number;
  addrLong: number;};
  shortName: string;
  description: string;
  id: string;
};

export interface ActionInput_unanet_createopportunity {
  city: string;
  state: string;
  country: string;
  zip: string;
  name: string;
  description: string;
  id: string;
  externalId: string;
  dueDate: string;
  federalAgency: {  city: string;
  state: string;
  country: string;
  zip: string;
  companyId: number;
  name: string;
  externalId: string;
  acronym: string;
  address1: string;
  address2: string;
  address3: string;
  isHeadquarters: boolean;
  parentCompanyId: number;
  parentCompanyName: string;
  childCount: number;
  addrLat: number;
  addrLong: number;};
  stage: string;
  active: boolean;
};

export interface ActionOutput_unanet_createopportunity {
  city: string;
  state: string;
  country: string;
  zip: string;
  name: string;
  description: string;
  id: string;
  externalId: string;
  dueDate: string;
  federalAgency: {  city: string;
  state: string;
  country: string;
  zip: string;
  companyId: number;
  name: string;
  externalId: string;
  acronym: string;
  address1: string;
  address2: string;
  address3: string;
  isHeadquarters: boolean;
  parentCompanyId: number;
  parentCompanyName: string;
  childCount: number;
  addrLat: number;
  addrLong: number;};
  stage: string;
  active: boolean;
};

export interface ActionInput_unanet_createcontact {
  id: string;
  firstName: string;
  lastName: string;
  federalAgency: {  city: string;
  state: string;
  country: string;
  zip: string;
  companyId: number;
  name: string;
  externalId: string;
  acronym: string;
  address1: string;
  address2: string;
  address3: string;
  isHeadquarters: boolean;
  parentCompanyId: number;
  parentCompanyName: string;
  childCount: number;
  addrLat: number;
  addrLong: number;};
  position: string;
  emailAddress: string;
  phone: string;
  fax: string;
};

export interface ActionOutput_unanet_createcontact {
  id: string;
  firstName: string;
  lastName: string;
  federalAgency: {  city: string;
  state: string;
  country: string;
  zip: string;
  companyId: number;
  name: string;
  externalId: string;
  acronym: string;
  address1: string;
  address2: string;
  address3: string;
  isHeadquarters: boolean;
  parentCompanyId: number;
  parentCompanyName: string;
  childCount: number;
  addrLat: number;
  addrLong: number;};
  position: string;
  emailAddress: string;
  phone: string;
  fax: string;
};

/** @deprecated It is recommended to use a Model */
export type ActionInput_unanet_liststages = void

export interface ActionOutput_unanet_liststages {
  stages: (number | string | string)[];
};
