export interface ActionInput_unanet_createcompany {
  name: string;
  federalAgency: {  city?: string | undefined;
  state?: string | undefined;
  country?: string | undefined;
  zip?: string | undefined;
  companyId?: number | undefined;
  name: string;
  externalId?: string | undefined;
  acronym?: string | undefined;
  address1?: string | undefined;
  address2?: string | undefined;
  address3?: string | undefined;
  isHeadquarters?: boolean | undefined;
  parentCompanyId?: number | undefined;
  parentCompanyName?: string | undefined;
  childCount?: number | undefined;
  addrLat?: number | undefined;
  addrLong?: number | undefined;};
};

export interface ActionOutput_unanet_createcompany {
  name: string;
  externalId: string;
  federalAgency?: {  city?: string | undefined;
  state?: string | undefined;
  country?: string | undefined;
  zip?: string | undefined;
  companyId?: number | undefined;
  name: string;
  externalId?: string | undefined;
  acronym?: string | undefined;
  address1?: string | undefined;
  address2?: string | undefined;
  address3?: string | undefined;
  isHeadquarters?: boolean | undefined;
  parentCompanyId?: number | undefined;
  parentCompanyName?: string | undefined;
  childCount?: number | undefined;
  addrLat?: number | undefined;
  addrLong?: number | undefined;};
  shortName: string;
  description: string;
  id?: string | undefined;
};

export interface ActionInput_unanet_createcontact {
  id?: string | undefined;
  firstName: string;
  lastName: string;
  federalAgency: {  city?: string | undefined;
  state?: string | undefined;
  country?: string | undefined;
  zip?: string | undefined;
  companyId?: number | undefined;
  name: string;
  externalId?: string | undefined;
  acronym?: string | undefined;
  address1?: string | undefined;
  address2?: string | undefined;
  address3?: string | undefined;
  isHeadquarters?: boolean | undefined;
  parentCompanyId?: number | undefined;
  parentCompanyName?: string | undefined;
  childCount?: number | undefined;
  addrLat?: number | undefined;
  addrLong?: number | undefined;};
  position: string;
  emailAddress: string;
  phone: string;
  fax: string;
};

export interface ActionOutput_unanet_createcontact {
  id?: string | undefined;
  firstName: string;
  lastName: string;
  federalAgency: {  city?: string | undefined;
  state?: string | undefined;
  country?: string | undefined;
  zip?: string | undefined;
  companyId?: number | undefined;
  name: string;
  externalId?: string | undefined;
  acronym?: string | undefined;
  address1?: string | undefined;
  address2?: string | undefined;
  address3?: string | undefined;
  isHeadquarters?: boolean | undefined;
  parentCompanyId?: number | undefined;
  parentCompanyName?: string | undefined;
  childCount?: number | undefined;
  addrLat?: number | undefined;
  addrLong?: number | undefined;};
  position: string;
  emailAddress: string;
  phone: string;
  fax: string;
};

export interface ActionInput_unanet_createlead {
  federalAgency: {  city?: string | undefined;
  state?: string | undefined;
  country?: string | undefined;
  zip?: string | undefined;
  companyId?: number | undefined;
  name: string;
  externalId?: string | undefined;
  acronym?: string | undefined;
  address1?: string | undefined;
  address2?: string | undefined;
  address3?: string | undefined;
  isHeadquarters?: boolean | undefined;
  parentCompanyId?: number | undefined;
  parentCompanyName?: string | undefined;
  childCount?: number | undefined;
  addrLat?: number | undefined;
  addrLong?: number | undefined;};
  name: string;
  dueDate: string;
  postedDate: string;
  solicitationNumber: string;
  naicsCategory: string | string[];
  city: string;
  state: string;
  country: string;
  description: string;
};

export interface ActionOutput_unanet_createlead {
  federalAgency: {  city?: string | undefined;
  state?: string | undefined;
  country?: string | undefined;
  zip?: string | undefined;
  companyId?: number | undefined;
  name: string;
  externalId?: string | undefined;
  acronym?: string | undefined;
  address1?: string | undefined;
  address2?: string | undefined;
  address3?: string | undefined;
  isHeadquarters?: boolean | undefined;
  parentCompanyId?: number | undefined;
  parentCompanyName?: string | undefined;
  childCount?: number | undefined;
  addrLat?: number | undefined;
  addrLong?: number | undefined;};
  name: string;
  dueDate: string;
  postedDate: string;
  solicitationNumber: string;
  naicsCategory: string | string[];
  city: string;
  state: string;
  country: string;
  description: string;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  id: string;
};

export interface ActionInput_unanet_createopportunity {
  city?: string | undefined;
  state?: string | undefined;
  country?: string | undefined;
  zip?: string | undefined;
  name: string;
  description: string;
  id?: string | undefined;
  externalId: string;
  dueDate: string;
  federalAgency: {  city?: string | undefined;
  state?: string | undefined;
  country?: string | undefined;
  zip?: string | undefined;
  companyId?: number | undefined;
  name: string;
  externalId?: string | undefined;
  acronym?: string | undefined;
  address1?: string | undefined;
  address2?: string | undefined;
  address3?: string | undefined;
  isHeadquarters?: boolean | undefined;
  parentCompanyId?: number | undefined;
  parentCompanyName?: string | undefined;
  childCount?: number | undefined;
  addrLat?: number | undefined;
  addrLong?: number | undefined;};
  stage: string;
  active: boolean;
};

export interface ActionOutput_unanet_createopportunity {
  city?: string | undefined;
  state?: string | undefined;
  country?: string | undefined;
  zip?: string | undefined;
  name: string;
  description: string;
  id?: string | undefined;
  externalId: string;
  dueDate: string;
  federalAgency: {  city?: string | undefined;
  state?: string | undefined;
  country?: string | undefined;
  zip?: string | undefined;
  companyId?: number | undefined;
  name: string;
  externalId?: string | undefined;
  acronym?: string | undefined;
  address1?: string | undefined;
  address2?: string | undefined;
  address3?: string | undefined;
  isHeadquarters?: boolean | undefined;
  parentCompanyId?: number | undefined;
  parentCompanyName?: string | undefined;
  childCount?: number | undefined;
  addrLat?: number | undefined;
  addrLong?: number | undefined;};
  stage: string;
  active: boolean;
};

export interface ActionInput_unanet_getcompany {
  name: string;
};

export interface ActionOutput_unanet_getcompany {
  0: {  name: string;
  externalId: string;
  federalAgency?: {  city?: string | undefined;
  state?: string | undefined;
  country?: string | undefined;
  zip?: string | undefined;
  companyId?: number | undefined;
  name: string;
  externalId?: string | undefined;
  acronym?: string | undefined;
  address1?: string | undefined;
  address2?: string | undefined;
  address3?: string | undefined;
  isHeadquarters?: boolean | undefined;
  parentCompanyId?: number | undefined;
  parentCompanyName?: string | undefined;
  childCount?: number | undefined;
  addrLat?: number | undefined;
  addrLong?: number | undefined;};
  shortName: string;
  description: string;
  id?: string | undefined;};
  1: null;
};

export type ActionInput_unanet_getleads = void

export interface ActionOutput_unanet_getleads {
  0: {  federalAgency: {  city?: string | undefined;
  state?: string | undefined;
  country?: string | undefined;
  zip?: string | undefined;
  companyId?: number | undefined;
  name: string;
  externalId?: string | undefined;
  acronym?: string | undefined;
  address1?: string | undefined;
  address2?: string | undefined;
  address3?: string | undefined;
  isHeadquarters?: boolean | undefined;
  parentCompanyId?: number | undefined;
  parentCompanyName?: string | undefined;
  childCount?: number | undefined;
  addrLat?: number | undefined;
  addrLong?: number | undefined;};
  name: string;
  dueDate: string;
  postedDate: string;
  solicitationNumber: string;
  naicsCategory: string | string[];
  city: string;
  state: string;
  country: string;
  description: string;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  id: string;};
};

export interface ActionInput_unanet_getschema {
  name: string;
};

export interface ActionOutput_unanet_getschema {
  0: {  PropertyName: string;
  Group: string | null;
  Label: string;
  Description: string | null;
  Enabled: boolean;
  ReadOnly: boolean;
  Required: boolean;
  DefaultValue: string | null;
  DataType: number;
  MaxLength: number | null;
  UnicodeSupported: boolean;
  Searchable: boolean;
  ArrayType: string | null;
  IsPrimaryKey: boolean;
  IsExternalId: boolean;
  ObjectEndpoint: string | null;
  IsHidden: boolean;
  IsIncludedInResponse: boolean;
  SchemaEndpoint: string | null;
  SortOrder: number;
  CustomSort: boolean;};
};

export type ActionInput_unanet_liststages = void

export interface ActionOutput_unanet_liststages {
  stages: ({  id: number;
  name: string;
  status: string;})[];
};

export interface ActionInput_unanet_updatelead {
  federalAgency: {  city?: string | undefined;
  state?: string | undefined;
  country?: string | undefined;
  zip?: string | undefined;
  companyId?: number | undefined;
  name: string;
  externalId?: string | undefined;
  acronym?: string | undefined;
  address1?: string | undefined;
  address2?: string | undefined;
  address3?: string | undefined;
  isHeadquarters?: boolean | undefined;
  parentCompanyId?: number | undefined;
  parentCompanyName?: string | undefined;
  childCount?: number | undefined;
  addrLat?: number | undefined;
  addrLong?: number | undefined;};
  name: string;
  dueDate: string;
  postedDate: string;
  solicitationNumber: string;
  naicsCategory: string | string[];
  city: string;
  state: string;
  country: string;
  description: string;
  id: string;
};

export interface ActionOutput_unanet_updatelead {
  federalAgency: {  city?: string | undefined;
  state?: string | undefined;
  country?: string | undefined;
  zip?: string | undefined;
  companyId?: number | undefined;
  name: string;
  externalId?: string | undefined;
  acronym?: string | undefined;
  address1?: string | undefined;
  address2?: string | undefined;
  address3?: string | undefined;
  isHeadquarters?: boolean | undefined;
  parentCompanyId?: number | undefined;
  parentCompanyName?: string | undefined;
  childCount?: number | undefined;
  addrLat?: number | undefined;
  addrLong?: number | undefined;};
  name: string;
  dueDate: string;
  postedDate: string;
  solicitationNumber: string;
  naicsCategory: string | string[];
  city: string;
  state: string;
  country: string;
  description: string;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  id: string;
};
