// Generated by ts-to-zod
import { z } from "zod";

export const idEntitySchema = z.object({
  id: z.string(),
});

export const successResponseSchema = z.object({
  success: z.boolean(),
});

export const actionResponseErrorSchema = z.object({
  message: z.string(),
});

export const userSchema = z.object({
  id: z.string(),
  firstName: z.string(),
  lastName: z.string(),
  email: z.string(),
});

export const createUserSchema = z.object({
  firstName: z.string(),
  lastName: z.string(),
  email: z.string(),
});

export const billCreateUserSchema = z.object({
  firstName: z.string(),
  lastName: z.string(),
  email: z.string(),
  roleId: z.string(),
  acceptTermsOfService: z.boolean(),
});
