// ---------------------------
// This file was generated by Nango (v0.64.1)
// You can version this file
// ---------------------------

export interface SyncMetadata_workable_candidates {
};

export interface WorkableCandidate {
  id: string;
  name: string;
  firstname: string;
  lastname: string;
  headline: string;
  account: {  subdomain: string;
  name: string;};
  job: {  shortcode: string;
  title: string;};
  stage: string;
  disqualified: boolean;
  disqualification_reason: string;
  hired_at: Date;
  sourced: boolean;
  profile_url: string;
  address: string;
  phone: string;
  email: string;
  domain: string;
  created_at: Date;
  updated_at: Date;
};

export interface SyncMetadata_workable_candidatesactivities {
};

export interface WorkableCandidateActivity {
  id: string;
  action: string;
  stage_name: string;
  created_at: Date;
  body: string;
  member: {  id: string;
  name: string;};
  rating: {};
};

export interface SyncMetadata_workable_candidatesoffer {
};

export interface WorkableCandidateOffer {
  id: string;
  candidate: {  id: string;
  name: string;};
  created_at: Date;
  document_variables: any[];
  documents: any[];
  state: string;
};

export interface SyncMetadata_workable_jobs {
};

export interface WorkableJob {
  id: string;
  title: string;
  full_title: string;
  shortcode: string;
  code: string;
  state: string;
  sample: boolean;
  department: string;
  department_hierarchy: any[];
  url: string;
  application_url: string;
  shortlink: string;
  location: {  location_str: string;
  country: string;
  country_code: string;
  region: string;
  region_code: string;
  city: string;
  zip_code: string;
  telecommuting: boolean;
  workplace_type: string;};
  locations: any[];
  salary: {  salary_from: number;
  salary_to: number;
  salary_currency: string;};
  created_at: Date;
};

export interface SyncMetadata_workable_jobscandidates {
};

export interface WorkableJobsCandidate {
  id: string;
  name: string;
  firstname: string;
  lastname: string;
  headline: string;
  account: {  subdomain: string;
  name: string;};
  job: {  shortcode: string;
  title: string;};
  stage: string;
  disqualified: boolean;
  disqualification_reason: string;
  hired_at: Date;
  sourced: boolean;
  profile_url: string;
  address: string;
  phone: string;
  email: string;
  domain: string;
  created_at: Date;
  updated_at: Date;
};

export interface SyncMetadata_workable_jobsquestions {
};

export interface WorkableJobQuestion {
  id: string;
  body: string;
  type: string;
  required: boolean;
  single_answer: boolean;
  choices: {  id: string;
  body: string;};
  supported_file_types: any[];
  max_file_size: number;
};

export interface SyncMetadata_workable_members {
};

export interface WorkableMember {
  id: string;
  name: string;
  headline: string;
  email: string;
  role: string;
};

export interface ActionInput_workable_createcandidate {
  shortcode: string;
  candidate: {  name: string;
  firstname: string;
  lastname: string;
  email: string;
  headline: string;
  summary: string;
  address: string;
  phone: string;
  cover_letter: string;
  education_entries: (string | string | string | string | string)[];
  experience_entries: (string | string | string | string | boolean | string | string)[];
  answers: (string | string | string[] | boolean | string | number | {  name: string;
  data: string;})[];
  skills: string[];
  tags: string[];
  disqualified: boolean;
  disqualification_reason: string;
  disqualified_at: string;
  social_profiles: (string | string | string | string)[];};
  domain: string;
  recruiter_key: string;
};

export interface ActionOutput_workable_createcandidate {
  status: string;
  candidate: {  id: string;
  name: string;
  firstname: string;
  lastname: string;
  headline: string;
  account: {  subdomain: string;
  name: string;};
  job: {  shortcode: string;
  title: string;};
  stage: string;
  disqualified: boolean;
  disqualification_reason: string;
  hired_at: Date;
  sourced: boolean;
  profile_url: string;
  address: string;
  phone: string;
  email: string;
  domain: string;
  created_at: Date;
  updated_at: Date;
  image_url: string;
  outbound_mailbox: string;
  uploader_id: string;
  cover_letter: string;
  summary: string;
  education_entries: any[];
  experience_entries: any[];
  skills: any[];
  answers: any[];
  resume_url: string;
  tags: any[];
  location: {  location_str: string;
  country: string;
  country_code: string;
  region: string;
  region_code: string;
  city: string;
  zip_code: string;};};
};

export interface ActionInput_workable_createcomment {
  id: string;
  member_id: string;
  comment: {  body: string;
  policy: string[];
  attachment: {  name: string;
  data: string;};};
};

export interface ActionOutput_workable_createcomment {
  id: string;
};
