// ---------------------------
// This file was generated by Nango (v0.68.1)
// You can version this file
// ---------------------------

export interface SyncMetadata_keeper_scim_users {
};

export interface User {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
};

export interface ActionInput_keeper_scim_createuser {
  firstName: string;
  lastName: string;
  email: string;
  active?: boolean | undefined;
  externalId?: string | undefined;
  phoneNumbers: ({  type: 'work' | 'mobile' | 'other';
  value: string;})[];
  photos: ({  type: 'photo' | 'thumbnail';
  value: string;})[];
  addresses: ({  type: 'work';
  streetAddress?: string | undefined;
  locality?: string | undefined;
  region?: string | undefined;
  postalCode?: string | undefined;
  country?: string | undefined;})[];
  title?: string | undefined;
};

export interface ActionOutput_keeper_scim_createuser {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
};

export interface ActionInput_keeper_scim_deleteuser {
  id: string;
};

export interface ActionOutput_keeper_scim_deleteuser {
  success: boolean;
};
