// ---------------------------
// This file was generated by Nango (v0.57.3)
// You can version this file
// ---------------------------

export interface BitdefenderCompany {
    id: string;
    name: string;
    type: number;
    country: string | undefined;
    createdAt: string;
    subscribedServices: { endpoint: boolean; exchange: boolean; network: boolean; sos: boolean };
    raw_json: string;
}

export interface BitdefenderEndpoint {
    id: string;
    name: string;
    fqdn: string;
    groupId: string;
    isManaged: boolean;
    machineType: number;
    os: { type: string; version: string; displayName: string };
    ip: string[];
    macs: string[];
    ssid: string | undefined;
    label: string | undefined;
    state: {
        managedWithClient: boolean;
        managedWithoutClient: boolean;
        pendingUninstall: boolean;
        needsReboot: boolean;
        canManage: boolean;
        agentVersion: string;
        lastUpdate: string;
        online: boolean;
    };
    raw_json: string;
}

export interface BitdefenderQuarantineItem {
    id: string;
    name: string;
    hash: string;
    filePath: string;
    endpointId: string;
    endpointName: string;
    date: string;
    malwareType: string;
    malwareName: string;
    moduleName: string;
    impact: number;
    size: number;
    isPasswordProtectedArchive: boolean;
    restored: boolean;
    deleted: boolean;
    raw_json: string;
}

export interface CompanyIdInput {
    id: string;
}

export interface QuarantineItemIdInput {
    id: string;
}

export interface RestoreQuarantineItemOutput {
    success: boolean;
    message: string | undefined;
    raw_json: string;
}
