// ---------------------------
// This file was generated by Nango (v0.58.3)
// You can version this file
// ---------------------------

export interface BitdefenderCompany {
    id: string;
    name: string;
    type: number;
    country: string | undefined;
    subscribedServices: { endpoint: boolean; exchange: boolean; network: boolean; sos: boolean };
}
