// ---------------------------
// This file was generated by Nango (v0.62.0)
// You can version this file
// ---------------------------

export interface Timestamps {
    created_at: string;
    updated_at: string;
}

export interface UtilityAnyType {
    [key: string]: any;
}

export interface Location {
    city?: string;
    country: string;
    state?: string;
}

export interface Candidate {
    id: string;
    object: string;
    uri: string;
    first_name: string;
    middle_name: string | null;
    last_name: string;
    mother_maiden_name: string;
    email: string;
    phone: number;
    zipcode: number;
    dob: string;
    ssn: string;
    driver_license_number: string;
    driver_license_state: string;
    previous_driver_license_number: string;
    previous_driver_license_state: string;
    copy_requested: boolean;
    custom_id: string;
    report_ids: string[];
    geo_ids: string[];
    adjudication: string;
    metadata: UtilityAnyType;
}

export interface CreateCandidate {
    city?: string;
    country: string;
    state?: string;
    first_name: string;
    middle_name?: string;
    no_middle_name?: boolean;
    last_name: string;
    email: string;
    phone: string;
    zipcode: string;
    dob: string;
    ssn: string;
    driver_license_number: string;
    driver_license_state: string;
    work_locations: Location[];
}

export interface BackgroundCheck {
    id: string;
    status: string;
    service_key: string;
    url: string;
    candidate_id: string;
    created_at: string;
    expires_at?: string | undefined;
}

export interface CheckrTriggeredBackgroundCheck {
    created_at: string;
    updated_at: string;
    id: string;
    object: string;
    uri: string;
    invitation_url: string;
    status: string;
    completed_at: string | null;
    deleted_at: string | null;
    package: string;
    candidate_id: string;
    report_id: string | null;
    archived: boolean;
    expires_at?: string;
    archived_info: { time: string; user: { email: string; id: string } };
}

export interface BackgroundCheckParametersInput {
    service_key: string;
}

export interface TriggeredBackgroundCheck {
    created_at: string;
    updated_at: string;
    applicationId: any;
    url: string;
    status: string;
    completed_at: string | null;
    candidate_id: string;
    service_key: string;
    deleted_at: string | null;
}

export interface TriggerBackgroundCheckInput {
    city?: string;
    country: string;
    state?: string;
    service_key: string;
    candidate_id: string;
    node?: string;
    tags?: string[];
}

export interface BackgroundCheckParameters {
    key: string;
    type: string;
    title: string;
    description: string;
    required: boolean;
}

export interface BackgroundCheckParameterResponse {
    parameters: BackgroundCheckParameters[];
}

export interface CheckrScreening {
    type: string;
    subtype: string | null;
}

export interface CheckrService {
    id: string;
    price: number;
    drug_screening_price: number | null;
    enabled_examples: string[];
    requires_observed_drug_test: boolean;
    object: string;
    apply_url: string;
    created_at: string;
    deleted_at: string | null;
    name: string;
    screenings: CheckrScreening[];
    slug: string;
    uri: string;
    node?: string;
}

export interface CheckrServicesResponse {
    services: CheckrService[];
}
