// ---------------------------
// This file was generated by Nango (v0.64.1)
// You can version this file
// ---------------------------

export interface ActionInput_google_sheet_fetchspreadsheet {
  id: string;
};

export interface ActionOutput_google_sheet_fetchspreadsheet {
  spreadsheetId: string;
  properties: {};
  sheets: ()[];
  namedRanges: ()[];
  spreadsheetUrl: string;
  developerMetadata: ()[];
  dataSources: ()[];
  dataSourceSchedules: ()[];
};
