// ---------------------------
// This file was generated by Nango (v0.56.1)
// You can version this file
// ---------------------------

export interface InstantlySetCampaignNameResponse {
    status: string;
}

export interface InstantlySetCampaignNameInput {
    campaign_id: string;
    name: string;
}
