import { z } from 'zod';
import { createAction } from 'nango';
import type { ProxyConfiguration } from 'nango';

const InputSchema = z
    .object({
        identifier: z
            .string()
            .min(1)
            .describe(
                'Email address, numeric contact ID, SMS attribute value, or EXT_ID attribute value of the contact (URL-encoded by the action). Examples: "peggy.rain@example.com", "42"'
            ),
        identifierType: z
            .enum(['email_id', 'phone_id', 'contact_id', 'ext_id', 'whatsapp_id', 'landline_number_id'])
            .optional()
            .describe('How to interpret identifier. Defaults to email_id (for emails), phone_id (for SMS) or contact_id (for IDs) when omitted.')
    })
    .describe('Input for looking up a contact full profile');

const CampaignEventSchema = z.object({
    campaignId: z.number().describe('ID of the campaign that generated the event. Example: 21'),
    eventTime: z.string().describe('UTC date-time of the event (YYYY-MM-DDTHH:mm:ss.SSSZ). Example: "2016-05-03T20:15:13Z"')
});

const ContactStatisticsSchema = z.object({
    clicked: z
        .array(
            z.object({
                campaignId: z.number().describe('ID of the campaign that generated the clicks. Example: 21'),
                links: z
                    .array(
                        z.object({
                            count: z.number().describe('Number of clicks on this link for the campaign'),
                            eventTime: z.string().describe('UTC date-time of the click. Example: "2016-05-03T21:25:01Z"'),
                            ip: z.string().optional().describe('IP address from which the link was clicked'),
                            url: z.string().describe('URL of the clicked link')
                        })
                    )
                    .describe('Links clicked by the contact for the campaign')
            })
        )
        .optional()
        .describe('Clicks generated by the contact'),
    complaints: z.array(CampaignEventSchema).optional().describe('Spam complaints generated by the contact'),
    delivered: z.array(CampaignEventSchema).optional().describe('Campaigns delivered to the contact'),
    hardBounces: z.array(CampaignEventSchema).optional().describe('Hard bounces generated by the contact'),
    messagesSent: z.array(CampaignEventSchema).optional().describe('Campaign messages sent to the contact'),
    opened: z
        .array(
            CampaignEventSchema.extend({
                count: z.number().optional().describe('Number of openings for the campaign'),
                ip: z.string().optional().describe('IP address from which the email was opened')
            })
        )
        .optional()
        .describe('Campaign openings generated by the contact'),
    softBounces: z.array(CampaignEventSchema).optional().describe('Soft bounces generated by the contact'),
    transacAttributes: z.array(z.record(z.string(), z.unknown())).optional().describe('Transactional attributes of the contact'),
    unsubscriptions: z
        .object({
            adminUnsubscription: z
                .array(
                    z.object({
                        eventTime: z.string().describe('UTC date-time of the unsubscription. Example: "2017-01-30T13:56:40Z"'),
                        ip: z.string().optional().describe('IP address from which the contact was unsubscribed')
                    })
                )
                .describe('Unsubscriptions performed by an administrator'),
            userUnsubscription: z
                .array(
                    z.object({
                        campaignId: z.number().nullable().describe('ID of the campaign that generated the unsubscription, when known'),
                        eventTime: z.string().describe('UTC date-time of the unsubscription. Example: "2017-01-30T13:56:40Z"'),
                        ip: z.string().optional().describe('IP address from which the contact unsubscribed')
                    })
                )
                .describe('Unsubscriptions performed by the contact via an unsubscription link')
        })
        .optional()
        .describe('Unsubscription history of the contact')
});

const ContactSchema = z.object({
    id: z.number().describe('Numeric ID of the contact. Example: 42'),
    email: z.string().optional().describe('Email address of the contact. Absent for SMS-only contacts'),
    emailBlacklisted: z.boolean().describe('Whether the contact is blacklisted for email campaigns'),
    smsBlacklisted: z.boolean().describe('Whether the contact is blacklisted for SMS campaigns'),
    whatsappBlacklisted: z.boolean().describe('Whether the contact is blacklisted for WhatsApp campaigns'),
    attributes: z.record(z.string(), z.unknown()).optional().describe('Contact attributes keyed by attribute name (e.g. FIRSTNAME, LASTNAME, SMS)'),
    createdAt: z.string().describe('Creation UTC date-time of the contact (YYYY-MM-DDTHH:mm:ss.SSSZ). Example: "2017-05-02T16:40:31Z"'),
    modifiedAt: z.string().describe('Last modification UTC date-time of the contact (YYYY-MM-DDTHH:mm:ss.SSSZ)'),
    listIds: z.array(z.number()).describe('IDs of the contact lists the contact belongs to'),
    listUnsubscribed: z.array(z.number()).optional().describe('IDs of the contact lists the contact has unsubscribed from'),
    statistics: ContactStatisticsSchema.optional().describe('Campaign engagement statistics of the contact (recent 90 days by default)')
});

const CompanySchema = z.object({
    id: z.string().describe('Unique company ID (24-character hex string). Example: "629475917295261d9b1f4403"'),
    attributes: z.record(z.string(), z.unknown()).optional().describe('Company attributes with values (e.g. name, domain, owner)'),
    linkedContactsIds: z.array(z.number()).optional().describe('IDs of contacts linked to this company'),
    linkedDealsIds: z.array(z.string()).optional().describe('IDs of deals linked to this company')
});

const DealSchema = z.object({
    id: z.string().describe('Unique deal ID (24-character hex string). Example: "629475917295261d9b1f4403"'),
    attributes: z.record(z.string(), z.unknown()).optional().describe('Deal attributes with values (e.g. deal_name, amount, pipeline, deal_stage)'),
    linkedContactsIds: z.array(z.number()).optional().describe('IDs of contacts linked to this deal'),
    linkedCompaniesIds: z.array(z.string()).optional().describe('IDs of companies linked to this deal')
});

const CompaniesResponseSchema = z.object({
    items: z.array(CompanySchema).optional()
});

const DealsResponseSchema = z.object({
    items: z.array(DealSchema).optional()
});

const OutputSchema = z
    .object({
        contact: ContactSchema.describe('The contact record, including attributes, list memberships, blacklist flags and campaign statistics'),
        companies: z.array(CompanySchema).describe('CRM companies linked to the contact. Empty when the contact is linked to no company'),
        deals: z.array(DealSchema).describe('CRM deals linked to the contact. Empty when the contact is linked to no deal')
    })
    .describe('360-degree profile of a contact: the contact record plus its linked CRM companies and deals');

/**
 * @tags: [read]
 * @tagReason: Fetches the contact record plus its linked CRM companies and deals through three read-only GET calls; nothing is created, updated, or deleted.
 * @pitfalls: An identifier that matches no contact fails with a 404 rather than an empty result. EXT_ID, WhatsApp, and landline number identifiers only resolve when identifierType is passed explicitly. Only the first page of linked companies/deals is returned (provider default page size), and campaign statistics cover the recent 90 days by default.
 */
const action = createAction({
    description: 'Get a 360-degree view of a contact: the contact record, its linked CRM companies and its linked CRM deals in one call.',
    version: '1.0.0',
    input: InputSchema,
    output: OutputSchema,

    exec: async (nango, input): Promise<z.infer<typeof OutputSchema>> => {
        const contactConfig: ProxyConfiguration = {
            // https://developers.brevo.com/reference/get-contact-info
            endpoint: `/contacts/${encodeURIComponent(input.identifier)}`,
            params: {
                ...(input.identifierType !== undefined && { identifierType: input.identifierType })
            },
            retries: 3
        };
        const contactResponse = await nango.get(contactConfig);
        const contact = ContactSchema.parse(contactResponse.data);

        const companiesConfig: ProxyConfiguration = {
            // https://developers.brevo.com/reference/get-all-companies
            endpoint: '/companies',
            params: {
                linkedContactsIds: contact.id
            },
            retries: 3
        };
        const dealsConfig: ProxyConfiguration = {
            // https://developers.brevo.com/reference/get-all-deals
            endpoint: '/crm/deals',
            params: {
                'filters[linkedContactsIds]': String(contact.id)
            },
            retries: 3
        };
        const [companiesResponse, dealsResponse] = await Promise.all([nango.get(companiesConfig), nango.get(dealsConfig)]);

        const companies = CompaniesResponseSchema.parse(companiesResponse.data).items ?? [];
        const deals = DealsResponseSchema.parse(dealsResponse.data).items ?? [];

        return { contact, companies, deals };
    }
});

export type NangoActionLocal = Parameters<(typeof action)['exec']>[0];
export default action;
