import { z } from 'zod';
import { createAction } from 'nango';

const InputSchema = z
    .object({
        campaignId: z.number().int().positive().describe('Numeric ID of the SMS campaign to retrieve. Example: 7')
    })
    .describe('Input for retrieving a single Brevo SMS campaign');

const SmsCampaignListSchema = z.object({
    id: z.number().optional().describe('Numeric ID of the contact list. Example: 2'),
    name: z.string().optional().describe('Name of the contact list. Example: "Your first list"')
});

const OutputSchema = z
    .object({
        id: z.number().describe('Numeric ID of the SMS campaign. Example: 7'),
        name: z.string().describe('Name of the SMS campaign'),
        status: z.enum(['draft', 'sent', 'archive', 'queued', 'suspended', 'inProcess']).describe('Current status of the SMS campaign'),
        content: z.string().describe('Text content of the SMS message'),
        sender: z.string().describe('SMS sender name or number shown to recipients. Plain string (e.g. "NangoDev"), not an email-style sender object'),
        createdAt: z
            .string()
            .describe(
                'Date-time at which the campaign was created, as an ISO 8601 timestamp with a provider-determined UTC offset (e.g. "2023-01-20T14:53:02.000+01:00"), not necessarily "Z"/UTC.'
            ),
        modifiedAt: z
            .string()
            .describe(
                'Date-time at which the campaign was last modified, as an ISO 8601 timestamp with a provider-determined UTC offset (e.g. "2023-01-20T14:53:02.000+01:00"), not necessarily "Z"/UTC.'
            ),
        recipients: z
            .object({
                lists: z.array(SmsCampaignListSchema).optional().describe('Recipient contact lists, returned as objects with id and name'),
                exclusionLists: z
                    .array(SmsCampaignListSchema)
                    .optional()
                    .describe('Contact lists excluded from the campaign, returned as objects with id and name')
            })
            .describe('Recipient and exclusion contact lists of the campaign'),
        statistics: z
            .object({
                delivered: z.number().describe('Number of delivered SMS'),
                sent: z.number().describe('Number of sent SMS'),
                processing: z.number().describe('Number of SMS currently being processed'),
                softBounces: z.number().describe('Number of soft-bounced SMS'),
                hardBounces: z.number().describe('Number of hard-bounced SMS'),
                unsubscriptions: z.number().describe('Number of unsubscriptions generated by the campaign'),
                answered: z.number().describe('Number of replies to the SMS')
            })
            .describe('Delivery and engagement statistics of the campaign'),
        scheduledAt: z
            .string()
            .optional()
            .describe('UTC date-time at which the campaign is scheduled (YYYY-MM-DDTHH:mm:ss.SSSZ). Empty string if not scheduled'),
        sentDate: z.string().optional().describe('UTC date-time at which the campaign was sent (YYYY-MM-DDTHH:mm:ss.SSSZ). Only present when status is "sent"'),
        organisationPrefix: z.string().optional().describe('Brand-name prefix added before the message content. Empty string if not set'),
        unsubscribeInstruction: z.string().optional().describe('Unsubscribe instructions appended to the message content. Empty string if not set'),
        tags: z.array(z.string()).optional().describe('Tags (labels) associated with the campaign')
    })
    .describe('A Brevo SMS campaign with its content, recipients, and delivery statistics');

type SmsCampaign = z.infer<typeof OutputSchema>;

/**
 * @tags: [read]
 * @tagReason: Performs a single read-only GET of an SMS campaign and changes nothing on the provider.
 * @pitfalls: An unknown campaignId fails with a 404 not-found error rather than returning an empty result. Recipient and exclusion lists are returned as {id, name} objects on this single-campaign view, whereas Brevo's SMS campaigns list endpoint returns plain list IDs.
 */
const action = createAction({
    description: 'Retrieve a single SMS campaign by ID, including its content, recipients, status, and delivery statistics.',
    version: '1.0.0',
    input: InputSchema,
    output: OutputSchema,

    exec: async (nango, input): Promise<SmsCampaign> => {
        // https://developers.brevo.com/reference/get-sms-campaign
        const response = await nango.get<SmsCampaign>({
            endpoint: `/smsCampaigns/${input.campaignId}`,
            retries: 3
        });

        const campaign = OutputSchema.parse(response.data);

        return campaign;
    }
});

export type NangoActionLocal = Parameters<(typeof action)['exec']>[0];
export default action;
