import { z } from 'zod';
import { createAction } from 'nango';

const InputSchema = z
    .object({
        identifier: z.string().min(1).describe('Email address or numeric ID of the contact to retrieve. Example: "peggy.rain@example.com" or "42".')
    })
    .describe('Input for fetching a single Brevo contact.');

const StatisticsEventSchema = z.object({
    campaignId: z.number().describe('ID of the campaign which generated the event.'),
    eventTime: z.string().describe('UTC date-time of the event (YYYY-MM-DDTHH:mm:ss.SSSZ).')
});

const StatisticsSchema = z
    .object({
        messagesSent: z.array(StatisticsEventSchema).optional().describe('Listing of the campaigns sent to the contact.'),
        hardBounces: z.array(StatisticsEventSchema).optional().describe('Listing of the hard bounces generated by the contact.'),
        softBounces: z.array(StatisticsEventSchema).optional().describe('Listing of the soft bounces generated by the contact.'),
        delivered: z.array(StatisticsEventSchema).optional().describe('Listing of the campaigns delivered to the contact.'),
        complaints: z.array(StatisticsEventSchema).optional().describe('Listing of the complaints generated by the contact.'),
        clicked: z
            .array(
                z.object({
                    campaignId: z.number().describe('ID of the campaign which generated the event.'),
                    links: z
                        .array(
                            z.object({
                                count: z.number().describe('Number of clicks on this link for the campaign.'),
                                eventTime: z.string().describe('UTC date-time of the event (YYYY-MM-DDTHH:mm:ss.SSSZ).'),
                                ip: z.string().describe('IP from which the contact clicked on the link.'),
                                url: z.string().describe('URL of the clicked link.')
                            })
                        )
                        .describe('Listing of the clicked links for the campaign.')
                })
            )
            .optional()
            .describe('Listing of the clicks generated by the contact.'),
        opened: z
            .array(
                z.object({
                    campaignId: z.number().describe('ID of the campaign which generated the event.'),
                    count: z.number().describe('Number of openings for the campaign.'),
                    eventTime: z.string().describe('UTC date-time of the event (YYYY-MM-DDTHH:mm:ss.SSSZ).'),
                    ip: z.string().describe('IP from which the contact opened the email.')
                })
            )
            .optional()
            .describe('Listing of the openings generated by the contact.'),
        unsubscriptions: z
            .object({
                adminUnsubscription: z
                    .array(
                        z.object({
                            eventTime: z.string().describe('UTC date-time of the event (YYYY-MM-DDTHH:mm:ss.SSSZ).'),
                            ip: z.string().optional().describe('IP from which the contact was unsubscribed.')
                        })
                    )
                    .describe('Listing of unsubscriptions performed by the administrator.'),
                userUnsubscription: z
                    .array(
                        z.object({
                            campaignId: z.number().nullable().describe('ID of the campaign which generated the event.'),
                            eventTime: z.string().describe('UTC date-time of the event (YYYY-MM-DDTHH:mm:ss.SSSZ).'),
                            ip: z.string().optional().describe('IP from which the contact unsubscribed.')
                        })
                    )
                    .describe('Listing of unsubscriptions made via the unsubscription link in a campaign.')
            })
            .optional()
            .describe('Listing of the unsubscriptions for the contact.'),
        transacAttributes: z.array(z.record(z.string(), z.unknown())).optional().describe('Listing of the transactional attributes for the contact.')
    })
    .describe('Campaign statistics of the contact for the recent 90 days.');

const ConsentGroupSchema = z.object({
    id: z.number().describe('ID of the consent group.'),
    status: z.enum(['subscribed', 'unsubscribed']).describe("The contact's subscription status within this consent group.")
});

const OutputSchema = z
    .object({
        id: z.number().describe('ID of the contact.'),
        email: z.string().optional().describe('Email address of the contact. Absent when the contact has no email attribute (e.g. SMS-only contacts).'),
        emailBlacklisted: z.boolean().describe('Blacklist status for email campaigns (true=blacklisted, false=not blacklisted).'),
        smsBlacklisted: z.boolean().describe('Blacklist status for SMS campaigns (true=blacklisted, false=not blacklisted).'),
        whatsappBlacklisted: z.boolean().describe('Blacklist status for WhatsApp campaigns (true=blacklisted, false=not blacklisted).'),
        createdAt: z
            .string()
            .describe(
                'Date-time at which the contact was created, as an ISO 8601 timestamp with a provider-determined UTC offset (e.g. "2017-05-02T16:40:31+02:00"), not necessarily "Z"/UTC.'
            ),
        modifiedAt: z
            .string()
            .describe(
                'Date-time at which the contact was last modified, as an ISO 8601 timestamp with a provider-determined UTC offset (e.g. "2017-05-02T16:40:31+02:00"), not necessarily "Z"/UTC.'
            ),
        listIds: z.array(z.number()).describe('IDs of the lists the contact belongs to.'),
        listUnsubscribed: z.array(z.number()).nullable().optional().describe('IDs of the lists the contact has unsubscribed from.'),
        attributes: z.record(z.string(), z.unknown()).describe('Set of attributes of the contact, keyed by attribute name.'),
        subscriptions: z
            .record(z.string(), z.unknown())
            .optional()
            .describe('Subscription preferences of the contact, keyed by subscription type. Empty when the contact has no subscriptions.'),
        consentGroups: z.array(ConsentGroupSchema).optional().describe('Consent groups the contact belongs to, with their subscription status.'),
        statistics: StatisticsSchema
    })
    .describe('A single Brevo contact with its attributes, list memberships and campaign statistics.');

/**
 * @tags: [read]
 * @tagReason: Fetches a single contact with a read-only GET and performs no provider mutations.
 * @pitfalls: Statistics cover only the recent 90 days; older campaign events are not returned. Contacts without an email attribute (e.g. SMS-only contacts) return no email field.
 */
const action = createAction({
    description: 'Retrieve a single contact by email or numeric ID.',
    version: '1.0.0',
    input: InputSchema,
    output: OutputSchema,

    exec: async (nango, input): Promise<z.infer<typeof OutputSchema>> => {
        const response = await nango.get({
            // https://developers.brevo.com/reference/getcontactinfo-1
            endpoint: `/contacts/${encodeURIComponent(input.identifier)}`,
            retries: 3
        });

        return OutputSchema.parse(response.data);
    }
});

export type NangoActionLocal = Parameters<(typeof action)['exec']>[0];
export default action;
