// ---------------------------
// This file was generated by Nango (v0.57.3)
// You can version this file
// ---------------------------

export interface User {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
};
