// ---------------------------
// This file was generated by Nango (v0.66.0)
// You can version this file
// ---------------------------

export interface SyncMetadata_oracle_hcm_unifiedemployees {
};

export interface StandardEmployee {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  displayName: string;
  employeeNumber?: string | undefined;
  title?: string | undefined;
  department: {  id: string;
  name: string;};
  employmentType: 'FULL_TIME' | 'PART_TIME' | 'CONTRACTOR' | 'INTERN' | 'TEMPORARY' | 'OTHER';
  employmentStatus: 'ACTIVE' | 'TERMINATED' | 'ON_LEAVE' | 'SUSPENDED' | 'PENDING';
  startDate: string;
  terminationDate?: string | undefined;
  manager?: {  id?: string | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
  email?: string | undefined;} | undefined;
  workLocation: {  name: string;
  type: 'OFFICE' | 'REMOTE' | 'HYBRID';
  primaryAddress?: {  street?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  country?: string | undefined;
  postalCode?: string | undefined;
  type: 'WORK' | 'HOME';} | undefined;};
  addresses?: ({  street?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  country?: string | undefined;
  postalCode?: string | undefined;
  type: 'WORK' | 'HOME';})[] | undefined;
  phones?: ({  type: 'WORK' | 'HOME' | 'MOBILE';
  number: string;})[] | undefined;
  emails?: ({  type: 'WORK' | 'PERSONAL';
  address: string;})[] | undefined;
  providerSpecific: {};
  createdAt: string;
  updatedAt: string;
};

export interface SyncMetadata_oracle_hcm_employees {
};

export interface Employee {
  id: string;
  personNumber?: string | undefined;
  displayName?: string | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
  workEmail?: string | undefined;
  title?: string | undefined;
  departmentId?: string | undefined;
  departmentName?: string | undefined;
  assignmentStatusType?: string | undefined;
  startDate?: string | undefined;
  terminationDate?: string | undefined;
  managerId?: string | undefined;
  managerName?: string | undefined;
  workLocationName?: string | undefined;
  workLocationType?: string | undefined;
  correspondenceLanguage?: string | null | undefined;
  bloodType?: string | null | undefined;
  dateOfBirth?: string | null | undefined;
  dateOfDeath?: string | null | undefined;
  countryOfBirth?: string | null | undefined;
  regionOfBirth?: string | null | undefined;
  townOfBirth?: string | null | undefined;
  applicantNumber?: string | null | undefined;
  createdBy?: string | undefined;
  lastUpdatedBy?: string | undefined;
  creationDate?: string | undefined;
  lastUpdateDate?: string | undefined;
  workLocationAddress?: {  addressLine1?: string | null | undefined;
  addressLine2?: string | null | undefined;
  townOrCity?: string | null | undefined;
  region2?: string | null | undefined;
  country?: string | undefined;
  postalCode?: string | null | undefined;
  addressType?: string | undefined;
  primaryFlag?: boolean | undefined;} | undefined;
  addresses?: ({  addressLine1?: string | null | undefined;
  addressLine2?: string | null | undefined;
  townOrCity?: string | null | undefined;
  region2?: string | null | undefined;
  country?: string | undefined;
  postalCode?: string | null | undefined;
  addressType?: string | undefined;
  primaryFlag?: boolean | undefined;})[] | undefined;
  phones?: ({  phoneType?: string | undefined;
  phoneNumber?: string | undefined;
  primaryFlag?: boolean | undefined;})[] | undefined;
  emails?: ({  emailType?: string | undefined;
  emailAddress?: string | undefined;
  primaryFlag?: boolean | undefined;})[] | undefined;
};
