import { createSync, type ProxyConfiguration } from 'nango';
import { z } from 'zod';

const ProviderGroupSchema = z.object({
    name: z.string(),
    label: z.string(),
    priority: z.number()
});

const ProviderAttributeSchema = z.object({
    name: z.string(),
    label: z.string(),
    group: ProviderGroupSchema,
    priority: z.number(),
    value_type: z.number(),
    value_type_description: z.string()
});

const ProviderInsightTypeSchema = z.object({
    name: z.string(),
    period: z.number(),
    priority: z.number(),
    attribute: ProviderAttributeSchema.nullable().optional()
});

const ProviderInsightSchema = z.object({
    created: z.string(),
    target_date: z.string().nullable().optional(),
    type: ProviderInsightTypeSchema,
    html: z.string(),
    text: z.string()
});

const GroupSchema = z
    .object({
        name: z.string().describe('Machine-readable name of the attribute group, e.g. "sleep".'),
        label: z.string().describe('Human-readable label of the attribute group, e.g. "Sleep".'),
        priority: z.number().describe('Sort priority of the attribute group in ascending order.')
    })
    .describe('Attribute group the insight relates to.');

const AttributeSchema = z
    .object({
        name: z.string().describe('Machine-readable attribute name, e.g. "sleep".'),
        label: z.string().describe('Human-readable attribute label, e.g. "Time asleep".'),
        group: GroupSchema.describe('Group this attribute belongs to.'),
        priority: z.number().describe('Sort priority of the attribute in ascending order.'),
        value_type: z.number().describe('Numeric code for the attribute value type, e.g. 3 for a duration in minutes.'),
        value_type_description: z.string().describe('Human-readable description of the attribute value type, e.g. "Period (min)".')
    })
    .describe('Attribute the insight was generated for.');

const InsightTypeSchema = z
    .object({
        name: z.string().describe('Machine-readable insight type name, e.g. "dow_sleep".'),
        period: z.number().describe('Number of days covered by the insight.'),
        priority: z.number().describe('Insight priority: 1 = real-time, 2 = day, 3 = week, 4 = month.'),
        attribute: AttributeSchema.optional().describe(
            'Attribute the insight was generated for, when the insight targets a specific attribute rather than a general summary.'
        )
    })
    .describe('Type metadata describing how and why the insight was generated.');

const InsightSchema = z
    .object({
        id: z.string().describe('Stable identifier derived from the insight type, target date, and creation timestamp.'),
        created: z.string().describe('ISO 8601 timestamp when Exist generated the insight.'),
        target_date: z
            .string()
            .optional()
            .describe('Local date (YYYY-MM-DD) the insight refers to, omitted when the insight covers a longer period or targets no specific day.'),
        type: InsightTypeSchema.describe('Type metadata for the insight.'),
        html: z.string().describe('HTML-formatted insight message for rendering.'),
        text: z.string().describe('Plain-text insight message.')
    })
    .describe('A personalized insight generated by Exist for the user.');

const sync = createSync({
    description: 'Sync the personalized insights Exist has generated for the user.',
    version: '1.0.0',
    frequency: 'every hour',
    autoStart: true,
    models: {
        Insight: InsightSchema
    },

    exec: async (nango) => {
        // Full refresh is required: GET /api/2/insights/ only exposes a `date_min` filter that
        // bounds results by `target_date` (see actions/list-insights.ts), not by `created`. Many
        // insights (e.g. weekly/monthly summaries) carry a null or absent `target_date`, so a
        // `created`-based checkpoint passed through as `date_min` can silently and permanently
        // exclude insights whose `target_date` predates the checkpoint even though they were only
        // just created. Every run re-reads the full insight history and re-upserts records by
        // their stable id, so deletions are tracked across the complete pass.
        await nango.trackDeletesStart('Insight');

        const proxyConfig: ProxyConfiguration = {
            // https://developer.exist.io/reference/insights/
            endpoint: '/api/2/insights/',
            paginate: {
                type: 'link',
                limit: 100,
                limit_name_in_request: 'limit',
                response_path: 'results',
                link_path_in_response_body: 'next'
            },
            retries: 3
        };

        for await (const page of nango.paginate<unknown>(proxyConfig)) {
            const insights = ProviderInsightSchema.array().parse(page);

            const records = insights.map((insight) => ({
                id: `${insight.type.name}:${insight.target_date ?? 'no-date'}:${insight.created}`,
                created: insight.created,
                ...(insight.target_date != null && { target_date: insight.target_date }),
                type: {
                    name: insight.type.name,
                    period: insight.type.period,
                    priority: insight.type.priority,
                    ...(insight.type.attribute != null && { attribute: insight.type.attribute })
                },
                html: insight.html,
                text: insight.text
            }));

            if (records.length > 0) {
                await nango.batchSave(records, 'Insight');
            }
        }

        await nango.trackDeletesEnd('Insight');
    }
});

export type NangoSyncLocal = Parameters<(typeof sync)['exec']>[0];
export default sync;
