// ---------------------------
// This file was generated by Nango (v0.62.0)
// You can version this file
// ---------------------------

export interface JiraProjectId {
    id: string;
}

export interface JiraIssueMetadata {
    projectIdsToSync: JiraProjectId[];
    cloudId?: string;
    baseUrl?: string;
}

export interface Timestamps {
    createdAt: string;
    updatedAt: string;
}

export interface Author {
    accountId: string | null;
    active: boolean;
    displayName: string;
    emailAddress: string | null;
}

export interface Comment {
    id: string;
    createdAt: string;
    updatedAt: string;
    author: Author;
    body: Record<string, any>;
}

export interface Issue {
    id: string;
    createdAt: string;
    updatedAt: string;
    key: string;
    summary: string;
    issueType: string;
    status: string;
    assignee: string | null;
    url: string;
    webUrl: string;
    projectId: string;
    projectKey: string;
    projectName: string;
    comments: Comment[];
}

export interface Project {
    id: string;
    key: string;
    name: string;
    url: string;
    projectTypeKey: string;
    webUrl: string;
}

export interface IssueType {
    projectId: string;
    id: string;
    name: string;
    description: string | null;
    url: string;
}

export interface CreateIssueInput {
    summary: string;
    description?: string;
    assignee?: string;
    labels?: string[];
    project: string;
    issueType: string;
}

export interface CreateIssueOutput {
    id: string;
    key: string;
    self: string;
}
