// ---------------------------
// This file was generated by Nango (v0.58.7)
// You can version this file
// ---------------------------

export interface NetsuiteMetadata {
    timezone?: string | undefined;
}

export interface NetsuiteAddress {
    addressLine1: string | null;
    addressLine2: string | null;
    city: string | null;
    zip: string | null;
    country: string | null;
    state: string | null;
}

export interface NetsuiteCustomer {
    id: string;
    externalId: string | null;
    name: string;
    email: string | null;
    taxNumber: string | null;
    phone: string | null;
    addressLine1: string | null;
    addressLine2: string | null;
    city: string | null;
    zip: string | null;
    country: string | null;
    state: string | null;
}

export interface NetsuiteCustomerCreateInput {
    externalId: string;
    name: string;
    email?: string;
    taxNumber?: string;
    addressLine1?: string;
    addressLine2?: string;
    city?: string;
    zip?: string;
    country?: string;
    state?: string;
    phone?: string;
}

export interface NetsuiteCustomerCreateOutput {
    id: string;
}

export interface NetsuiteCustomerUpdateInput {
    externalId?: string;
    name?: string;
    email?: string;
    taxNumber?: string;
    addressLine1?: string;
    addressLine2?: string;
    city?: string;
    zip?: string;
    country?: string;
    state?: string;
    phone?: string;
    id: string;
}

export interface NetsuiteCustomerUpdateOutput {
    success: boolean;
}

export interface NetsuiteInvoiceLine {
    itemId: string;
    quantity: number;
    amount: number;
    vatCode?: string;
    description?: string;
    locationId?: string;
}

export interface NetsuiteCreditNote {
    id: string;
    customerId: string;
    currency: string;
    description: string | null;
    createdAt: string;
    lines: NetsuiteInvoiceLine[];
    total: number;
    status: string;
}

export interface NetsuiteCreditNoteLine {
    itemId: string;
    quantity: number;
    amount: number;
    vatCode?: string;
    description?: string;
}

export interface NetsuiteCreditNoteCreateInput {
    customerId: string;
    status: string;
    currency: string;
    description?: string;
    lines: NetsuiteCreditNoteLine[];
}

export interface NetsuiteCreditNoteCreateOutput {
    id: string;
}

export interface NetsuiteCreditNoteUpdateInput {
    customerId: string;
    status: string;
    currency: string;
    description?: string;
    lines: NetsuiteCreditNoteLine[];
    id: string;
}

export interface NetsuiteCreditNoteUpdateOutput {
    success: boolean;
}

export interface NetsuiteInvoice {
    id: string;
    customerId: string;
    currency: string;
    description: string | null;
    createdAt: string;
    lines: NetsuiteInvoiceLine[];
    total: number;
    status: string;
}

export interface NetsuiteInvoiceCreateInput {
    customerId: string;
    currency: string;
    description?: string;
    status: string;
    lines: NetsuiteInvoiceLine[];
}

export interface NetsuiteInvoiceCreateOutput {
    id: string;
}

export interface NetsuiteInvoiceUpdateInput {
    customerId?: string;
    currency?: string;
    description?: string;
    status: string;
    lines: NetsuiteInvoiceLine[];
    id: string;
    locationId?: string;
}

export interface NetsuiteInvoiceUpdateOutput {
    success: boolean;
}

export interface NetsuitePayment {
    id: string;
    description?: string;
    customerId: string | null;
    amount: number | null;
    createdAt: string | null;
    currency: string | null;
    paymentReference: string | null;
    status: string | null;
    applyTo: string[];
}

export interface NetsuitePaymentCreateInput {
    customerId: string;
    amount: number;
    currency: string;
    paymentReference: string;
    applyTo: string[];
    status: string;
    description?: string;
}

export interface NetsuitePaymentCreateOutput {
    id: string;
}

export interface NetsuitePaymentUpdateInput {
    customerId: string;
    amount?: number;
    currency?: string;
    paymentReference?: string;
    applyTo?: string[];
    status?: string;
    description?: string;
    id: string;
}

export interface NetsuitePaymentUpdateOutput {
    success: boolean;
}

export interface NetsuiteLocation {
    id: string;
    isInactive: boolean;
    name: string;
    lastModifiedDate: string;
    address: { address1: string; addressee: string; addressText: string; city: string; country: string; state: string; zip: string };
    returnAddress: { addressText: string; country: string };
    timeZone?: string | null;
    useBins: boolean;
}

export interface LedgerLine {
    journalLineId: string;
    accountId: string;
    accountName: string;
    cleared: boolean;
    credit?: number;
    debit?: number;
    description: string;
}

export interface GeneralLedger {
    id: string;
    date: string;
    transactionId: string;
    void: boolean;
    approved: boolean;
    currency: string;
    createdDate: string;
    updatedDate: string;
    isReversal: boolean;
    subsidiary: { id: string; name: string };
    lines: LedgerLine[];
}

export interface InventoryDetail {
    binNumber?: string;
    expirationDate?: string;
    quantity?: number;
    serialNumber?: string;
    toBinNumber?: string;
}

export interface PurchaseOrderLine {
    itemId: string;
    quantity: number;
    amount: number;
    description?: string;
    locationId?: string;
    rate?: number;
    department?: string;
    class?: string;
    createWorkOrder?: boolean;
    inventoryDetail?: InventoryDetail | null;
}

export interface TaxDetails {
    taxCode?: string;
    taxRate?: number;
}

export interface Address {
    addr1?: string;
    addr2?: string;
    addr3?: string;
    city?: string;
    state?: string;
    zip?: string;
    country?: string;
}

export interface NetsuitePurchaseOrderCreateInput {
    vendorId: string;
    currency?: string;
    description?: string;
    status: string;
    tranDate?: string;
    dueDate?: string;
    lines: PurchaseOrderLine[];
    customForm?: string;
    location?: string;
    subsidiary?: string;
    department?: string;
    class?: string;
    taxDetails?: TaxDetails | null;
    billingAddress?: Address;
    shippingAddress?: Address;
}

export interface NetsuitePurchaseOrderCreateOutput {
    id: string;
}

export interface NetsuitePurchaseOrderUpdateInput {
    id: string;
    vendorId?: string;
    currency?: string;
    description?: string;
    status?: string;
    tranDate?: string;
    dueDate?: string;
    lines?: PurchaseOrderLine[];
    customForm?: string;
    location?: string;
    subsidiary?: string;
    department?: string;
    class?: string;
    billingAddress?: Address | null;
    shippingAddress?: Address | null;
    taxDetails?: TaxDetails | null;
}

export interface NetsuitePurchaseOrderUpdateOutput {
    success: boolean;
}

export interface NetsuiteBillLine {
    itemId: string;
    quantity: number;
    amount: number;
    description?: string;
    rate?: number;
    locationId?: string;
    departmentId?: string;
    classId?: string;
    customerId?: string;
    isBillable?: boolean;
    taxDetails?: { taxCode?: string; taxRate?: number };
    inventoryDetail?: { binNumber?: string; expirationDate?: string; quantity?: number; serialNumber?: string };
}

export interface NetsuiteBillCreateInput {
    vendorId: string;
    tranDate: string;
    currency: string;
    dueDate?: string;
    status?: string;
    memo?: string;
    externalId?: string;
    location?: string;
    subsidiary?: string;
    department?: string;
    class?: string;
    terms?: string;
    lines: NetsuiteBillLine[];
    billingAddress?: { addr1?: string; addr2?: string; addr3?: string; city?: string; state?: string; zip?: string; country?: string };
    taxDetails?: { taxCode?: string; taxRate?: number };
}

export interface NetsuiteBillCreateOutput {
    id: string;
}

export interface NetsuiteBillUpdateInput {
    id: string;
    vendorId?: string;
    tranDate?: string;
    currency?: string;
    dueDate?: string;
    status?: string;
    memo?: string;
    externalId?: string;
    location?: string;
    subsidiary?: string;
    department?: string;
    class?: string;
    terms?: string;
    lines?: NetsuiteBillLine[];
    billingAddress?: { addr1?: string; addr2?: string; addr3?: string; city?: string; state?: string; zip?: string; country?: string };
    taxDetails?: { taxCode?: string; taxRate?: number };
}

export interface NetsuiteBillUpdateOutput {
    success: boolean;
}

export interface FetchFieldsInput {
    name: string;
}

export interface FetchFieldsOutput {
    id?: string | undefined;
    schema?: string | undefined;
    title?: string | undefined;
    description?: string | undefined;
    type?: string | string[] | undefined;
    properties?: Record<string, any> | undefined;
    required?: string[] | undefined;
    items?: FetchFieldsOutput | FetchFieldsOutput[] | undefined;
    enum?: any[] | undefined;
    definitions?: Record<string, any> | undefined;
    additionalProperties?: boolean | FetchFieldsOutput | undefined;
    default?: any | undefined;
}
