// ---------------------------
// This file was generated by Nango (v0.68.1)
// You can version this file
// ---------------------------

export interface SyncMetadata_pennylane_customers {
};

export interface PennylaneCustomer {
  id: string;
  first_name?: string | undefined;
  last_name?: string | undefined;
  gender?: string | undefined;
  address?: string | undefined;
  vat_number?: string | null | undefined;
  postal_code?: string | null | undefined;
  city?: string | null | undefined;
  country_alpha2?: string | null | undefined;
  recipient?: string | null | undefined;
  source_id?: string | null | undefined;
  emails?: string[] | null | undefined;
  billing_iban?: string | null | undefined;
  delivery_address?: {  address?: string | undefined;
  postal_code?: string | null | undefined;
  city?: string | null | undefined;
  country_alpha2?: string | null | undefined;} | null;
  delivery_postal_code?: string | null | undefined;
  delivery_country_alpha2?: string | null | undefined;
  payment_conditions?: string | null | undefined;
  phone?: string | null | undefined;
  reference?: string | null | undefined;
  notes?: string | null | undefined;
};

export interface SyncMetadata_pennylane_suppliers {
};

export interface PennylaneSupplier {
  name: string;
  id: string;
  reg_no?: string | undefined;
  address: string;
  postal_code: string;
  city: string;
  country_alpha2: string;
  recipient?: string | undefined;
  vat_number?: string | undefined;
  source_id?: string | undefined;
  emails: string[];
  iban?: string | undefined;
  payment_conditions?: string | undefined;
  phone?: string | undefined;
  reference?: string | undefined;
  notes?: string | undefined;
};

export interface SyncMetadata_pennylane_invoices {
};

export interface PennylaneInvoice {
  id: string;
  amount: string | null;
  billing_subscription?: {  id: string | null;} | null | undefined;
  categories?: ({  source_id: string;
  weight: string;
  label: string;
  direction: string | null;
  created_at: Date | string;
  updated_at: Date | string;})[] | null | undefined;
  currency: string | null;
  currency_amount: string | null;
  currency_amount_before_tax?: string | null | undefined;
  currency_tax: string | null;
  customer?: {  customer_type?: string | undefined;
  first_name: string;
  last_name: string;
  country_alpha2: string;
  gender?: string | null | undefined;
  address?: string | undefined;
  postal_code?: string | undefined;
  city?: string | undefined;
  source_id?: string | undefined;
  emails?: string[] | undefined;
  billing_iban?: string | undefined;
  delivery_address?: string | {  address?: string | undefined;
  postal_code?: string | null | undefined;
  city?: string | null | undefined;
  country_alpha2?: string | null | undefined;};
  vat_number?: string | null | undefined;
  delivery_postal_code?: string | undefined;
  delivery_city?: string | undefined;
  delivery_country_alpha2?: string | undefined;
  payment_conditions?: string | undefined;
  phone?: string | undefined;
  reference?: string | undefined;
  notes?: string | undefined;
  mandate?: {  provider?: string | undefined;
  source_id: string;};
  plan_item?: {  number?: string | undefined;
  label?: string | undefined;
  enabled?: boolean | undefined;
  vat_rate?: string | undefined;
  country_alpha2?: string | undefined;
  description?: string | undefined;};};
  customer_name: string;
  customer_validation_needed: boolean | null;
  date?: Date | string | undefined;
  deadline: string | null;
  discount: string | null;
  discount_type?: string | null | undefined;
  exchange_rate: number | null;
  file_url: string | null;
  filename: string | null;
  fully_paid_at?: Date | null | undefined;
  imputation_dates: {  start_date: string;
  end_date: string;} | null;
  invoice_number?: string | null | undefined;
  is_draft: boolean;
  is_estimate?: boolean | undefined;
  label?: string | null | undefined;
  language?: string | null | undefined;
  line_items: ({  id?: number | undefined;
  label?: string | undefined;
  unit?: string | null | undefined;
  quantity?: string | undefined;
  amount?: string | undefined;
  currency_amount?: string | undefined;
  description?: string | undefined;
  product_id?: string | null | undefined;
  vat_rate?: string | undefined;
  currency_price_before_tax?: string | undefined;
  currency_tax?: string | undefined;
  raw_currency_unit_price?: string | undefined;
  discount?: string | undefined;
  discount_type?: string | undefined;
  section_rank?: number | null | undefined;
  v2_id?: number | null | undefined;
  product_v2_id?: number | null | undefined;})[];
  line_items_sections_attributes: ({  title?: string | null | undefined;
  description?: string | null | undefined;
  rank: number;})[];
  matched_transactions: ({  label: string | null;
  amount: string | null;
  group_uuid: string | null;
  date: Date | null;
  fee: string | null;
  currency: string;})[];
  paid: boolean;
  payments: ({})[];
  pdf_invoice_free_text: string;
  pdf_invoice_subject: string;
  public_url: string | null;
  quote_group_uuid?: string | null | undefined;
  remaining_amount: string | null;
  source: string | null;
  special_mention: string | null;
  status: string | null;
  transactions_reference?: {  banking_provider: string | null;
  provider_field_name: string | null;
  provider_field_value: string | null;} | null | undefined;
  updated_at: Date | string;
};

export interface SyncMetadata_pennylane_products {
};

export interface PennylaneProduct {
  id: string;
  source_id: string;
  label: string;
  description?: string | undefined;
  unit: string;
  price_before_tax?: number | undefined;
  price: number;
  vat_rate: string;
  currency: string;
  reference?: string | null | undefined;
  substance?: string | null | undefined;
};

export interface ActionInput_pennylane_createcustomer {
  customer_type?: string | undefined;
  first_name: string;
  last_name: string;
  country_alpha2: string;
  gender?: string | null | undefined;
  address?: string | undefined;
  postal_code?: string | undefined;
  city?: string | undefined;
  source_id?: string | undefined;
  emails?: string[] | undefined;
  billing_iban?: string | undefined;
  delivery_address?: string | {  address?: string | undefined;
  postal_code?: string | null | undefined;
  city?: string | null | undefined;
  country_alpha2?: string | null | undefined;};
  vat_number?: string | null | undefined;
  delivery_postal_code?: string | undefined;
  delivery_city?: string | undefined;
  delivery_country_alpha2?: string | undefined;
  payment_conditions?: string | undefined;
  phone?: string | undefined;
  reference?: string | undefined;
  notes?: string | undefined;
  mandate?: {  provider?: string | undefined;
  source_id: string;};
  plan_item?: {  number?: string | undefined;
  label?: string | undefined;
  enabled?: boolean | undefined;
  vat_rate?: string | undefined;
  country_alpha2?: string | undefined;
  description?: string | undefined;};
};

export interface ActionOutput_pennylane_createcustomer {
  success: boolean;
  source_id: string;
};

export interface ActionInput_pennylane_createinvoice {
  create_customer?: boolean | undefined;
  create_products?: boolean | undefined;
  update_customer?: boolean | undefined;
  date: string;
  deadline: string;
  draft?: boolean | undefined;
  customer_source_id: string;
  external_id?: string | null | undefined;
  pdf_invoice_free_text?: string | null | undefined;
  pdf_invoice_subject?: string | null | undefined;
  currency?: string | undefined;
  special_mention?: string | null | undefined;
  discount?: number | undefined;
  language?: string | undefined;
  transactions_reference: {  banking_provider: string | null;
  provider_field_name: string | null;
  provider_field_value: string | null;};
  line_items: ({  label: string;
  quantity: number;
  section_rank?: number | undefined;
  currency_amount: number;
  plan_item_number?: string | undefined;
  unit: string;
  vat_rate: string;
  description?: string | undefined;
  discount?: number | undefined;})[] | ({  label: string;
  quantity: number;
  section_rank?: number | undefined;
  currency_amount_before_tax: number;
  plan_item_number?: string | undefined;
  unit: string;
  vat_rate: string;
  description?: string | undefined;
  discount?: number | undefined;})[] | ({  label?: string | undefined;
  quantity: number;
  discount?: number | undefined;
  section_rank?: number | undefined;
  plan_item_number?: string | undefined;
  product: {  source_id: string;
  price?: number | undefined;
  vat_rate?: string | undefined;
  unit?: string | undefined;};})[];
  categories: ({  source_id: string;
  weight: number | null;
  amount: number | null;})[];
  line_items_sections_attributes: ({  title?: string | null | undefined;
  description?: string | null | undefined;
  rank: number;})[];
  imputation_dates?: {  start_date: string;
  end_date: string;} | undefined;
};

export interface ActionOutput_pennylane_createinvoice {
  success: boolean;
  source_id: string;
};

export interface ActionInput_pennylane_createsupplier {
  name: string;
  reg_no?: string | undefined;
  address: string;
  postal_code: string;
  city: string;
  country_alpha2: string;
  recipient?: string | undefined;
  vat_number?: string | undefined;
  source_id?: string | undefined;
  emails: string[];
  iban?: string | undefined;
  payment_conditions?: string | undefined;
  phone?: string | undefined;
  reference?: string | undefined;
  notes?: string | undefined;
};

export interface ActionOutput_pennylane_createsupplier {
  success: boolean;
  source_id: string;
};

export interface ActionInput_pennylane_updatecustomer {
  id: string;
  first_name?: string | undefined;
  last_name?: string | undefined;
  gender?: string | undefined;
  address?: string | undefined;
  vat_number?: string | null | undefined;
  postal_code?: string | null | undefined;
  city?: string | null | undefined;
  country_alpha2?: string | null | undefined;
  recipient?: string | null | undefined;
  source_id?: string | null | undefined;
  emails?: string[] | null | undefined;
  billing_iban?: string | null | undefined;
  delivery_address?: {  address?: string | undefined;
  postal_code?: string | null | undefined;
  city?: string | null | undefined;
  country_alpha2?: string | null | undefined;} | null;
  delivery_postal_code?: string | null | undefined;
  delivery_country?: string | null | undefined;
  delivery_country_alpha2?: string | null | undefined;
  payment_conditions?: string | null | undefined;
  phone?: string | null | undefined;
  reference?: string | null | undefined;
  notes?: string | null | undefined;
};

export interface ActionOutput_pennylane_updatecustomer {
  success: boolean;
  source_id: string;
};

export interface ActionInput_pennylane_updateinvoice {
  id: string;
  label?: string | null | undefined;
  invoice_number?: string | null | undefined;
  quote_group_uuid?: string | undefined;
  is_draft?: boolean | undefined;
  is_estimate?: boolean | undefined;
  currency?: string | undefined;
  amount?: string | undefined;
  currency_amount?: string | undefined;
  currency_amount_before_tax?: string | undefined;
  exchange_rate?: number | undefined;
  date?: string | null | undefined;
  deadline?: string | null | undefined;
  currency_tax?: string | undefined;
  language?: string | undefined;
  paid?: boolean | undefined;
  fully_paid_at?: string | null | undefined;
  status?: string | null | undefined;
  discount?: string | undefined;
  discount_type?: string | undefined;
  public_url?: string | undefined;
  file_url?: string | null | undefined;
  filename?: string | undefined;
  remaining_amount?: string | undefined;
  source?: 'InvoiceSource' | undefined;
  special_mention?: string | null | undefined;
  updated_at?: string | undefined;
  imputation_dates?: {  start_date: string;
  end_date: string;} | null | undefined;
  customer: {  customer_type?: string | undefined;
  first_name: string;
  last_name: string;
  country_alpha2: string;
  gender?: string | null | undefined;
  address?: string | undefined;
  postal_code?: string | undefined;
  city?: string | undefined;
  source_id?: string | undefined;
  emails?: string[] | undefined;
  billing_iban?: string | undefined;
  delivery_address?: string | {  address?: string | undefined;
  postal_code?: string | null | undefined;
  city?: string | null | undefined;
  country_alpha2?: string | null | undefined;};
  vat_number?: string | null | undefined;
  delivery_postal_code?: string | undefined;
  delivery_city?: string | undefined;
  delivery_country_alpha2?: string | undefined;
  payment_conditions?: string | undefined;
  phone?: string | undefined;
  reference?: string | undefined;
  notes?: string | undefined;
  mandate?: {  provider?: string | undefined;
  source_id: string;};
  plan_item?: {  number?: string | undefined;
  label?: string | undefined;
  enabled?: boolean | undefined;
  vat_rate?: string | undefined;
  country_alpha2?: string | undefined;
  description?: string | undefined;};};
  line_items_sections_attributes: ({  title?: string | null | undefined;
  description?: string | null | undefined;
  rank: number;})[];
  line_items: ({  id?: number | undefined;
  label?: string | undefined;
  unit?: string | null | undefined;
  quantity?: string | undefined;
  amount?: string | undefined;
  currency_amount?: string | undefined;
  description?: string | undefined;
  product_id?: string | null | undefined;
  vat_rate?: string | undefined;
  currency_price_before_tax?: string | undefined;
  currency_tax?: string | undefined;
  raw_currency_unit_price?: string | undefined;
  discount?: string | undefined;
  discount_type?: string | undefined;
  section_rank?: number | null | undefined;
  v2_id?: number | null | undefined;
  product_v2_id?: number | null | undefined;})[];
  categories: ({  source_id: string;
  weight: string;
  label: string;
  direction: string | null;
  created_at: Date | string;
  updated_at: Date | string;})[];
  transactions_reference: {  banking_provider: string | null;
  provider_field_name: string | null;
  provider_field_value: string | null;};
  payments: ({  label: string;
  created_at: Date | string;
  currency_amount: string;})[];
  matched_transactions: ({  label: string | null;
  amount: string | null;
  group_uuid: string | null;
  date: Date | null;
  fee: string | null;
  currency: string;})[];
  pdf_invoice_free_text?: string | undefined;
  pdf_invoice_subject?: string | undefined;
  billing_subscription?: {  id: string | null;} | null | undefined;
};

export interface ActionOutput_pennylane_updateinvoice {
  success: boolean;
  source_id: string;
};

export interface ActionInput_pennylane_updatesupplier {
  source_id: string;
  name?: string | undefined;
  reg_no?: string | undefined;
  address?: string | undefined;
  postal_code?: string | undefined;
  city?: string | undefined;
  country_alpha2?: string | undefined;
  recipient?: string | undefined;
  vat_number?: string | undefined;
  emails: string[];
  iban?: string | undefined;
  payment_conditions?: string | undefined;
  phone?: string | undefined;
  reference?: string | undefined;
  notes?: string | undefined;
};

export interface ActionOutput_pennylane_updatesupplier {
  success: boolean;
  source_id: string;
};

export interface ActionInput_pennylane_createproduct {
  source_id: string;
  label: string;
  description?: string | undefined;
  unit: string;
  price_before_tax?: number | undefined;
  price: number;
  vat_rate: string;
  currency: string;
  reference?: string | null | undefined;
  substance?: string | null | undefined;
};

export interface ActionOutput_pennylane_createproduct {
  success: boolean;
  source_id: string;
};

export interface ActionInput_pennylane_updateproduct {
  source_id: string;
  label?: string | undefined;
  description?: string | undefined;
  unit?: string | undefined;
  price_before_tax?: number | undefined;
  price?: number | undefined;
  vat_rate?: string | undefined;
  currency?: string | undefined;
  reference?: string | null | undefined;
  substance?: string | null | undefined;
};

export interface ActionOutput_pennylane_updateproduct {
  success: boolean;
  source_id: string;
};
