// ---------------------------
// This file was generated by Nango (v0.65.0)
// You can version this file
// ---------------------------

export interface TransactionReferenceObject {
    banking_provider: string | null;
    provider_field_name: string | null;
    provider_field_value: string | null;
}

export interface LineItemWithTax {
    label: string;
    quantity: number;
    section_rank?: number | undefined;
    currency_amount: number;
    plan_item_number?: string | undefined;
    unit: string;
    vat_rate: string;
    description?: string | undefined;
    discount?: number | undefined;
}

export interface LineItemWithoutTax {
    label: string;
    quantity: number;
    section_rank?: number | undefined;
    currency_amount_before_tax: number;
    plan_item_number?: string | undefined;
    unit: string;
    vat_rate: string;
    description?: string | undefined;
    discount?: number | undefined;
}

export interface LineItemWithExistingProduct {
    label?: string | undefined;
    quantity: number;
    discount?: number | undefined;
    section_rank?: number | undefined;
    plan_item_number?: string | undefined;
    product: { source_id: string; price?: number | undefined; vat_rate?: string | undefined; unit?: string | undefined };
}

export interface CategoryObject {
    source_id: string;
    weight: number | null;
    amount: number | null;
}

export interface LineItemsSectionsAttributesObject {
    title?: string | null | undefined;
    description?: string | null | undefined;
    rank: number;
}

export interface CreateInvoice {
    create_customer?: boolean | undefined;
    create_products?: boolean | undefined;
    update_customer?: boolean | undefined;
    date: string;
    deadline: string;
    draft?: boolean | undefined;
    customer_source_id: string;
    external_id?: string | null | undefined;
    pdf_invoice_free_text?: string | null | undefined;
    pdf_invoice_subject?: string | null | undefined;
    currency?: string | undefined;
    special_mention?: string | null | undefined;
    discount?: number | undefined;
    language?: string | undefined;
    transactions_reference?: TransactionReferenceObject | undefined;
    line_items: LineItemWithTax[] | LineItemWithoutTax[] | LineItemWithExistingProduct[];
    categories?: CategoryObject[] | undefined;
    line_items_sections_attributes?: LineItemsSectionsAttributesObject[] | undefined;
    imputation_dates?: { start_date: string; end_date: string } | undefined;
}

export interface ImputationDateObject {
    start_date: string;
    end_date: string;
}

export interface DeliveryAddressObject {
    address?: string | undefined;
    postal_code?: string | null | undefined;
    city?: string | null | undefined;
    country_alpha2?: string | null | undefined;
}

export interface PennylaneIndividualCustomer {
    customer_type?: string | undefined;
    first_name: string;
    last_name: string;
    country_alpha2: string;
    gender?: string | null | undefined;
    address?: string | undefined;
    postal_code?: string | undefined;
    city?: string | undefined;
    source_id?: string | undefined;
    emails?: string[] | undefined;
    billing_iban?: string | undefined;
    delivery_address?: string | DeliveryAddressObject | undefined;
    vat_number?: string | null | undefined;
    delivery_postal_code?: string | undefined;
    delivery_city?: string | undefined;
    delivery_country_alpha2?: string | undefined;
    payment_conditions?: string | undefined;
    phone?: string | undefined;
    reference?: string | undefined;
    notes?: string | undefined;
    mandate?: { provider?: string | undefined; source_id: string } | undefined;
    plan_item?:
        | {
              number?: string | undefined;
              label?: string | undefined;
              enabled?: boolean | undefined;
              vat_rate?: string | undefined;
              country_alpha2?: string | undefined;
              description?: string | undefined;
          }
        | undefined;
}

export interface InvoiceLineItem {
    id?: number | undefined;
    label?: string | undefined;
    unit?: string | null | undefined;
    quantity?: string | undefined;
    amount?: string | undefined;
    currency_amount?: string | undefined;
    description?: string | undefined;
    product_id?: string | null | undefined;
    vat_rate?: string | undefined;
    currency_price_before_tax?: string | undefined;
    currency_tax?: string | undefined;
    raw_currency_unit_price?: string | undefined;
    discount?: string | undefined;
    discount_type?: string | undefined;
    section_rank?: number | null | undefined;
    v2_id?: number | null | undefined;
    product_v2_id?: number | null | undefined;
}

export interface InvoiceCategory {
    source_id: string;
    weight: string;
    label: string;
    direction: string | null;
    created_at: Date | string;
    updated_at: Date | string;
}

export interface PaymentsObject {
    label: string;
    created_at: Date | string;
    currency_amount: string;
}

export interface MatchedTransactionsObject {
    label: string | null;
    amount: string | null;
    group_uuid: string | null;
    date: Date | null;
    fee: string | null;
    currency: string;
}

export interface BillingSubscriptionObject {
    id: string | null;
}

export interface UpdateInvoice {
    id: string;
    label?: string | null | undefined;
    invoice_number?: string | null | undefined;
    quote_group_uuid?: string | undefined;
    is_draft?: boolean | undefined;
    is_estimate?: boolean | undefined;
    currency?: string | undefined;
    amount?: string | undefined;
    currency_amount?: string | undefined;
    currency_amount_before_tax?: string | undefined;
    exchange_rate?: number | undefined;
    date?: string | null | undefined;
    deadline?: string | null | undefined;
    currency_tax?: string | undefined;
    language?: string | undefined;
    paid?: boolean | undefined;
    fully_paid_at?: string | null | undefined;
    status?: string | null | undefined;
    discount?: string | undefined;
    discount_type?: string | undefined;
    public_url?: string | undefined;
    file_url?: string | null | undefined;
    filename?: string | undefined;
    remaining_amount?: string | undefined;
    source?: 'InvoiceSource' | undefined;
    special_mention?: string | null | undefined;
    updated_at?: string | undefined;
    imputation_dates?: ImputationDateObject | null | undefined;
    customer?: PennylaneIndividualCustomer | undefined;
    line_items_sections_attributes?: LineItemsSectionsAttributesObject[] | undefined;
    line_items?: InvoiceLineItem[] | undefined;
    categories?: InvoiceCategory[] | undefined;
    transactions_reference?: TransactionReferenceObject | undefined;
    payments?: PaymentsObject[] | undefined;
    matched_transactions?: MatchedTransactionsObject[] | undefined;
    pdf_invoice_free_text?: string | undefined;
    pdf_invoice_subject?: string | undefined;
    billing_subscription?: BillingSubscriptionObject | null | undefined;
}

export interface UpdateInvoiceResponse {
    invoice: UpdateInvoice;
}

export interface CreateSupplier {
    name: string;
    reg_no?: string | undefined;
    address: string;
    postal_code: string;
    city: string;
    country_alpha2: string;
    recipient?: string | undefined;
    vat_number?: string | undefined;
    source_id?: string | undefined;
    emails: string[];
    iban?: string | undefined;
    payment_conditions?: string | undefined;
    phone?: string | undefined;
    reference?: string | undefined;
    notes?: string | undefined;
}

export interface UpdateSupplier {
    source_id: string;
    name?: string | undefined;
    reg_no?: string | undefined;
    address?: string | undefined;
    postal_code?: string | undefined;
    city?: string | undefined;
    country_alpha2?: string | undefined;
    recipient?: string | undefined;
    vat_number?: string | undefined;
    emails?: string[] | undefined;
    iban?: string | undefined;
    payment_conditions?: string | undefined;
    phone?: string | undefined;
    reference?: string | undefined;
    notes?: string | undefined;
}

export interface UpdateSupplierResponse {
    supplier: {
        source_id: string;
        name?: string | undefined;
        reg_no?: string | undefined;
        address?: string | undefined;
        postal_code?: string | undefined;
        city?: string | undefined;
        country_alpha2?: string | undefined;
        recipient?: string | undefined;
        vat_number?: string | undefined;
        emails?: string[] | undefined;
        iban?: string | undefined;
        payment_conditions?: string | undefined;
        phone?: string | undefined;
        reference?: string | undefined;
        notes?: string | undefined;
    };
}

export interface PennylaneInvoice {
    id: string;
    amount: string | null;
    billing_subscription?: BillingSubscriptionObject | null | undefined;
    categories?: InvoiceCategory[] | null | undefined;
    currency: string | null;
    currency_amount: string | null;
    currency_amount_before_tax?: string | null | undefined;
    currency_tax: string | null;
    customer?: PennylaneIndividualCustomer | undefined;
    customer_name: string;
    customer_validation_needed: boolean | null;
    date?: Date | string | undefined;
    deadline: string | null;
    discount: string | null;
    discount_type?: string | null | undefined;
    exchange_rate: number | null;
    file_url: string | null;
    filename: string | null;
    fully_paid_at?: Date | null | undefined;
    imputation_dates: ImputationDateObject | null;
    invoice_number?: string | null | undefined;
    is_draft: boolean;
    is_estimate?: boolean | undefined;
    label?: string | null | undefined;
    language?: string | null | undefined;
    line_items?: InvoiceLineItem[] | undefined;
    line_items_sections_attributes?: LineItemsSectionsAttributesObject[] | undefined;
    matched_transactions?: MatchedTransactionsObject[] | undefined;
    paid: boolean;
    payments: Record<string, any>[];
    pdf_invoice_free_text: string;
    pdf_invoice_subject: string;
    public_url: string | null;
    quote_group_uuid?: string | null | undefined;
    remaining_amount: string | null;
    source: string | null;
    special_mention: string | null;
    status: string | null;
    transactions_reference?: TransactionReferenceObject | null | undefined;
    updated_at: Date | string;
}

export interface InvoiceResponse {
    invoice: PennylaneInvoice;
}

export interface UpdateIndividualCustomer {
    id: string;
    customer: PennylaneIndividualCustomer;
}

export interface MandateObject {
    provider: string;
    source_id: string;
}

export interface IndividualCustomerResponse {
    customer: {
        first_name?: string | undefined;
        last_name?: string | undefined;
        gender?: string | null | undefined;
        name?: string | undefined;
        updated_at?: string | undefined;
        source_id: string;
        emails?: string[] | undefined;
        billing_iban?: string | null | undefined;
        customer_type?: string | undefined;
        recipient?: string | undefined;
        billing_address?:
            | { address?: string | undefined; postal_code?: string | undefined; city?: string | undefined; country_alpha2?: string | undefined }
            | undefined;
        delivery_address?:
            | { address?: string | undefined; postal_code?: string | undefined; city?: string | undefined; country_alpha2?: string | undefined }
            | undefined;
        payment_conditions?: string | undefined;
        phone?: string | undefined;
        reference?: string | undefined;
        notes?: string | undefined;
        plan_item?: { number: string; label: string; enabled: boolean; vat_rate: string; country_alpha2: string; description: string } | undefined;
        mandates?: MandateObject[] | undefined;
    };
}

export interface PennylaneSuccessResponse {
    success: boolean;
    source_id: string;
}

export interface UpdatePennylaneCustomer {
    id: string;
    first_name?: string | undefined;
    last_name?: string | undefined;
    gender?: string | undefined;
    address?: string | undefined;
    vat_number?: string | null | undefined;
    postal_code?: string | null | undefined;
    city?: string | null | undefined;
    country_alpha2?: string | null | undefined;
    recipient?: string | null | undefined;
    source_id?: string | null | undefined;
    emails?: string[] | null | undefined;
    billing_iban?: string | null | undefined;
    delivery_address?: DeliveryAddressObject | null | undefined;
    delivery_postal_code?: string | null | undefined;
    delivery_country?: string | null | undefined;
    delivery_country_alpha2?: string | null | undefined;
    payment_conditions?: string | null | undefined;
    phone?: string | null | undefined;
    reference?: string | null | undefined;
    notes?: string | null | undefined;
}

export interface PennylaneCustomer {
    id: string;
    first_name?: string | undefined;
    last_name?: string | undefined;
    gender?: string | undefined;
    address?: string | undefined;
    vat_number?: string | null | undefined;
    postal_code?: string | null | undefined;
    city?: string | null | undefined;
    country_alpha2?: string | null | undefined;
    recipient?: string | null | undefined;
    source_id?: string | null | undefined;
    emails?: string[] | null | undefined;
    billing_iban?: string | null | undefined;
    delivery_address?: DeliveryAddressObject | null | undefined;
    delivery_postal_code?: string | null | undefined;
    delivery_country_alpha2?: string | null | undefined;
    payment_conditions?: string | null | undefined;
    phone?: string | null | undefined;
    reference?: string | null | undefined;
    notes?: string | null | undefined;
}

export interface PennylaneSupplier {
    name: string;
    id?: string | undefined;
    reg_no?: string | undefined;
    address: string;
    postal_code: string;
    city: string;
    country_alpha2: string;
    recipient?: string | undefined;
    vat_number?: string | undefined;
    source_id?: string | undefined;
    emails: string[];
    iban?: string | undefined;
    payment_conditions?: string | undefined;
    phone?: string | undefined;
    reference?: string | undefined;
    notes?: string | undefined;
}

export interface CreateProduct {
    source_id: string;
    label: string;
    description?: string | undefined;
    unit: string;
    price_before_tax?: number | undefined;
    price: number;
    vat_rate: string;
    currency: string;
    reference?: string | null | undefined;
    substance?: string | null | undefined;
}

export interface UpdateProduct {
    source_id: string;
    label?: string | undefined;
    description?: string | undefined;
    unit?: string | undefined;
    price_before_tax?: number | undefined;
    price?: number | undefined;
    vat_rate?: string | undefined;
    currency?: string | undefined;
    reference?: string | null | undefined;
    substance?: string | null | undefined;
}

export interface PennylaneProduct {
    id: string;
    source_id: string;
    label: string;
    description?: string | undefined;
    unit: string;
    price_before_tax?: number | undefined;
    price: number;
    vat_rate: string;
    currency: string;
    reference?: string | null | undefined;
    substance?: string | null | undefined;
}

export interface InvoiceMapper {
    create_customer: boolean;
    create_products: boolean;
    update_customer: boolean;
    invoice: {
        date: string;
        deadline: string;
        draft: boolean;
        customer: { source_id: string };
        currency: string;
        line_items: LineItemWithTax[] | LineItemWithoutTax[] | LineItemWithExistingProduct[];
        pdf_invoice_free_text: string;
        pdf_invoice_subject: string;
        special_mention: string | null;
        discount: number;
        categories: CategoryObject[] | null;
        transactions_reference?: { banking_provider: string; provider_field_name: string; provider_field_value: string } | undefined;
        imputation_dates?: { start_date: string; end_date: string } | undefined;
    };
}
