// ---------------------------
// This file was generated by Nango (v0.54.0)
// You can version this file
// ---------------------------

export interface IdEntity {
    id: string;
}

export interface SuccessResponse {
    success: boolean;
}

export interface CreateUser {
    firstName: string;
    lastName: string;
    email: string;
}

export interface FreshdeskCreateUser {
    firstName: string;
    lastName: string;
    email: string;
    ticket_scope?: number;
    ticketScope?: 'globalAccess' | 'groupAccess' | 'restrictedAccess';
    occasional?: boolean;
    signature?: string;
    skill_ids?: number[];
    group_ids?: number[];
    role_ids?: number[];
    agent_type?: number;
    agentType?: 'support' | 'field' | 'collaborator';
    language?: string;
    time_zone?: string;
    focus_mode?: boolean;
}

export interface User {
    id: string;
    email: string;
    firstName: string;
    lastName: string;
}

export interface Contact {
    id: string;
    active: boolean;
    email: string;
    name: string;
    createdAt: string;
    updatedAt: string;
    companyId?: string | undefined;
    phone?: string | undefined | null;
    mobile?: string | undefined | null;
    jobTitle?: string | undefined | null;
}

export interface CreateContact {
    name: string;
    email?: string;
    phone?: string;
    mobile?: string;
    twitter_id?: { type: string; unique: true; required: true };
    unique_external_id?: { type: string; unique: true; required: true };
    other_emails?: any[];
    company_id?: number;
    view_all_tickets?: boolean;
    other_companies?: any[];
    address?: string;
    avatar?: Record<string, any>;
    custom_fields?: Record<string, any>;
    description?: string;
    job_title?: string;
    language?: string;
    tags?: any[];
    time_zone?: string;
    lookup_parameter?: string;
}

export interface Timestamps {
    created_at: string;
    updated_at: string;
}

export interface HierarchyData {
    id: number;
    name: string;
    language: string;
}

export interface HierarchyLevel {
    level: number;
    type: string;
    data: HierarchyData;
}

export interface SeoData {
    meta_title?: string | undefined;
    meta_description?: string | undefined;
    meta_keywords?: string | undefined;
}

export interface Article {
    id: number;
    created_at: string;
    updated_at: string;
    type: number;
    category_id: number;
    folder_id: number;
    hierarchy: HierarchyLevel[];
    thumbs_up: number;
    thumbs_down: number;
    hits: number;
    tags?: string[] | undefined;
    seo_data: SeoData;
    agent_id: number;
    title: string;
    description: string;
    description_text: string;
    status: number;
}

export interface Ticket {
    id: string;
    type: string;
    priority: number;
    request_id: number;
    response_id: number;
    source: number;
    subject: string;
    to_emails: string[] | null;
    created_at: string;
    updated_at: string;
    is_escalated: boolean;
}
