// Generated by ts-to-zod
import { z } from 'zod';

export const richPageInputSchema = z.object({
    pageId: z.string()
});

export const contentMetadataSchema = z.object({
    id: z.string(),
    path: z.string().optional(),
    type: z.union([z.literal('page'), z.literal('database')]),
    last_modified: z.string(),
    title: z.string().optional(),
    parent_id: z.union([z.string(), z.undefined()]).optional()
});

export const richPageSchema = z.object({
    id: z.string(),
    path: z.string(),
    title: z.string(),
    content: z.string(),
    contentType: z.string(),
    meta: z.record(z.any()),
    last_modified: z.string(),
    parent_id: z.union([z.string(), z.undefined()]).optional()
});

export const databaseInputSchema = z.object({
    databaseId: z.string()
});

export const rowEntrySchema = z.object({
    id: z.string(),
    row: z.record(z.any())
});

export const databaseSchema = z.object({
    id: z.string(),
    path: z.string(),
    title: z.string(),
    meta: z.record(z.any()),
    last_modified: z.string(),
    entries: z.array(rowEntrySchema)
});

export const notionCompleteDatabaseSchema = z.object({
    id: z.string(),
    row: z.record(z.any()),
    meta: z.object({
        databaseId: z.string(),
        path: z.string(),
        title: z.string(),
        last_modified: z.string()
    })
});

export const urlOrIdSchema = z.object({
    url: z.string().optional(),
    id: z.string().optional()
});

export const userSchema = z.object({
    id: z.string(),
    email: z.string().nullable(),
    firstName: z.string(),
    lastName: z.string(),
    isBot: z.boolean()
});
