// ---------------------------
// This file was generated by Nango (v0.63.0)
// You can version this file
// ---------------------------

export interface SyncMetadata_gusto_employees {
};

export interface GustoEmployee {
  id: string;
  uuid: string;
  first_name: string;
  last_name: string;
  email: string;
  work_email: string;
  phone: string;
  department: string;
  department_uuid: string;
  manager_uuid: string;
  version: string;
  terminated: boolean;
  onboarded: boolean;
  onboarding_status: string;
  date_of_birth: string;
  has_ssn: boolean;
  custom_fields: (string | string | string | string | string | string | string[])[];
  jobs: (string | string | string | string | boolean)[];
};

export interface SyncMetadata_gusto_unifiedemployees {
};

export interface StandardEmployee {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  displayName: string;
  employeeNumber: string;
  title: string;
  department: {  id: string;
  name: string;};
  employmentType: 'FULL_TIME' | 'PART_TIME' | 'CONTRACTOR' | 'INTERN' | 'TEMPORARY' | 'OTHER';
  employmentStatus: 'ACTIVE' | 'TERMINATED' | 'ON_LEAVE' | 'SUSPENDED' | 'PENDING';
  startDate: string;
  terminationDate: string;
  manager: {  id: string;
  firstName: string;
  lastName: string;
  email: string;};
  workLocation: {  name: string;
  type: 'OFFICE' | 'REMOTE' | 'HYBRID';
  primaryAddress: {  street: string;
  city: string;
  state: string;
  country: string;
  postalCode: string;
  type: 'WORK' | 'HOME';};};
  addresses: (string | string | string | string | string | 'WORK' | 'HOME')[];
  phones: ('WORK' | 'HOME' | 'MOBILE' | string)[];
  emails: ('WORK' | 'PERSONAL' | string)[];
  providerSpecific: {};
  createdAt: string;
  updatedAt: string;
};

export interface ActionInput_gusto_createemployee {
  firstName: string;
  lastName: string;
  email: string;
  middleInitial: string;
  preferredFirstName: string;
  dateOfBirth: string;
  ssn: string;
  selfOnboarding: boolean;
};

export interface ActionOutput_gusto_createemployee {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
};

export interface ActionInput_gusto_updateemployee {
  id: string;
  version: string;
  firstName: string;
  lastName: string;
  email: string;
  middleInitial: string;
  preferredFirstName: string;
  dateOfBirth: string;
  ssn: string;
  twoPercentShareholder: boolean;
};

export interface ActionOutput_gusto_updateemployee {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
};

export interface ActionInput_gusto_terminateemployee {
  id: string;
  effectiveDate: string;
  runTerminationPayroll: boolean;
};

export interface ActionOutput_gusto_terminateemployee {
  success: boolean;
};
