// ---------------------------
// This file was generated by Nango (v0.65.0)
// You can version this file
// ---------------------------

export interface Option {
    id: number;
    name: string;
}

export interface BamboohrField {
    id: string;
    type: string;
    name: string;
    alias?: string | undefined;
    options?: Option[] | undefined;
}

export interface BamboohrEmployee {
    id: string;
    employeeNumber: string;
    firstName: string;
    lastName: string;
    dateOfBirth: string;
    address1: string;
    bestEmail: string;
    workEmail: string;
    jobTitle: string;
    hireDate: string;
    supervisorId: string;
    supervisor: string;
    createdByUserId: string;
    department: string;
    division: string;
    employmentHistoryStatus: string;
    gender: string;
    country: string;
    city: string;
    location: string;
    state: string;
    maritalStatus: string;
    exempt: string;
    payRate: string;
    payType: string;
    payPer: string;
    ssn: string;
    workPhone: string;
    homePhone: string;
}

export interface BamboohrCreateEmployee {
    firstName: string;
    lastName: string;
    employeeNumber?: string | undefined;
    dateOfBirth?: string | undefined;
    address1?: string | undefined;
    bestEmail?: string | undefined;
    workEmail?: string | undefined;
    jobTitle?: string | undefined;
    hireDate?: string | undefined;
    supervisorId?: string | undefined;
    supervisor?: string | undefined;
    createdByUserId?: string | undefined;
    department?: string | undefined;
    division?: string | undefined;
    employmentHistoryStatus?: string | undefined;
    gender?: string | undefined;
    country?: string | undefined;
    city?: string | undefined;
    location?: string | undefined;
    state?: string | undefined;
    maritalStatus?: string | undefined;
    exempt?: string | undefined;
    payRate?: string | undefined;
    payType?: string | undefined;
    payPer?: string | undefined;
    ssn?: string | undefined;
    workPhone?: string | undefined;
    homePhone?: string | undefined;
}

export interface BamboohrUpdateEmployee {
    id: string;
    firstName?: string | undefined;
    lastName?: string | undefined;
    employeeNumber?: string | undefined;
    dateOfBirth?: string | undefined;
    address1?: string | undefined;
    bestEmail?: string | undefined;
    workEmail?: string | undefined;
    jobTitle?: string | undefined;
    hireDate?: string | undefined;
    supervisorId?: string | undefined;
    supervisor?: string | undefined;
    createdByUserId?: string | undefined;
    department?: string | undefined;
    division?: string | undefined;
    employmentHistoryStatus?: string | undefined;
    gender?: string | undefined;
    country?: string | undefined;
    city?: string | undefined;
    location?: string | undefined;
    state?: string | undefined;
    maritalStatus?: string | undefined;
    exempt?: string | undefined;
    payRate?: string | undefined;
    payType?: string | undefined;
    payPer?: string | undefined;
    ssn?: string | undefined;
    workPhone?: string | undefined;
    homePhone?: string | undefined;
}

export interface BamboohrResponseStatus {
    status: string;
}

export interface BamboohrCreateEmployeeResponse {
    status: string;
    id: string;
}

export interface StandardEmployeeEmail {
    email: string;
    type: string;
}

export interface StandardEmployeeWorkingHours {
    days: string[];
    hours: string[];
    time_zone: string;
}

export interface StandardEmployeeAddress {
    line1?: string | undefined;
    line2?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    postal_code?: string | undefined;
    country?: string | undefined;
    type: string;
}

export interface StandardEmployeeLocation {
    name?: string | undefined;
    type: string;
    address?: StandardEmployeeAddress | undefined;
}

export interface StandardEmployeePhone {
    type: 'WORK' | 'HOME' | 'MOBILE';
    number: string;
}

export interface StandardEmployeeBankAccount {
    bank_name?: string | undefined;
    account_number?: string | undefined;
    routing_number?: string | undefined;
    type?: string | undefined;
    currency?: string | undefined;
}

export interface StandardEmployeeManager {
    id: string;
    first_name: string;
    last_name: string;
    email?: string | undefined;
}

export interface Address {
    street?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    country?: string | undefined;
    postalCode?: string | undefined;
    type: 'WORK' | 'HOME';
}

export interface Phone {
    type: 'WORK' | 'HOME' | 'MOBILE';
    number: string;
}

export interface Email {
    type: 'WORK' | 'PERSONAL';
    address: string;
}

export interface StandardEmployee {
    id: string;
    firstName: string;
    lastName: string;
    email: string;
    displayName: string;
    employeeNumber?: string | undefined;
    title?: string | undefined;
    department: { id: string; name: string };
    employmentType: 'FULL_TIME' | 'PART_TIME' | 'CONTRACTOR' | 'INTERN' | 'TEMPORARY' | 'OTHER';
    employmentStatus: 'ACTIVE' | 'TERMINATED' | 'ON_LEAVE' | 'SUSPENDED' | 'PENDING';
    startDate: string;
    terminationDate?: string | undefined | undefined;
    manager?: { id: string; firstName: string; lastName: string; email: string } | undefined;
    workLocation: {
        name: string;
        type: 'OFFICE' | 'REMOTE' | 'HYBRID';
        primaryAddress?:
            | {
                  street?: string | undefined;
                  city?: string | undefined;
                  state?: string | undefined;
                  country?: string | undefined;
                  postalCode?: string | undefined;
                  type: 'WORK' | 'HOME';
              }
            | undefined;
    };
    addresses?: Address[] | undefined;
    phones?: Phone[] | undefined;
    emails?: Email[] | undefined;
    providerSpecific: { [key: string]: any };
    createdAt: string;
    updatedAt: string;
}

export type Anonymous_bamboohrbasic_action_fetchfields_output = BamboohrField[];
