import { z } from 'zod';
import { createAction } from 'nango';
import type { ProxyConfiguration } from 'nango';

const RatingSchema = z.object({
    positive: z.boolean().describe('Whether the user rated this correlation positively.'),
    rating_type: z.number().describe('Provider-specific numeric code for the rating type.'),
    rating: z.string().describe('Human-readable rating label. Example: "Useful".')
});

const CorrelationSchema = z.object({
    date: z.string().describe('Date the correlation was generated, as YYYY-MM-DD.'),
    period: z.number().describe('Number of days covered by the correlation window.'),
    offset: z.number().describe('Offset in days used when computing the correlation.'),
    attribute: z.string().describe('First attribute in the correlation. Example: "sleep".'),
    attribute2: z.string().describe('Second attribute in the correlation. Example: "workouts_min".'),
    value: z.number().describe('Correlation coefficient between -1 and 1.'),
    p: z.number().describe('P-value indicating the statistical significance of the correlation.'),
    percentage: z.number().describe('Correlation strength expressed as a percentage.'),
    stars: z.number().describe('Confidence rating from 1 to 5 stars.'),
    second_person: z.string().describe('Human-readable sentence describing the correlation.'),
    second_person_elements: z.array(z.string()).describe('Sentence fragments that make up the human-readable description.'),
    attribute_category: z.string().nullable().describe('Sub-category of the attribute when the correlation covers a subset of its data, otherwise null.'),
    strength_description: z.string().describe('Human-readable description of the relationship strength. Example: "Quite often go together".'),
    stars_description: z.string().describe('Human-readable description of the confidence level. Example: "Certain to be related".'),
    description: z.string().nullable().describe('Additional explanation about the correlation when available, otherwise null.'),
    occurrence: z.string().nullable().describe('How commonly the correlation occurs when available, otherwise null.'),
    rating: RatingSchema.nullable().describe('User-submitted rating for the correlation when present, otherwise null.')
});

const InputSchema = z
    .object({
        page: z.number().int().min(1).optional().describe('Page index to fetch, starting at 1. Defaults to 1.'),
        limit: z.number().int().min(1).max(100).optional().describe('Number of correlations to return per page. Maximum is 100.'),
        strong: z.boolean().optional().describe('When true, return only correlations above a certain relationship strength.'),
        confident: z.boolean().optional().describe('When true, return only correlations with five-star confidence.'),
        attribute: z.string().optional().describe('Filter correlations to those involving this attribute name. Example: "sleep".')
    })
    .describe('Filters and paging options for listing correlations generated by Exist.');

const OutputSchema = z
    .object({
        count: z.number().describe('Total number of correlations matching the filters across all pages.'),
        next: z.string().nullable().describe('Full URL of the next page of results, or null when this is the last page.'),
        previous: z.string().nullable().describe('Full URL of the previous page of results, or null when this is the first page.'),
        results: z.array(CorrelationSchema).describe('Correlations returned on this page.')
    })
    .describe('A page of correlations generated by Exist in the last week.');

/**
 * @tags: [read]
 * @tagReason: Reads the correlations generated by Exist; it does not mutate any provider data.
 * @pitfalls: Only correlations generated in the last week are returned, so results are a rolling weekly snapshot rather than accumulated history; results are also limited to the connection's read scopes, and filtering by an attribute with no correlations returns an empty result set rather than an error.
 */
const action = createAction({
    description: 'List correlations Exist has generated in the last week, optionally filtered by attribute, strength, or confidence.',
    version: '1.0.0',
    input: InputSchema,
    output: OutputSchema,

    exec: async (nango, input): Promise<z.infer<typeof OutputSchema>> => {
        const config: ProxyConfiguration = {
            // https://developer.exist.io/reference/correlations
            endpoint: '/api/2/correlations/',
            params: {
                ...(input.page !== undefined && { page: input.page }),
                ...(input.limit !== undefined && { limit: input.limit }),
                ...(input.strong === true && { strong: 1 }),
                ...(input.confident === true && { confident: 1 }),
                ...(input.attribute !== undefined && { attribute: input.attribute })
            },
            retries: 3
        };

        const response = await nango.get(config);
        const parsed = OutputSchema.parse(response.data);

        return parsed;
    }
});

export type NangoActionLocal = Parameters<(typeof action)['exec']>[0];
export default action;
