// Generated by ts-to-zod
import { z } from 'zod';

export const userSchema = z.object({
    id: z.string(),
    email: z.string(),
    firstName: z.string(),
    lastName: z.string()
});

export const createUserSchema = z.object({
    firstName: z.string(),
    lastName: z.string(),
    email: z.string()
});

export const keeperCreateUserSchema = z.object({
    firstName: z.string(),
    lastName: z.string(),
    email: z.string(),
    external_id: z.string().optional(),
    phone: z.string().optional(),
    avatar: z.string().optional(),
    signed_up_at: z.number().optional(),
    last_seen_at: z.number().optional(),
    owner_id: z.string().optional(),
    unsubscribed_from_emails: z.boolean().optional()
});
