// ---------------------------
// This file was generated by Nango (v0.57.3)
// You can version this file
// ---------------------------

export interface IdEntity {
  id: string;
};

export interface DocumentMetadata {
  files: string[] | undefined;
  folders: string[] | undefined;
};

export interface Document {
  id: string;
  url: string;
  title: string;
  mimeType: string;
  updatedAt: string;
};

export interface Folder {
  id: string;
  url: string;
  title: string;
  mimeType: string;
  updatedAt: string;
};

export interface JSONSpreadsheet {
  spreadsheetId: string;
  properties: Record<string, any>;
  sheets: Record<string, any>[];
  namedRanges: Record<string, any>[];
  spreadsheetUrl: string;
  developerMetadata: Record<string, any>[];
  dataSources: Record<string, any>[];
  dataSourceSchedules: Record<string, any>[];
};

export interface JSONDocument {
  documentId: string;
  title: string;
  url: string;
  tabs: Record<string, any>[];
  revisionId: string;
  suggestionsViewMode: 'DEFAULT_FOR_CURRENT_ACCESS' | 'SUGGESTIONS_INLINE' | 'PREVIEW_SUGGESTIONS_ACCEPTED' | 'PREVIEW_WITHOUT_SUGGESTIONS';
  body: Record<string, any>;
  headers: Record<string, any>;
  footers: Record<string, any>;
  footnotes: Record<string, any>;
  documentStyle: Record<string, any>;
  suggestedDocumentStyleChanges: Record<string, any>;
  namedStyles: Record<string, any>;
  suggestedNamedStylesChanges: Record<string, any>;
  lists: Record<string, any>;
  namedRanges: Record<string, any>;
  inlineObjects: Record<string, any>;
  positionedObjects: Record<string, any>;
};

export interface FetchFoldersInput {
  id?: string;
  cursor?: string | undefined;
};

export interface GoogleDocument {
  id: string;
  name: string;
  mimeType: string;
  parents?: string[];
  modifiedTime?: string;
  createdTime?: string;
  webViewLink?: string;
  kind?: string;
};

export interface GoogleDriveFolder {
  folders?: GoogleDocument[];
  cursor?: string | undefined;
};

export interface UploadFileInput {
  content: string;
  name: string;
  mimeType: string;
  folderId?: string | undefined;
  description?: string | undefined;
  isBase64?: boolean | undefined;
};

export interface FolderContentInput {
  id?: string;
  cursor?: string;
};

export interface FolderContent {
  files: GoogleDocument[];
  folders: GoogleDocument[];
  cursor?: string;
};

/** @deprecated It is recommended to use a Model */
export type Anonymous_googledrive_action_fetchdocument_output = string
