// ---------------------------
// This file was generated by Nango (v0.64.1)
// You can version this file
// ---------------------------

export interface SyncMetadata_jira_issues {
  projectIdsToSync: (string)[];
  cloudId: string;
  baseUrl: string;
  timeZone: string;
};

export interface Issue {
  id: string;
  createdAt: string;
  updatedAt: string;
  key: string;
  summary: string;
  issueType: string;
  status: string;
  assignee: string | null;
  url: string;
  webUrl: string;
  projectId: string;
  projectKey: string;
  projectName: string;
  comments: (string | string | string | {  accountId: string | null;
  active: boolean;
  displayName: string;
  emailAddress: string | null;} | {})[];
};

export interface SyncMetadata_jira_projects {
  projectIdsToSync: (string)[];
  cloudId: string;
  baseUrl: string;
  timeZone: string;
};

export interface Project {
  id: string;
  key: string;
  name: string;
  url: string;
  projectTypeKey: string;
  webUrl: string;
};

export interface SyncMetadata_jira_issuetypes {
  projectIdsToSync: (string)[];
  cloudId: string;
  baseUrl: string;
  timeZone: string;
};

export interface IssueType {
  projectId: string;
  id: string;
  name: string;
  description: string | null;
  url: string;
};

export interface ActionInput_jira_createissue {
  summary: string;
  description: string;
  assignee: string;
  labels: string[];
  project: string;
  issueType: string;
};

export interface ActionOutput_jira_createissue {
  id: string;
  key: string;
  self: string;
};
