// ---------------------------
// This file was generated by Nango (v0.53.0)
// You can version this file
// ---------------------------

export interface IdEntity {
    id: string;
}

export interface SuccessResponse {
    success: boolean;
}

export interface ActionResponseError {
    message: string;
}

export interface User {
    id: number;
    firstname: string;
    lastname: string;
    meta: Record<string, any> | null;
}

export interface AssigneeUser {
    id: number;
    firstname: string;
    lastname: string;
    meta: Record<string, any> | null;
    email: string;
    name: string;
    bio: string | null;
}

export interface RecieverSender {
    id: number;
    firstname: string;
    lastname: string;
    meta: Record<string, any> | null;
    email: string | null;
    name: string | null;
}

export interface Attachment {
    url: string;
    name: string;
    size: number | null;
    content_type: string;
    public: boolean;
    extra: string | null;
}

export interface Message {
    id: number;
    uri: string;
    message_id: string | null;
    integration_id: number | null;
    rule_id: number | null;
    external_id: string | null;
    ticket_id: number;
    channel:
        | 'aircall'
        | 'api'
        | 'chat'
        | 'contact_form'
        | 'email'
        | 'facebook'
        | 'facebook-mention'
        | 'facebook-messenger'
        | 'facebook-recommendations'
        | 'help-center'
        | 'instagram-ad-comment'
        | 'instagram-comment'
        | 'instagram-direct-message'
        | 'instagram-mention'
        | 'internal-note'
        | 'phone'
        | 'sms'
        | 'twitter'
        | 'twitter-direct-message'
        | 'whatsapp'
        | 'yotpo-review';
    via:
        | 'aircall'
        | 'api'
        | 'chat'
        | 'contact_form'
        | 'email'
        | 'facebook'
        | 'facebook-mention'
        | 'facebook-messenger'
        | 'facebook-recommendations'
        | 'form'
        | 'gorgias_chat'
        | 'help-center'
        | 'helpdesk'
        | 'instagram'
        | 'instagram-ad-comment'
        | 'instagram-comment'
        | 'instagram-direct-message'
        | 'instagram-mention'
        | 'internal-note'
        | 'offline_capture'
        | 'phone'
        | 'rule'
        | 'self_service'
        | 'shopify'
        | 'sms'
        | 'twilio'
        | 'twitter'
        | 'twitter-direct-message'
        | 'whatsapp'
        | 'yotpo'
        | 'yotpo-review'
        | 'zendesk';
    subject: string | null;
    body_text: string | null;
    body_html: string | null;
    stripped_text: string | null;
    stripped_html: string | null;
    stripped_signature: string | null;
    public: boolean;
    from_agent: boolean;
    sender: RecieverSender;
    receiver: RecieverSender | null;
    attachments: Attachment[] | null;
    meta: Record<string, any> | null;
    headers: Record<string, any> | null;
    actions: any[] | null;
    macros: any[] | null;
    created_datetime: string | null;
    opened_datetime: string | null;
    failed_datetime: string | null;
    last_sending_error: Record<string, any> | null;
    deleted_datetime: string | null;
    replied_by?: string | null | undefined;
    replied_to?: string | null | undefined;
}

export interface Ticket {
    id: number;
    assignee_user: AssigneeUser | null;
    channel:
        | 'aircall'
        | 'api'
        | 'chat'
        | 'contact_form'
        | 'email'
        | 'facebook'
        | 'facebook-mention'
        | 'facebook-messenger'
        | 'facebook-recommendations'
        | 'help-center'
        | 'instagram-ad-comment'
        | 'instagram-comment'
        | 'instagram-direct-message'
        | 'instagram-mention'
        | 'internal-note'
        | 'phone'
        | 'sms'
        | 'twitter'
        | 'twitter-direct-message'
        | 'whatsapp'
        | 'yotpo-review';
    closed_datetime: string | null;
    created_datetime: string | null;
    excerpt?: string | undefined;
    external_id: string | null;
    from_agent: boolean;
    integrations?: any[] | null | undefined;
    is_unread: boolean;
    language: string | null;
    last_message_datetime: string | null;
    last_received_message_datetime: string | null;
    messages_count?: number | undefined;
    messages: Message[];
    meta: Record<string, any> | null;
    opened_datetime: string | null;
    snooze_datetime: string | null;
    status: 'open' | 'closed';
    subject: string | null;
    tags: {
        id: number;
        name: string;
        uri: string | null;
        decoration: Record<string, any> | null;
        created_datetime: string | null;
        deleted_datetime?: string | null | undefined;
    }[];
    spam: boolean | null;
    trashed_datetime: string | null;
    updated_datetime: string | null;
    via:
        | 'aircall'
        | 'api'
        | 'chat'
        | 'contact_form'
        | 'email'
        | 'facebook'
        | 'facebook-mention'
        | 'facebook-messenger'
        | 'facebook-recommendations'
        | 'form'
        | 'gorgias_chat'
        | 'help-center'
        | 'helpdesk'
        | 'instagram'
        | 'instagram-ad-comment'
        | 'instagram-comment'
        | 'instagram-direct-message'
        | 'instagram-mention'
        | 'internal-note'
        | 'offline_capture'
        | 'phone'
        | 'rule'
        | 'self_service'
        | 'shopify'
        | 'sms'
        | 'twilio'
        | 'twitter'
        | 'twitter-direct-message'
        | 'whatsapp'
        | 'yotpo'
        | 'yotpo-review'
        | 'zendesk';
    uri: string;
}

export interface CreateTicketMessage {
    attachments: { url: string; name: string; size: number; content_type: string }[];
    body_html: string;
    body_text: string;
    id: string;
}

export interface CreateTicketInput {
    customer: { phone_number: string; email?: string | undefined };
    ticket: { messages: CreateTicketMessage[] };
}

export interface CreateUser {
    firstName: string;
    lastName: string;
    email: string;
}

export interface GorgiasCreateUser {
    firstName: string;
    lastName: string;
    email: string;
    role: 'admin' | 'agent' | 'basic-agent' | 'lite-agent' | 'observer-agent';
}

export interface GorgiasUser {
    id: string;
    firstName: string;
    lastName: string;
    email: string;
}
