// ---------------------------
// This file was generated by Nango (v0.57.3)
// You can version this file
// ---------------------------

export interface PipeDriveActivity {
  id: number;
  done: boolean;
  type: string;
  duration: Date;
  subject: string;
  company_id: number;
  user_id: number;
  conference_meeting_client: string;
  conference_meeting_url: string;
  conference_meeting_id: string;
  due_date: Date;
  due_time: Date;
  busy_flag: boolean;
  add_time: Date;
  marked_as_done_time: Date;
  public_description: string;
  location: string;
  org_id: number;
  person_id: number;
  deal_id: number;
  active_flag: boolean;
  update_time: Date;
  update_user_id: number;
  source_timezone: string;
  lead_id: string;
  location_subpremise: string;
  location_street_number: string;
  location_route: string;
  location_sublocality: string;
  location_locality: string;
  location_admin_area_level_1: string;
  location_admin_area_level_2: string;
  location_country: string;
  location_postal_code: string;
  location_formatted_address: string;
  project_id: number;
};

export interface PipeDriveDeal {
  id: number;
  creator_user_id: number;
  user_id: number;
  person_id: number;
  org_id: number;
  stage_id: number;
  title: string;
  value: number;
  currency: string;
  add_time: Date;
  update_time: Date;
  status: string;
  probability: string;
  lost_reason: string;
  visible_to: string;
  close_time: Date;
  pipeline_id: number;
  won_time: Date;
  lost_time: Date;
  expected_close_date: Date;
  label: string;
};

export interface PipeDriveOrganization {
  id: number;
  owner_id: number;
  name: string;
  active_flag: boolean;
  update_time: Date;
  delete_time: Date;
  add_time: Date;
  visible_to: string;
  label: number;
  address: number;
  address_subpremise: string;
  address_street_number: string;
  address_route: string;
  address_sublocality: string;
  address_locality: string;
  address_admin_area_level_1: string;
  address_admin_area_level_2: string;
  address_country: string;
  address_postal_code: string;
  address_formatted_address: string;
  cc_email: string;
};

export interface PipeDrivePerson {
  id: number;
  active_flag: boolean;
  owner_id: number;
  org_id: number;
  name: string;
  phone: string[];
  email: string[];
  update_time: Date;
  delete_time: Date;
  add_time: Date;
  visible_to: string;
  picture_id: number;
  label: number;
  cc_email: string;
};
