// Generated by ts-to-zod
import { z } from 'zod';

export const emailEntitySchema = z.object({
    email: z.string().email()
});

export const successResponseSchema = z.object({
    success: z.boolean()
});

export const userSchema = z.object({
    id: z.string(),
    email: z.string().email(),
    firstName: z.string(),
    lastName: z.string()
});

export const createUserSchema = z.object({
    firstName: z.string(),
    lastName: z.string(),
    email: z.string().email()
});

export const dialpadCreateUserSchema = createUserSchema.extend({
    license: z.string().optional(),
    officeId: z.string().optional(),
    autoAssign: z.boolean().optional()
});

export const deleteUserSchema = z.object({
    email: z.string().email() //todo: verify the type from zod
})