// Generated by ts-to-zod
import { z } from 'zod';

export const bitdefenderCompanySchema = z.object({
    id: z.string(),
    name: z.string(),
    type: z.number(),
    country: z.union([z.string(), z.undefined()]),
    createdAt: z.string(),
    subscribedServices: z.object({
        endpoint: z.boolean(),
        exchange: z.boolean(),
        network: z.boolean(),
        sos: z.boolean()
    }),
    raw_json: z.string()
});

export const bitdefenderEndpointSchema = z.object({
    id: z.string(),
    name: z.string(),
    fqdn: z.string(),
    groupId: z.string(),
    isManaged: z.boolean(),
    machineType: z.number(),
    os: z.object({
        type: z.string(),
        version: z.string(),
        displayName: z.string()
    }),
    ip: z.array(z.string()),
    macs: z.array(z.string()),
    ssid: z.union([z.string(), z.undefined()]),
    label: z.union([z.string(), z.undefined()]),
    state: z.object({
        managedWithClient: z.boolean(),
        managedWithoutClient: z.boolean(),
        pendingUninstall: z.boolean(),
        needsReboot: z.boolean(),
        canManage: z.boolean(),
        agentVersion: z.string(),
        lastUpdate: z.string(),
        online: z.boolean()
    }),
    raw_json: z.string()
});

export const bitdefenderQuarantineItemSchema = z.object({
    id: z.string(),
    name: z.string(),
    hash: z.string(),
    filePath: z.string(),
    endpointId: z.string(),
    endpointName: z.string(),
    date: z.string(),
    malwareType: z.string(),
    malwareName: z.string(),
    moduleName: z.string(),
    impact: z.number(),
    size: z.number(),
    isPasswordProtectedArchive: z.boolean(),
    restored: z.boolean(),
    deleted: z.boolean(),
    raw_json: z.string()
});

export const companyIdInputSchema = z.object({
    id: z.string()
});

export const quarantineItemIdInputSchema = z.object({
    id: z.string()
});

export const restoreQuarantineItemOutputSchema = z.object({
    success: z.boolean(),
    message: z.union([z.string(), z.undefined()]),
    raw_json: z.string()
});
