// ---------------------------
// This file was generated by Nango (v0.58.3)
// You can version this file
// ---------------------------

export interface UserNamEntity {
    userName: string;
}

export interface SuccessResponse {
    success: boolean;
}

export interface ActionResponseError {
    message: string;
}

export interface User {
    id: string;
    firstName: string;
    lastName: string;
    email: string;
}

export interface CreateUser {
    firstName: string;
    lastName: string;
    email: string;
}

export interface AWSCreateUser {
    firstName: string;
    lastName: string;
    email: string;
    userName?: string;
}
