// ---------------------------
// This file was generated by Nango (v0.53.0)
// You can version this file
// ---------------------------

export interface AlgoliaContact {
    createdAt: Date;
    taskID: number;
    objectID: string;
}

export interface AlgoliaCreateContactInput {
    name: string;
    company: string;
    email: string;
}
