import { z } from 'zod';
import { createAction } from 'nango';
import type { ProxyConfiguration } from 'nango';

const RateLimitInputSchema = z
    .object({
        count: z.number().int().positive().describe('Maximum number of events accepted within the time window. Example: 1000'),
        window: z.number().int().positive().describe('Length of the rate-limit time window in seconds. Example: 7200')
    })
    .describe('Rate limit capping how many events this key may send per time window');

const InputSchema = z
    .object({
        organizationIdOrSlug: z.string().describe('ID or slug of the organization that owns the project. Example: "nangodev"'),
        projectIdOrSlug: z.string().describe('ID or slug of the project the key is created for. Example: "nango-seed-project"'),
        name: z.string().optional().describe('Human-readable name of the key. Auto-generated by Sentry when omitted. Example: "Nango Seed Key"'),
        rateLimit: RateLimitInputSchema.optional(),
        useCase: z.enum(['user', 'profiling', 'tempest', 'demo']).optional().describe('Intended use case of the key. Example: "user"')
    })
    .describe('Parameters for creating a new client key (DSN) on a Sentry project');

const RateLimitSchema = z.object({
    window: z.number(),
    count: z.number()
});

const ProjectKeySchema = z.object({
    id: z.string(),
    name: z.string(),
    label: z.string(),
    public: z.string(),
    secret: z.string(),
    projectId: z.number(),
    isActive: z.boolean(),
    rateLimit: RateLimitSchema.nullable(),
    dsn: z.object({
        secret: z.string(),
        public: z.string(),
        csp: z.string().optional(),
        security: z.string().optional(),
        minidump: z.string().optional(),
        nel: z.string().optional(),
        playstation: z.string().optional(),
        integration: z.string().optional(),
        otlp_traces: z.string().optional(),
        otlp_logs: z.string().optional(),
        unreal: z.string().optional(),
        cdn: z.string().optional(),
        crons: z.string().optional()
    }),
    browserSdkVersion: z.string().optional(),
    dateCreated: z.string()
});

const DsnOutputSchema = z
    .object({
        public: z.string().describe('Public DSN used by Sentry SDKs to send events. Example: "https://<public-key>@o123.ingest.us.sentry.io/456"'),
        secret: z.string().describe('Legacy secret DSN including the secret key'),
        csp: z.string().optional().describe('CSP report endpoint URL for this key'),
        security: z.string().optional().describe('Security (CSP/Expect-CT) report endpoint URL for this key'),
        minidump: z.string().optional().describe('Minidump upload endpoint URL for this key'),
        nel: z.string().optional().describe('Network Error Logging (NEL) report endpoint URL for this key'),
        unreal: z.string().optional().describe('Unreal Engine crash report endpoint URL for this key'),
        cdn: z.string().optional().describe('CDN URL of the Sentry browser SDK loader bundled with this key'),
        crons: z.string().optional().describe('Cron check-in endpoint URL template for this key')
    })
    .describe('Endpoint URLs derived from this client key');

const RateLimitOutputSchema = z
    .object({
        window: z.number().describe('Length of the rate-limit time window in seconds'),
        count: z.number().describe('Maximum number of events accepted within the window')
    })
    .describe('Rate limit applied to this key; omitted when no limit is set');

const OutputSchema = z
    .object({
        id: z.string().describe('ID of the created client key (same value as the public key). Example: "60120449b6b1d5e45f75561e6dabd80b"'),
        name: z.string().describe('Name of the key. Example: "Nango Seed Key"'),
        label: z.string().describe('Display label of the key'),
        public: z.string().describe('Public component of the key, embedded in DSNs'),
        secret: z.string().describe('Secret component of the key, generated by the server'),
        projectId: z.number().describe('Numeric ID of the project the key belongs to. Example: 4505281256090153'),
        isActive: z.boolean().describe('Whether the key is active and accepts events'),
        rateLimit: RateLimitOutputSchema.optional(),
        dsn: DsnOutputSchema,
        browserSdkVersion: z.string().optional().describe('Default browser SDK version served by the CDN loader. Example: "7.x"'),
        dateCreated: z.string().describe('ISO 8601 creation timestamp of the key. Example: "2026-09-29T12:00:00.000000Z"')
    })
    .describe('The created Sentry client key with its DSN endpoints');

/**
 * @tags: [write]
 * @tagReason: Creates a new client key on the provider; reads nothing and deletes or revokes nothing.
 * @pitfalls: Requires an auth token with project:write or project:admin scope; other tokens receive a 403. Repeated calls with the same name create additional keys with freshly generated credentials — Sentry does not deduplicate by name.
 */
const action = createAction({
    description: 'Create an additional client key (DSN) for a project.',
    version: '1.0.0',
    input: InputSchema,
    output: OutputSchema,
    scopes: ['project:write'],

    exec: async (nango, input): Promise<z.infer<typeof OutputSchema>> => {
        const config: ProxyConfiguration = {
            // https://docs.sentry.io/api/projects/create-a-new-client-key/
            endpoint: `/0/projects/${encodeURIComponent(input.organizationIdOrSlug)}/${encodeURIComponent(input.projectIdOrSlug)}/keys/`,
            data: {
                ...(input.name !== undefined && { name: input.name }),
                ...(input.rateLimit !== undefined && { rateLimit: { count: input.rateLimit.count, window: input.rateLimit.window } }),
                ...(input.useCase !== undefined && { useCase: input.useCase })
            },
            // Not idempotent: no idempotency key exists, and retrying a lost response would create duplicate keys.
            // eslint-disable-next-line @nangohq/custom-integrations-linting/proxy-call-retries -- non-idempotent create: retries must stay 0
            retries: 0
        };

        const response = await nango.post(config);

        if (!response.data) {
            throw new nango.ActionError({
                type: 'create_failed',
                message: 'Sentry returned an empty response when creating the project key',
                organizationIdOrSlug: input.organizationIdOrSlug,
                projectIdOrSlug: input.projectIdOrSlug
            });
        }

        const key = ProjectKeySchema.parse(response.data);

        return {
            id: key.id,
            name: key.name,
            label: key.label,
            public: key.public,
            secret: key.secret,
            projectId: key.projectId,
            isActive: key.isActive,
            ...(key.rateLimit != null && { rateLimit: { window: key.rateLimit.window, count: key.rateLimit.count } }),
            dsn: {
                public: key.dsn.public,
                secret: key.dsn.secret,
                ...(key.dsn.csp !== undefined && { csp: key.dsn.csp }),
                ...(key.dsn.security !== undefined && { security: key.dsn.security }),
                ...(key.dsn.minidump !== undefined && { minidump: key.dsn.minidump }),
                ...(key.dsn.nel !== undefined && { nel: key.dsn.nel }),
                ...(key.dsn.unreal !== undefined && { unreal: key.dsn.unreal }),
                ...(key.dsn.cdn !== undefined && { cdn: key.dsn.cdn }),
                ...(key.dsn.crons !== undefined && { crons: key.dsn.crons })
            },
            ...(key.browserSdkVersion !== undefined && { browserSdkVersion: key.browserSdkVersion }),
            dateCreated: key.dateCreated
        };
    }
});

export type NangoActionLocal = Parameters<(typeof action)['exec']>[0];
export default action;
