// ---------------------------
// This file was generated by Nango (v0.66.0)
// You can version this file
// ---------------------------

export interface SyncMetadata_google_calendar_events {
  calendarsToSync: string[];
  timeMin?: string | undefined;
  timeMax?: string | undefined;
  singleEvents?: boolean | undefined;
};

export interface GoogleCalendarEvent {
  kind: string;
  etag: string;
  id: string;
  status: string;
  htmlLink: string;
  created: string;
  updated: string;
  summary: string;
  description?: string | undefined;
  location?: string | undefined;
  colorId?: string | undefined;
  creator?: {  id?: string | undefined;
  email?: string | undefined;
  displayName?: string | undefined;
  self?: boolean | undefined;} | undefined;
  organizer?: {  id?: string | undefined;
  email?: string | undefined;
  displayName?: string | undefined;
  self?: boolean | undefined;} | undefined;
  start: {  date?: string | undefined;
  dateTime?: string | undefined;
  timeZone?: string | undefined;};
  end: {  date?: string | undefined;
  dateTime?: string | undefined;
  timeZone?: string | undefined;};
  endTimeUnspecified?: boolean | undefined;
  recurrence?: string[] | undefined;
  recurringEventId?: string | undefined;
  originalStartTime?: {  date?: string | undefined;
  dateTime?: string | undefined;
  timeZone?: string | undefined;} | undefined;
  transparency?: string | undefined;
  visibility?: string | undefined;
  iCalUID?: string | undefined;
  sequence?: number | undefined;
  attendees?: ({  id?: string | undefined;
  email?: string | undefined;
  displayName?: string | undefined;
  organizer?: boolean | undefined;
  self?: boolean | undefined;
  resource?: boolean | undefined;
  optional?: boolean | undefined;
  responseStatus?: string | undefined;
  comment?: string | undefined;
  additionalGuests?: number | undefined;})[] | undefined;
  attendeesOmitted?: boolean | undefined;
  extendedProperties?: {  private?: {} | undefined;
  shared?: {} | undefined;} | undefined;
  hangoutLink?: string | undefined;
  conferenceData?: {  createRequest?: {  requestId: string;
  conferenceSolutionKey: {  type: string;};
  status: {  statusCode: string;};} | undefined;
  entryPoints?: ({  entryPointType: string;
  uri?: string | undefined;
  label?: string | undefined;
  pin?: string | undefined;
  accessCode?: string | undefined;
  meetingCode?: string | undefined;
  passcode?: string | undefined;
  password?: string | undefined;
  regionCode?: string | undefined;})[] | undefined;
  conferenceSolution?: {  key: {  type: string;};
  name: string;
  iconUri: string;} | undefined;
  conferenceId?: string | undefined;
  signature?: string | undefined;
  notes?: string | undefined;
  parameters?: {  addOnParameters?: {  parameters?: {} | undefined;} | undefined;} | undefined;} | undefined;
  gadget?: {  type?: string | undefined;
  title?: string | undefined;
  link?: string | undefined;
  iconLink?: string | undefined;
  width?: number | undefined;
  height?: number | undefined;
  display?: string | undefined;
  preferences?: {} | undefined;} | undefined;
  anyoneCanAddSelf?: boolean | undefined;
  guestsCanInviteOthers?: boolean | undefined;
  guestsCanModify?: boolean | undefined;
  guestsCanSeeOtherGuests?: boolean | undefined;
  privateCopy?: boolean | undefined;
  locked?: boolean | undefined;
  reminders?: {  useDefault: boolean;
  overrides?: ({  method: string;
  minutes: number;})[] | undefined;} | undefined;
  outOfOfficeProperties?: {  autoDeclineMode?: string | undefined;
  declineMessage?: string | undefined;} | undefined;
  source?: {  url?: string | undefined;
  title?: string | undefined;} | undefined;
  workingLocationProperties?: {  type: string;
  homeOffice?: any | undefined;
  customLocation?: {  label?: string | undefined;} | undefined;
  officeLocation?: {  buildingId?: string | undefined;
  floorId?: string | undefined;
  floorSectionId?: string | undefined;
  deskId?: string | undefined;
  label?: string | undefined;} | undefined;} | undefined;
  attachments?: ({  fileUrl: string;
  title?: string | undefined;
  mimeType?: string | undefined;
  iconLink?: string | undefined;
  fileId?: string | undefined;})[] | undefined;
  eventType?: string | undefined;
};

export interface SyncMetadata_google_calendar_calendars {
};

export interface GoogleCalendar {
  kind: string;
  etag: string;
  id: string;
  summary: string;
  description: string;
  location: string;
  timeZone: string;
  summaryOverride: string;
  colorId: string;
  backgroundColor: string;
  foregroundColor: string;
  hidden: boolean;
  selected: boolean;
  accessRole: string;
  defaultReminders: ({  method: string;
  minutes: number;})[];
  notificationSettings: {  notifications: ({  type: string;
  method: string;})[];};
  primary: boolean;
  deleted: boolean;
  conferenceProperties: {  allowedConferenceSolutionTypes: string[];};
};

export type ActionInput_google_calendar_whoami = void

export interface ActionOutput_google_calendar_whoami {
  id: string;
  email: string;
};

export type ActionInput_google_calendar_settings = void

export interface ActionOutput_google_calendar_settings {
  settings: ({  kind: string;
  etag: string;
  id: string;
  value: string;})[];
};
