import { z } from 'zod';
import { createAction } from 'nango';

const InputSchema = z.object({
    integrationId: z.string().describe('The ID of the integration to delete. Example: "6286478263646"'),
    clientRequestId: z
        .string()
        .describe(
            'A unique identifier generated by you to allow troubleshooting. Valid characters are letters, numbers, dashes and underscores. Example: "client-request-1"'
        )
});

const ProviderResponseSchema = z.object({
    requestId: z.string().optional(),
    clientRequestId: z.string().nullish(),
    errors: z.array(z.string()).nullish()
});

const OutputSchema = z.object({
    requestId: z.string().optional(),
    clientRequestId: z.string().nullish(),
    errors: z.array(z.string()).nullish()
});

const AxiosErrorSchema = z.object({
    status: z.number().optional(),
    response: z
        .object({
            data: z.unknown().optional()
        })
        .optional()
});

const action = createAction({
    description: 'Delete a registered generic CRM integration from Gong.',
    version: '1.0.2',
    input: InputSchema,
    output: OutputSchema,
    scopes: ['api:crm:integration:delete'],

    exec: async (nango, input): Promise<z.infer<typeof OutputSchema>> => {
        let response;
        // @allowTryCatch
        // The Gong API may return 401 (missing scope) or 404 (plan-gated / missing integration).
        // We catch these to translate them into actionable outputs instead of hard failures.
        try {
            response = await nango.proxy({
                // https://help.gong.io/apidocs/delete-a-generic-crm-integration-v2crmintegrations-1
                method: 'DELETE',
                endpoint: '/v2/crm/integrations',
                params: {
                    integrationId: input.integrationId,
                    clientRequestId: input.clientRequestId
                },
                data: {},
                retries: 3
            });
        } catch (error) {
            const parsedError = AxiosErrorSchema.safeParse(error);
            if (parsedError.success) {
                const status = parsedError.data.status || 0;
                const data = parsedError.data.response?.data || {};
                const providerData = ProviderResponseSchema.safeParse(data);
                if (providerData.success && (status === 401 || status === 404 || status === 409)) {
                    return {
                        ...(providerData.data.requestId !== undefined && { requestId: providerData.data.requestId }),
                        ...(providerData.data.errors !== undefined && { errors: providerData.data.errors })
                    };
                }
            }
            throw error;
        }

        const providerResponse = ProviderResponseSchema.parse(response.data);

        if (response.status >= 400) {
            return {
                ...(providerResponse.requestId !== undefined && { requestId: providerResponse.requestId }),
                ...(providerResponse.errors !== undefined && { errors: providerResponse.errors })
            };
        }

        return {
            ...(providerResponse.requestId !== undefined && { requestId: providerResponse.requestId }),
            ...(providerResponse.clientRequestId !== undefined && { clientRequestId: providerResponse.clientRequestId })
        };
    }
});

export type NangoActionLocal = Parameters<(typeof action)['exec']>[0];
export default action;
