// Generated by ts-to-zod
import { z } from 'zod';

export const idEntitySchema = z.object({
    id: z.string()
});

export const successResponseSchema = z.object({
    success: z.boolean()
});

export const userSchema = z.object({
    id: z.string(),
    email: z.string(),
    firstName: z.string(),
    lastName: z.string()
});

export const freshdeskCreateUserSchema = z.object({
    name: z.string(),
    email: z.string().optional(),
    phone: z.string().optional(),
    mobile: z.string().optional(),
    twitter_id: z
        .object({
            type: z.string(),
            unique: z.literal(true),
            required: z.literal(true)
        })
        .optional(),
    unique_external_id: z
        .object({
            type: z.string(),
            unique: z.literal(true),
            required: z.literal(true)
        })
        .optional(),
    other_emails: z.array(z.any()).optional(),
    company_id: z.number().optional(),
    view_all_tickets: z.boolean().optional(),
    other_companies: z.array(z.any()).optional(),
    address: z.string().optional(),
    avatar: z.record(z.any()).optional(),
    custom_fields: z.record(z.any()).optional(),
    description: z.string().optional(),
    job_title: z.string().optional(),
    language: z.string().optional(),
    tags: z.array(z.any()).optional(),
    time_zone: z.string().optional(),
    lookup_parameter: z.string().optional()
});

export const timestampsSchema = z.object({
    created_at: z.string(),
    updated_at: z.string()
});

export const hierarchyDataSchema = z.object({
    id: z.number(),
    name: z.string(),
    language: z.string()
});

export const hierarchyLevelSchema = z.object({
    level: z.number(),
    type: z.string(),
    data: hierarchyDataSchema
});

export const seoDataSchema = z.object({
    meta_title: z.union([z.string(), z.undefined()]).optional(),
    meta_description: z.union([z.string(), z.undefined()]).optional(),
    meta_keywords: z.union([z.string(), z.undefined()]).optional()
});

export const articleSchema = z.object({
    id: z.number(),
    created_at: z.string(),
    updated_at: z.string(),
    type: z.number(),
    category_id: z.number(),
    folder_id: z.number(),
    hierarchy: z.array(hierarchyLevelSchema),
    thumbs_up: z.number(),
    thumbs_down: z.number(),
    hits: z.number(),
    tags: z.union([z.array(z.string()), z.undefined()]).optional(),
    seo_data: seoDataSchema,
    agent_id: z.number(),
    title: z.string(),
    description: z.string(),
    description_text: z.string(),
    status: z.number()
});
