// Generated by ts-to-zod
import { z } from 'zod';

export const spreadsheetIdSchema = z.object({
    id: z.string()
});

export const spreadsheetSchema = z.object({
    spreadsheetId: z.string(),
    properties: z.record(z.any()),
    sheets: z.array(z.record(z.any())),
    namedRanges: z.array(z.record(z.any())),
    spreadsheetUrl: z.string(),
    developerMetadata: z.array(z.record(z.any())),
    dataSources: z.array(z.record(z.any())),
    dataSourceSchedules: z.array(z.record(z.any()))
});
