// ---------------------------
// This file was generated by Nango (v0.57.3)
// You can version this file
// ---------------------------

export interface Account {
  id: string;
  key: string;
  name: string;
  account_type: string;
  normal_balance: string;
  status: string;
  disallow_direct_posting: boolean;
  closing_type: string;
  alternative_GLAccount: string;
  audit: {  created_date_time: string;
  modified_date_time: string;
  created_by: string;
  modified_by: string;};
};
