// ---------------------------
// This file was generated by Nango (v0.64.2)
// You can version this file
// ---------------------------

export interface Updates {
    id: string;
    sync_token: string;
    active?: boolean | undefined;
}

export interface Metadata {
    created_at: string;
    updated_at: string;
}

export interface BillAddr {
    city: string | null;
    line1: string | null;
    postal_code: string | null;
    country: string | null;
    id: string;
}

export interface InvoiceItem {
    id: string;
    description: string | null;
    qty: number;
    unit_price_cents: number;
    amount_cents: number;
}

export interface BaseInvoice {
    created_at: string;
    updated_at: string;
    id: string;
    txn_date: string;
    balance_cents: number;
    total_amt_cents: number;
    bill_address: BillAddr | null;
    items: InvoiceItem[];
}

export interface Reference {
    name?: string | undefined | undefined;
    value: string;
}

export interface Customer {
    created_at: string;
    updated_at: string;
    id: string;
    given_name: string | null;
    display_name: string | null;
    active: boolean;
    balance_cents: number;
    taxable: boolean;
    primary_email: string | null;
    primary_phone: string | null;
    bill_address: BillAddr | null;
    ship_address: BillAddr | null;
}

export interface Account {
    created_at: string;
    updated_at: string;
    id: string;
    fully_qualified_name: string;
    name: string;
    account_type: string;
    account_sub_type: string;
    classification: string;
    current_balance_cents: number;
    active: boolean;
    description: string | null;
    acct_num: string | null;
    sub_account: boolean;
}

export interface Payment {
    created_at: string;
    updated_at: string;
    id: string;
    amount_cents: number;
    customer_name: string | null;
    txn_date: string;
}

export interface Item {
    created_at: string;
    updated_at: string;
    id: string;
    name: string;
    active: boolean;
    type: string;
    unit_price_cents: number;
    purchase_cost_cents: number;
    qty_on_hand: number | null;
    inv_start_date: string | null;
    description: string | null;
    track_qty_onHand: boolean;
}

export interface Invoice {
    created_at: string;
    updated_at: string;
    id: string;
    txn_date: string;
    balance_cents: number;
    total_amt_cents: number;
    bill_address: BillAddr | null;
    items: InvoiceItem[];
    due_date: string;
    deposit_cents: number;
}

export interface Address {
    line1?: string | undefined | undefined;
    line2?: string | undefined;
    city?: string | undefined;
    postal_code?: string | undefined;
    country?: string | undefined;
    lat?: string | undefined;
    long?: string | undefined;
}

export interface CreateCustomer {
    display_name?: string | undefined;
    suffix?: string | undefined;
    title?: string | undefined;
    given_name?: string | undefined;
    company_name?: string | undefined;
    notes?: string | undefined;
    primary_email?: string | undefined;
    primary_phone?: string | undefined;
    bill_address?: Address | undefined;
    ship_address?: Address | undefined;
}

export interface UpdateCustomer {
    display_name?: string | undefined;
    suffix?: string | undefined;
    title?: string | undefined;
    given_name?: string | undefined;
    company_name?: string | undefined;
    notes?: string | undefined;
    primary_email?: string | undefined;
    primary_phone?: string | undefined;
    bill_address?: Address | undefined;
    ship_address?: Address | undefined;
    id: string;
    sync_token: string;
    active?: boolean | undefined;
}

export interface CreateItem {
    track_qty_onHand?: boolean | undefined;
    qty_on_hand?: number | undefined;
    name: string;
    expense_accountRef?: Reference | undefined;
    income_accountRef?: Reference | undefined;
    asset_accountRef?: Reference | undefined;
    inv_start_date?: string | undefined;
    unit_price_cents?: number | undefined;
    purchase_cost_cents?: number | undefined;
    type?: string | undefined;
}

export interface UpdateItem {
    track_qty_onHand?: boolean | undefined;
    qty_on_hand?: number | undefined;
    name: string;
    expense_accountRef?: Reference | undefined;
    income_accountRef?: Reference | undefined;
    asset_accountRef?: Reference | undefined;
    inv_start_date?: string | undefined;
    unit_price_cents?: number | undefined;
    purchase_cost_cents?: number | undefined;
    type?: string | undefined;
    id: string;
    sync_token: string;
    active?: boolean | undefined;
}

export interface CreateAccount {
    name: string;
    account_type?: string | undefined;
    account_sub_type?: string | undefined;
    description?: string | undefined;
    acct_num?: string | undefined;
}

export interface UpdateAccount {
    name: string;
    account_type?: string | undefined;
    account_sub_type?: string | undefined;
    description?: string | undefined;
    acct_num?: string | undefined;
    id: string;
    sync_token: string;
    active?: boolean | undefined;
}

export interface Line {
    detail_type: string;
    amount_cents: number;
    sales_item_line_detail: { item_ref: Reference };
    quantity?: number | undefined;
    unit_price_cents?: number | undefined;
    discount_rate?: number | undefined;
    description?: string | undefined;
}

export interface CreateInvoice {
    customer_ref?: Reference | undefined;
    line?: Line[] | undefined;
    due_date?: string | undefined;
    currency_ref?: Reference | undefined;
    project_ref?: Reference | undefined;
}

export interface UpdateInvoice {
    customer_ref?: Reference | undefined;
    line?: Line[] | undefined;
    due_date?: string | undefined;
    currency_ref?: Reference | undefined;
    project_ref?: Reference | undefined;
    id: string;
    sync_token: string;
    active?: boolean | undefined;
}

export interface CreateCreditMemo {
    customer_ref?: Reference | undefined;
    line?: Line[] | undefined;
    due_date?: string | undefined;
    currency_ref?: Reference | undefined;
    project_ref?: Reference | undefined;
}

export interface UpdateCreditMemo {
    customer_ref?: Reference | undefined;
    line?: Line[] | undefined;
    due_date?: string | undefined;
    currency_ref?: Reference | undefined;
    project_ref?: Reference | undefined;
    id: string;
    sync_token: string;
    active?: boolean | undefined;
}

export interface CreditMemo {
    created_at: string;
    updated_at: string;
    id: string;
    txn_date: string;
    balance_cents: number;
    total_amt_cents: number;
    bill_address: BillAddr | null;
    items: InvoiceItem[];
    remaining_credit: number;
    customer_name: string | null;
}

export interface CreatePayment {
    total_amount_cents: number;
    customer_ref: Reference;
    currency_ref?: Reference | undefined;
    project_ref?: Reference | undefined;
}

export interface JournalEntryLine {
    id: string;
    type: string;
    account_id: string;
    account_name: string;
    net_amount: number;
    posting_type: 'Debit' | 'Credit';
    description: string;
    entity_type?: string | undefined | undefined;
    entity_type_id?: string | undefined | undefined;
    entity_type_name?: string | undefined | undefined;
    department_id?: string | undefined | undefined;
    department_name?: string | undefined | undefined;
    class_id?: string | undefined | undefined;
    class_name?: string | undefined | undefined;
}

export interface JournalEntry {
    created_at: string;
    updated_at: string;
    id: string;
    date: string | null;
    currency: string;
    note?: string | undefined | undefined;
    lines: JournalEntryLine[];
}

export interface BillLine {
    id: string;
    detail_type: string;
    amount: number;
    account_id?: string | undefined | undefined;
    account_name?: string | undefined | undefined;
}

export interface Bill {
    created_at: string;
    updated_at: string;
    id: string;
    sales_term_id?: string | undefined;
    due_date: string;
    balance: number;
    txn_date: string;
    currency: string;
    vendor_id: string;
    vendor_name?: string | undefined | undefined;
    ap_account_id?: string | undefined | undefined;
    ap_account_name?: string | undefined | undefined;
    total_amount: number;
    lines: BillLine[];
}

export interface CreateBill {
    currency: string;
    vendor_id: string;
    vendor_name?: string | undefined | undefined;
    line: BillLine[];
}

export interface BillPaymentLinkedTxn {
    txn_id: string;
    txn_type: string;
}

export interface BillPaymentLine {
    amount: number;
    linkedTxn: BillPaymentLinkedTxn[];
}

export interface BillPayment {
    id: string;
    vendor_id?: string | undefined | undefined;
    vendor_name?: string | undefined | undefined;
    txn_date: string;
    total_amount: number;
    currency: string;
    private_note?: string | undefined | undefined;
    lines: BillPaymentLine[];
}

export interface PurchaseLine {
    id: string;
    description?: string | undefined;
    detail_type: string;
    amount: number;
    account_name?: string | undefined | undefined;
    account_id?: string | undefined | undefined;
    billable_status?: string | undefined | undefined;
    tax_code?: string | undefined | undefined;
}

export interface Purchase {
    created_at: string;
    updated_at: string;
    id: string;
    account_id?: string | undefined | undefined;
    account_name?: string | undefined | undefined;
    payment_type: string;
    entity_type?: string | undefined | undefined;
    entity_id?: string | undefined | undefined;
    entity_name: string | undefined;
    total_amount: number;
    print_status?: string | undefined;
    doc_number?: string | undefined;
    txn_date: string;
    currency: string;
    lines: PurchaseLine[];
}

export interface Transfer {
    created_at: string;
    updated_at: string;
    id: string;
    from_account_id?: string | undefined | undefined;
    from_account_name?: string | undefined | undefined;
    to_account_id?: string | undefined | undefined;
    to_account_name?: string | undefined | undefined;
    amount: number;
    currency: string;
    txn_date: string;
    private_note?: string | undefined | undefined;
}

export interface DepositLine {
    id?: string | undefined;
    amount: number;
    detail_type?: string | undefined;
    deposit_account_id?: string | undefined | undefined;
    deposit_account_name?: string | undefined | undefined;
}

export interface Deposit {
    created_at: string;
    updated_at: string;
    id: string;
    account_id?: string | undefined | undefined;
    account_name?: string | undefined | undefined;
    txn_date: string;
    total_amount: number;
    currency: string;
    private_note?: string | undefined | undefined;
    lines: DepositLine[];
}

export interface DeleteResponse {
    id: string;
}

export interface LinkedTxn {
    txn_id: string;
    txn_type: string;
    txn_line_id?: string | undefined;
}

export interface MarkupInfo {
    price_level_ref?: Reference | undefined;
    percent?: number | undefined;
    mark_up_income_account_ref?: Reference | undefined;
}

export interface ItemBasedExpenseLine {
    item_ref?: Reference | undefined;
    price_level_ref?: Reference | undefined;
    qty?: number | undefined;
    unit_price_cents?: number | undefined;
    tax_inclusive_amt?: number | undefined;
    customer_ref?: Reference | undefined;
    class_ref?: Reference | undefined;
    tax_code_ref?: Reference | undefined;
    markup_info?: MarkupInfo | null | undefined;
    billable_status?: 'Billable' | 'NotBillable' | 'HasBeenBilled' | undefined;
}

export interface PurchaseOrderLine {
    id?: string | undefined;
    amount_cents: number;
    detail_type: 'ItemBasedExpenseLineDetail';
    item_based_expense_line_detail?: ItemBasedExpenseLine | undefined;
    description?: string | undefined;
    line_num?: number | undefined;
    linked_txn?: LinkedTxn[] | undefined;
    project_ref?: Reference | undefined;
}

export interface CustomField {
    definition_id: string;
    name?: string | undefined;
    type?: string | undefined;
    string_value?: string | undefined;
}

export interface TaxLine {
    amount: number;
    detail_type: string;
    tax_line_detail: 'TaxLineDetail';
}

export interface TxnTaxDetail {
    txn_tax_code_ref?: Reference | undefined;
    total_tax_cents?: number | undefined;
    tax_line?: TaxLine[] | undefined;
}

export interface PhysicalAddress {
    line1?: string | undefined | undefined;
    line2?: string | undefined;
    line3?: string | undefined;
    line4?: string | undefined;
    line5?: string | undefined;
    city?: string | undefined;
    sub_division_code?: string | undefined;
    postal_code?: string | undefined;
    country?: string | undefined;
    country_sub_division_code?: string | undefined;
    lat?: string | undefined;
    long?: string | undefined;
    id: string;
}

export interface CreatePurchaseOrder {
    ap_account_ref: Reference;
    vendor_ref: Reference;
    line: PurchaseOrderLine[];
    sync_token?: string | undefined;
    currency_ref?: Reference | undefined;
    global_tax_calculation?: 'TaxExcluded' | 'TaxInclusive' | 'NotApplicable' | undefined;
    txn_date?: string | undefined;
    custom_field?: CustomField[] | undefined;
    po_email?: string | null | undefined;
    class_ref?: Reference | undefined;
    sales_term_ref?: Reference | undefined;
    linked_txn?: LinkedTxn[] | undefined;
    memo?: string | undefined;
    po_status?: 'Open' | 'Closed' | undefined;
    transaction_location_type?: string | undefined;
    due_date?: string | undefined;
    metadata?: Metadata | undefined;
    doc_number?: string | undefined;
    private_note?: string | undefined;
    ship_method_ref?: Reference | undefined;
    txn_tax_detail?: TxnTaxDetail | undefined;
    ship_to?: Reference | undefined;
    exchange_rate?: number | undefined;
    ship_addr?: PhysicalAddress | null | undefined;
    vendor_addr?: PhysicalAddress | null | undefined;
    email_status?: string | undefined;
    total_amt_cents: number;
    recur_data_ref?: Reference | undefined;
}

export interface PurchaseOrder {
    id: string;
    created_at: string;
    updated_at: string;
    ap_account_ref: Reference;
    vendor_ref: Reference;
    line: PurchaseOrderLine[];
    sync_token?: string | undefined;
    currency_ref?: Reference | undefined;
    global_tax_calculation?: 'TaxExcluded' | 'TaxInclusive' | 'NotApplicable' | undefined;
    txn_date?: string | undefined;
    custom_field?: CustomField[] | undefined;
    po_email?: string | null | undefined;
    class_ref?: Reference | undefined;
    sales_term_ref?: Reference | undefined;
    linked_txn?: LinkedTxn[] | undefined;
    memo?: string | undefined;
    po_status?: 'Open' | 'Closed' | undefined;
    transaction_location_type?: string | undefined;
    due_date?: string | undefined;
    metadata?: Metadata | undefined;
    doc_number?: string | undefined;
    private_note?: string | undefined;
    ship_method_ref?: Reference | undefined;
    txn_tax_detail?: TxnTaxDetail | undefined;
    ship_to?: Reference | undefined;
    exchange_rate?: number | undefined;
    ship_addr?: PhysicalAddress | null | undefined;
    vendor_addr?: PhysicalAddress | null | undefined;
    email_status?: string | undefined;
    total_amt_cents: number;
    recur_data_ref?: Reference | undefined;
}

export interface AccountBasedExpenseLineDetail {
    account_ref: Reference;
    tax_amount?: number | undefined;
    tax_inclusive_amt?: number | undefined;
    customer_ref?: Reference | undefined;
    class_ref?: Reference | undefined;
    tax_code_ref?: Reference | undefined;
    markup_info?: MarkupInfo | null | undefined;
    billable_status?: 'Billable' | 'NotBillable' | 'HasBeenBilled' | undefined;
}

export interface CreateJournalEntry {
    line_items: {
        detail_type: string;
        amount: number;
        project_ref?: Reference | undefined;
        description?: string | undefined;
        line_num?: number | undefined;
        journal_entry_line_detail: {
            journal_code_ref?: Reference | undefined;
            posting_type: 'Debit' | 'Credit';
            account_ref: Reference;
            tax_applicable_on?: string | undefined;
            entity?: { type?: string | undefined; entity_ref?: Reference | undefined } | undefined;
            tax_inclusive_amt?: number | undefined;
            class_ref?: Reference | undefined;
            department_ref?: Reference | undefined;
            tax_code_ref?: Reference | undefined;
            billable_status?: string | undefined;
            tax_amount?: number | undefined;
        };
    }[];
    journal_code_ref?: Reference | undefined;
    currency_ref?: Reference | undefined;
}

export interface UpdateJournalEntry {
    id: string;
    sync_token: string;
    sparse?: boolean | undefined;
    line_items: {
        id?: string | undefined;
        detail_type: string;
        amount?: number | undefined;
        project_ref?: Reference | undefined;
        description?: string | undefined;
        line_num?: number | undefined;
        journal_entry_line_detail: {
            journal_code_ref?: Reference | undefined;
            posting_type: 'Debit' | 'Credit';
            account_ref: Reference;
            tax_applicable_on?: string | undefined;
            entity?: { type?: string | undefined; entity_ref?: Reference | undefined } | undefined;
            tax_inclusive_amt?: number | undefined;
            class_ref?: Reference | undefined;
            department_ref?: Reference | undefined;
            tax_code_ref?: Reference | undefined;
            billable_status?: string | undefined;
            tax_amount?: number | undefined;
        };
    }[];
    currency_ref?: Reference | undefined;
    global_tax_calculation?: string | undefined;
    doc_number?: string | undefined;
    private_note?: string | undefined;
    exchange_rate?: number | undefined;
    transaction_location_type?: string | undefined;
    txn_tax_detail?:
        | {
              txn_tax_code_ref?: Reference | undefined;
              total_tax?: number | undefined;
              tax_line?:
                  | {
                        detail_type: string;
                        tax_line_detail?:
                            | {
                                  tax_rate_ref?: Reference | undefined;
                                  net_amount_taxable?: number | undefined;
                                  percent_based?: boolean | undefined;
                                  tax_percent?: number | undefined;
                              }
                            | undefined;
                        amount?: number | undefined;
                    }[]
                  | undefined;
          }
        | undefined;
    adjustment?: boolean | undefined;
}
