// ---------------------------
// This file was generated by Nango (v0.68.1)
// You can version this file
// ---------------------------

export interface SyncMetadata_grammarly_users {
};

export interface User {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  __raw?: any | undefined;
};

export interface ActionInput_grammarly_deleteuser {
  email: string;
};

export interface ActionOutput_grammarly_deleteuser {
  success: boolean;
};
