#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run fix -- --quiet
npm run compile:integrations
git add ./internal/flows.zero.json

# Only run lint-staged if there are staged files
staged_files=$(git diff --cached --name-only)
if [ -n "$staged_files" ]; then
  npx lint-staged --allow-empty
fi
