// ---------------------------
// This file was generated by Nango (v0.57.3)
// You can version this file
// ---------------------------

export interface EventType {
    id: string;
    teamId: null | number;
    schedulingType: null | string;
    userId: number;
    metadata: { [key: string]: any };
    description: string | null;
    hidden: boolean;
    slug: string;
    length: number;
    title: string;
    requiresConfirmation: boolean;
    position: number;
    offsetStart: number;
    profileId: string | null;
    eventName: string | null;
    parentId: number | null;
    timeZone: string | null;
    periodType: string;
    periodStartDate: string | null;
    periodEndDate: string | null;
    periodDays: number | null;
    periodCountCalendarDays: number | null;
    lockTimeZoneToggleOnBookingPage: boolean;
    requiresBookerEmailVerification: boolean;
    disableGuests: boolean;
    hideCalendarNotes: boolean;
    minimumBookingNotice: number;
    beforeEventBuffer: number;
    afterEventBuffer: number;
    seatsPerTimeSlot: number | null;
    onlyShowFirstAvailableSlot: boolean;
    seatsShowAttendees: boolean;
    seatsShowAvailabilityCount: boolean;
    scheduleId: number | null;
    price: number;
    currency: string;
    slotInterval: number | null;
    successRedirectUrl: string | null;
    isInstantEvent: boolean;
    aiPhoneCallConfig: string | null;
    assignAllTeamMembers: boolean;
    recurringEvent: boolean | null;
    locations: { type: string }[];
    bookingFields: string | null;
    useEventTypeDestinationCalendarEmail: boolean;
    secondaryEmailId: string | null;
    bookingLimits: boolean | null;
    durationLimits: boolean | null;
    hashedLink: string | null;
    children: { [key: string]: any }[];
    hosts: { [key: string]: any }[];
    userIds: number[];
}

export interface User {
    username: string;
    name: string;
    weekStart: string;
    organizationId: number;
    avatarUrl: string;
    profile: {
        username: string;
        id: number;
        userId: number;
        uid: string;
        name: string;
        organizationId: number;
        organization: { id: number; slug: string; name: string; metadata: { [key: string]: any } };
        upId: string;
        image: string;
        brandColor: string;
        darkBrandColor: string;
        theme: string;
        bookerLayouts: { [key: string]: any };
    };
    bookerUrl: string;
}

export interface Attendee {
    id: number;
    email: string;
    name: string;
    timeZone: string;
    locale: string;
    bookingId: number;
}

export interface Event {
    id: string;
    title: string;
    userPrimaryEmail: string;
    description: string;
    customInputs: { [key: string]: any };
    startTime: string;
    endTime: string;
    attendees: Attendee[];
    metadata: { [key: string]: any };
    uid: string;
    recurringEventId: string;
    location: string;
    eventType: {
        slug: string;
        id: number;
        eventName: string;
        price: number;
        recurringEvent: { [key: string]: any };
        currency: string;
        metadata: { [key: string]: any };
        seatsShowAttendees: { [key: string]: any };
        seatsShowAvailabilityCount: { [key: string]: any };
        team: { [key: string]: any };
    };
    status: { [key: string]: any };
    paid: boolean;
    payment: { [key: string]: any }[];
    references: {
        id: number;
        type: string;
        uid: string;
        meetingId: string;
        thirdPartyRecurringEventId: string;
        meetingPassword: string;
        meetingUrl: string;
        bookingId: number;
        externalCalendarId: string;
        deleted: { [key: string]: string };
        credentialId: number;
    }[];
    isRecorded: boolean;
    seatsReferences: { [key: string]: any }[];
    user: User;
    rescheduled: { [key: string]: any };
}
