// ---------------------------
// This file was generated by Nango (v0.66.0)
// You can version this file
// ---------------------------

export interface SyncMetadata_salesforce_accounts {
};

export interface Account {
  id: string;
  name: string;
  description: string | null;
  website: string | null;
  industry: string | null;
  billing_city: string | null;
  billing_country: string | null;
  owner_id: string;
  owner_name: string;
  last_modified_date: string;
};

export interface SyncMetadata_salesforce_contacts {
};

export interface Contact {
  id: string;
  first_name: string | null;
  last_name: string;
  account_name: string | null;
  account_id: string | null;
  email: string | null;
  owner_id: string;
  owner_name: string;
  mobile: string | null;
  phone: string | null;
  salutation: string | null;
  title: string | null;
  last_modified_date: string;
};

export interface SyncMetadata_salesforce_leads {
};

export interface Lead {
  id: string;
  first_name: string | null;
  last_name: string;
  company_name: string;
  email: string | null;
  owner_id: string;
  owner_name: string;
  phone: string | null;
  salutation: string | null;
  title: string | null;
  website: string | null;
  industry: string | null;
  last_modified_date: string;
};

export interface SyncMetadata_salesforce_articles {
  customFields: string[];
};

export interface Article {
  id: string;
  title: string;
  content: string;
  last_modified_date: string;
};

export interface SyncMetadata_salesforce_tickets {
};

export interface Ticket {
  id: string;
  case_number: string;
  subject: string | null;
  account_id: string | null;
  account_name: string | null;
  contact_id: string | null;
  contact_name: string | null;
  owner_id: string;
  owner_name: string | null;
  priority: string;
  status: string;
  description: string | null;
  type: string | null;
  created_date: string;
  closed_date: string | null;
  origin: string | null;
  is_closed: boolean;
  is_escalated: boolean;
  conversation: ({  id: string;
  body: string;
  created_date: string;
  created_by: string;})[];
  last_modified_date: string;
};

export interface SyncMetadata_salesforce_opportunities {
};

export interface Opportunity {
  id: string;
  opportunity_name: string;
  account_name: string | null;
  account_id: string | null;
  amount: number | null;
  description: string | null;
  close_date: string;
  created_by_id: string;
  created_by: string;
  owner_id: string;
  owner_name: string;
  stage: string;
  probability: number | null;
  type: string | null;
  last_modified_date: string;
};

export interface ActionInput_salesforce_fetchfields {
  name: string;
};

export interface ActionOutput_salesforce_fetchfields {
  fields: ({  name: string;
  label: string;
  type: string;
  referenceTo: string[];
  relationshipName: string | null;})[];
  childRelationships: ({  object: string;
  relationshipName: string | null;
  field: string;})[];
  validationRules: ({  id: string;
  name: string;
  errorConditionFormula: string;
  errorMessage: string;})[];
};

export interface ActionInput_salesforce_createcontact {
  first_name?: string | undefined;
  account_id?: string | undefined;
  owner_id?: string | undefined;
  email?: string | undefined;
  mobile?: string | undefined;
  phone?: string | undefined;
  salutation?: string | undefined;
  title?: string | undefined;
  last_name: string;
};

export interface ActionOutput_salesforce_createcontact {
  id: string;
  success: boolean;
  errors: any[];
};

export interface ActionInput_salesforce_updatecontact {
  first_name?: string | undefined;
  account_id?: string | undefined;
  owner_id?: string | undefined;
  email?: string | undefined;
  mobile?: string | undefined;
  phone?: string | undefined;
  salutation?: string | undefined;
  title?: string | undefined;
  id: string;
  last_name?: string | undefined;
};

export interface ActionOutput_salesforce_updatecontact {
  success: boolean;
};

export interface ActionInput_salesforce_deletecontact {
  id: string;
};

export interface ActionOutput_salesforce_deletecontact {
  success: boolean;
};

export interface ActionInput_salesforce_createlead {
  first_name?: string | undefined;
  email?: string | undefined;
  owner_id?: string | undefined;
  phone?: string | undefined;
  salutation?: string | undefined;
  title?: string | undefined;
  website?: string | undefined;
  industry?: string | undefined;
  last_name: string;
  company_name: string;
};

export interface ActionOutput_salesforce_createlead {
  id: string;
  success: boolean;
  errors: any[];
};

export interface ActionInput_salesforce_updatelead {
  first_name?: string | undefined;
  email?: string | undefined;
  owner_id?: string | undefined;
  phone?: string | undefined;
  salutation?: string | undefined;
  title?: string | undefined;
  website?: string | undefined;
  industry?: string | undefined;
  id: string;
  last_name?: string | undefined;
  company_name?: string | undefined;
};

export interface ActionOutput_salesforce_updatelead {
  success: boolean;
};

export interface ActionInput_salesforce_deletelead {
  id: string;
};

export interface ActionOutput_salesforce_deletelead {
  success: boolean;
};

export interface ActionInput_salesforce_createaccount {
  description?: string | undefined;
  website?: string | undefined;
  industry?: string | undefined;
  billing_city?: string | undefined;
  billing_country?: string | undefined;
  owner_id?: string | undefined;
  name: string;
};

export interface ActionOutput_salesforce_createaccount {
  id: string;
  success: boolean;
  errors: any[];
};

export interface ActionInput_salesforce_updateaccount {
  description?: string | undefined;
  website?: string | undefined;
  industry?: string | undefined;
  billing_city?: string | undefined;
  billing_country?: string | undefined;
  owner_id?: string | undefined;
  id: string;
  name?: string | undefined;
};

export interface ActionOutput_salesforce_updateaccount {
  success: boolean;
};

export interface ActionInput_salesforce_deleteaccount {
  id: string;
};

export interface ActionOutput_salesforce_deleteaccount {
  success: boolean;
};

export interface ActionInput_salesforce_createopportunity {
  account_id?: string | undefined;
  amount?: number | undefined;
  description?: string | undefined;
  created_by_id?: string | undefined;
  owner_id?: string | undefined;
  probability?: number | undefined;
  type?: string | undefined;
  opportunity_name: string;
  close_date: string;
  stage: string;
};

export interface ActionOutput_salesforce_createopportunity {
  id: string;
  success: boolean;
  errors: any[];
};

export interface ActionInput_salesforce_updateopportunity {
  account_id?: string | undefined;
  amount?: number | undefined;
  description?: string | undefined;
  created_by_id?: string | undefined;
  owner_id?: string | undefined;
  probability?: number | undefined;
  type?: string | undefined;
  id: string;
  opportunity_name?: string | undefined;
  close_date?: string | undefined;
  stage?: string | undefined;
};

export interface ActionOutput_salesforce_updateopportunity {
  success: boolean;
};

export interface ActionInput_salesforce_deleteopportunity {
  id: string;
};

export interface ActionOutput_salesforce_deleteopportunity {
  success: boolean;
};

export type ActionInput_salesforce_whoami = void

export interface ActionOutput_salesforce_whoami {
  id: string;
  email: string;
};
