// ---------------------------
// This file was generated by Nango (v0.64.1)
// You can version this file
// ---------------------------

export interface SyncMetadata_recharge_customers {
};

export interface Customer {
  id: string;
  phone_number: string | null;
  first_name: string | null;
  last_name: string | null;
  email: string | null;
  subscriptions: (string | string | string | string | string | null | string | null)[];
};

export interface ActionInput_recharge_upsertcustomers {
  email: string;
  external_customer_id: {  ecommerce: string;};
  first_name: string;
  last_name: string;
  phone: string;
  tax_exempt: boolean;
};

export interface ActionOutput_recharge_upsertcustomers {
  action: 'update' | 'create';
  response: {  accepts_marketing: number | null;
  analytics_data: {  utm_params: (string | string | string | string | string | string | string)[];};
  billing_address1: string | null;
  billing_address2: string | null;
  billing_city: string | null;
  billing_company: string | null;
  billing_country: string | null;
  billing_phone: string | null;
  billing_province: string | null;
  billing_zip: string | null;
  created_at: string;
  email: string;
  first_charge_processed_at: string | null;
  first_name: string;
  has_card_error_in_dunning: boolean;
  has_valid_payment_method: boolean;
  hash: string;
  id: number;
  last_name: string;
  number_active_subscriptions: number;
  number_subscriptions: number;
  phone: string | null;
  processor_type: string | null;
  reason_payment_method_not_valid: string | null;
  shopify_customer_id: string | null;
  status: string;
  tax_exempt: boolean;
  updated_at: string;
  apply_credit_to_next_recurring_charge: boolean;
  external_customer_id: {  ecommerce: string;};
  has_payment_method_in_dunning: boolean;
  subscriptions_active_count: number;
  subscriptions_total_count: number;
  subscription_related_charge_streak: number;};
};
