// ---------------------------
// This file was generated by Nango (v0.62.0)
// You can version this file
// ---------------------------

export interface Customer {
    id: string;
    phone_number: string | null;
    first_name: string | null;
    last_name: string | null;
    email: string | null;
    subscriptions: { id: string; type: string; name: string; start_date: string; end_date: string | null; next_charge_scheduled_at: string | null }[];
}

export interface ExternalCustomerId {
    ecommerce: string;
}

export interface UpsertRechargeCustomerInput {
    email: string;
    external_customer_id?: ExternalCustomerId | undefined;
    first_name: string;
    last_name: string;
    phone?: string | undefined;
    tax_exempt?: boolean | undefined;
}

export interface UpsertRechargeCustomerOutput {
    action: 'update' | 'create';
    response: {
        accepts_marketing: number | null;
        analytics_data: {
            utm_params: {
                utm_campaign?: string | undefined;
                utm_content?: string | undefined;
                utm_data_source?: string | undefined;
                utm_source?: string | undefined;
                utm_medium?: string | undefined;
                utm_term?: string | undefined;
                utm_timestamp?: string | undefined;
            }[];
        };
        billing_address1: string | null;
        billing_address2: string | null;
        billing_city: string | null;
        billing_company: string | null;
        billing_country: string | null;
        billing_phone: string | null;
        billing_province: string | null;
        billing_zip: string | null;
        created_at: string;
        email: string;
        first_charge_processed_at: string | null;
        first_name: string;
        has_card_error_in_dunning: boolean;
        has_valid_payment_method: boolean;
        hash: string;
        id: number;
        last_name: string;
        number_active_subscriptions: number;
        number_subscriptions: number;
        phone: string | null;
        processor_type: string | null;
        reason_payment_method_not_valid: string | null;
        shopify_customer_id: string | null;
        status: string;
        tax_exempt: boolean;
        updated_at: string;
        apply_credit_to_next_recurring_charge?: boolean | undefined;
        external_customer_id?: ExternalCustomerId | undefined;
        has_payment_method_in_dunning?: boolean | undefined;
        subscriptions_active_count?: number | undefined;
        subscriptions_total_count?: number | undefined;
        subscription_related_charge_streak?: number | undefined;
    };
}
