import { createSync, type ProxyConfiguration } from 'nango';
import { z } from 'zod';

/**
 * Internal schema for the raw stats object returned by the Brevo API.
 * The docs mark these counters as required-but-nullable, and some are omitted
 * depending on the campaign state, so every field is nullable and optional.
 */
const ProviderCampaignStatsSchema = z.object({
    sent: z.number().nullable().optional(),
    delivered: z.number().nullable().optional(),
    hardBounces: z.number().nullable().optional(),
    softBounces: z.number().nullable().optional(),
    complaints: z.number().nullable().optional(),
    unsubscriptions: z.number().nullable().optional(),
    viewed: z.number().nullable().optional(),
    uniqueViews: z.number().nullable().optional(),
    opensRate: z.number().nullable().optional(),
    clickers: z.number().nullable().optional(),
    uniqueClicks: z.number().nullable().optional(),
    trackableViews: z.number().nullable().optional(),
    trackableViewsRate: z.number().nullable().optional(),
    estimatedViews: z.number().nullable().optional(),
    appleMppOpens: z.number().nullable().optional(),
    deferred: z.number().nullable().optional(),
    listId: z.number().nullable().optional()
});

/**
 * Internal schema for a raw email campaign as returned by GET /emailCampaigns.
 * Only the fields mapped into the public model are declared; unknown fields are stripped.
 */
const ProviderEmailCampaignSchema = z.object({
    id: z.number(),
    name: z.string(),
    type: z.string(),
    status: z.string(),
    createdAt: z.string(),
    modifiedAt: z.string(),
    subject: z.string().nullable().optional(),
    tag: z.string().nullable().optional(),
    previewText: z.string().nullable().optional(),
    replyTo: z.string().nullable().optional(),
    scheduledAt: z.string().nullable().optional(),
    sentDate: z.string().nullable().optional(),
    testSent: z.boolean().nullable().optional(),
    abTesting: z.boolean().nullable().optional(),
    sendAtBestTime: z.boolean().nullable().optional(),
    sender: z
        .object({
            id: z.number().nullable().optional(),
            name: z.string().nullable().optional(),
            email: z.string().nullable().optional()
        })
        .nullable()
        .optional(),
    recipients: z
        .object({
            lists: z.array(z.number()),
            exclusionLists: z.array(z.number()),
            segments: z.array(z.number()).nullable().optional(),
            excludedSegments: z.array(z.number()).nullable().optional()
        })
        .nullable()
        .optional(),
    statistics: z
        .object({
            globalStats: ProviderCampaignStatsSchema.nullable().optional(),
            campaignStats: z.array(ProviderCampaignStatsSchema).nullable().optional(),
            mirrorClick: z.number().nullable().optional(),
            remaining: z.number().nullable().optional()
        })
        .nullable()
        .optional()
});

type ProviderEmailCampaign = z.infer<typeof ProviderEmailCampaignSchema>;
type ProviderCampaignStats = z.infer<typeof ProviderCampaignStatsSchema>;

const EmailCampaignStatsSchema = z.object({
    sent: z.number().optional().describe('Number of emails sent for the campaign. Example: 19887'),
    delivered: z.number().optional().describe('Number of emails delivered for the campaign. Example: 19765'),
    hardBounces: z.number().optional().describe('Number of hard bounces for the campaign. Example: 87'),
    softBounces: z.number().optional().describe('Number of soft bounces for the campaign. Example: 100'),
    complaints: z.number().optional().describe('Number of spam complaints reported for the campaign. Example: 1'),
    unsubscriptions: z.number().optional().describe('Number of unsubscriptions generated by the campaign. Example: 2'),
    viewed: z.number().optional().describe('Number of times the campaign emails were opened. Example: 8999'),
    uniqueViews: z.number().optional().describe('Number of unique opens of the campaign emails. Example: 7779'),
    opensRate: z
        .number()
        .optional()
        .describe('Percentage of recipients who opened the email, out of the total number of recipients. May include Apple MPP opens. Example: 29.54'),
    clickers: z.number().optional().describe('Total number of clicks on links in the campaign. Example: 2665'),
    uniqueClicks: z.number().optional().describe('Number of unique clicks on links in the campaign. Example: 2300'),
    trackableViews: z.number().optional().describe('Number of recipients without any privacy protection option enabled in their email client. Example: 5661'),
    trackableViewsRate: z
        .number()
        .optional()
        .describe('Rate of recipients without any privacy protection option enabled in their email client. Example: 23.45'),
    estimatedViews: z
        .number()
        .optional()
        .describe('Rate of recipients without privacy protection enabled, applied as an estimate to all delivered emails. Example: 560'),
    appleMppOpens: z.number().optional().describe('Number of times the email was opened automatically through Apple Mail Privacy Protection. Example: 10'),
    deferred: z.number().optional().describe('Number of deferred emails for the campaign. Example: 30')
});

const EmailCampaignListStatsSchema = EmailCampaignStatsSchema.extend({
    listId: z.number().optional().describe('ID of the recipient contact list these statistics apply to. Example: 5')
});

const EmailCampaignSchema = z
    .object({
        id: z.string().describe('Unique identifier of the campaign, stringified from the numeric Brevo campaign ID. Example: "12"'),
        name: z.string().describe('Name of the campaign. Example: "EN - Sales Summer 2017"'),
        type: z.string().describe("Type of the campaign: 'classic' for a regular campaign or 'trigger' for a trigger campaign"),
        status: z
            .string()
            .describe(
                "Status of the campaign. Known values: 'draft', 'sent', 'archive', 'queued', 'suspended', 'in_process', 'in_review', 'cancelling', 'cancelled'"
            ),
        subject: z.string().optional().describe('Subject of the campaign. Only present when A/B testing is disabled for the campaign'),
        tag: z.string().optional().describe('Tag of the campaign. Example: "Newsletter"'),
        previewText: z.string().optional().describe('Preview text (preheader) of the email campaign'),
        replyTo: z.string().optional().describe('Email address defined as the "Reply-To" of the campaign'),
        sender: z
            .object({
                id: z.number().optional().describe('ID of the campaign sender. Example: 26'),
                name: z.string().optional().describe('Name of the campaign sender. Example: "Marketing"'),
                email: z.string().optional().describe('Email address of the campaign sender. Example: "marketing@mycompany.com"')
            })
            .optional()
            .describe('Sender of the campaign'),
        testSent: z.boolean().optional().describe('Whether a test email has been sent for the campaign'),
        abTesting: z.boolean().optional().describe('Whether A/B testing is enabled for the campaign'),
        sendAtBestTime: z.boolean().optional().describe('Whether the campaign is sent at the best time for each recipient'),
        recipients: z
            .object({
                lists: z.array(z.number()).describe('IDs of the contact lists the campaign is sent to. Example: [5]'),
                exclusionLists: z.array(z.number()).describe('IDs of the contact lists excluded from the campaign. Example: [13]'),
                segments: z.array(z.number()).optional().describe('IDs of the segments included in the campaign'),
                excludedSegments: z.array(z.number()).optional().describe('IDs of the segments excluded from the campaign')
            })
            .optional()
            .describe('Recipients configuration of the campaign'),
        scheduledAt: z
            .string()
            .optional()
            .describe(
                'Date-time on which the campaign is scheduled, as an ISO 8601 timestamp with a provider-determined UTC offset (e.g. "2027-01-15T12:00:00.000+03:00"), not necessarily "Z"/UTC. Only present when the campaign has a schedule'
            ),
        sentDate: z
            .string()
            .optional()
            .describe(
                'Date-time on which the campaign was sent, as an ISO 8601 timestamp with a provider-determined UTC offset (e.g. "2026-10-02T02:05:38.000+03:00"), not necessarily "Z"/UTC. Only present when the campaign status is "sent"'
            ),
        createdAt: z
            .string()
            .describe(
                'Date-time of creation of the campaign, as an ISO 8601 timestamp with a provider-determined UTC offset (e.g. "2026-10-02T02:09:51.000+03:00"), not necessarily "Z"/UTC.'
            ),
        modifiedAt: z
            .string()
            .describe(
                'Date-time of the last modification of the campaign, as an ISO 8601 timestamp with a provider-determined UTC offset (e.g. "2026-10-02T02:10:13.000+03:00"), not necessarily "Z"/UTC.'
            ),
        statistics: z
            .object({
                globalStats: EmailCampaignStatsSchema.optional().describe('Aggregate delivery statistics of the campaign across all recipients'),
                campaignStats: z.array(EmailCampaignListStatsSchema).optional().describe('Per-recipient-list delivery statistics of the campaign'),
                mirrorClick: z.number().optional().describe('Number of clicks on the mirror link of the campaign. Example: 120'),
                remaining: z.number().optional().describe('Number of emails remaining to send for the campaign. Example: 1000')
            })
            .optional()
            .describe('Delivery statistics of the campaign')
    })
    .describe('Email (classic) campaign synced from Brevo, including its status and delivery statistics');

function toOptionalString(value: string | null | undefined): string | undefined {
    return value ? value : undefined;
}

function toOptionalNumber(value: number | null | undefined): number | undefined {
    return value ?? undefined;
}

function toStats(stats: ProviderCampaignStats): z.infer<typeof EmailCampaignStatsSchema> {
    return {
        sent: toOptionalNumber(stats.sent),
        delivered: toOptionalNumber(stats.delivered),
        hardBounces: toOptionalNumber(stats.hardBounces),
        softBounces: toOptionalNumber(stats.softBounces),
        complaints: toOptionalNumber(stats.complaints),
        unsubscriptions: toOptionalNumber(stats.unsubscriptions),
        viewed: toOptionalNumber(stats.viewed),
        uniqueViews: toOptionalNumber(stats.uniqueViews),
        opensRate: toOptionalNumber(stats.opensRate),
        clickers: toOptionalNumber(stats.clickers),
        uniqueClicks: toOptionalNumber(stats.uniqueClicks),
        trackableViews: toOptionalNumber(stats.trackableViews),
        trackableViewsRate: toOptionalNumber(stats.trackableViewsRate),
        estimatedViews: toOptionalNumber(stats.estimatedViews),
        appleMppOpens: toOptionalNumber(stats.appleMppOpens),
        deferred: toOptionalNumber(stats.deferred)
    };
}

function toEmailCampaign(record: ProviderEmailCampaign): z.infer<typeof EmailCampaignSchema> {
    return {
        id: String(record.id),
        name: record.name,
        type: record.type,
        status: record.status,
        subject: toOptionalString(record.subject),
        tag: toOptionalString(record.tag),
        previewText: toOptionalString(record.previewText),
        replyTo: toOptionalString(record.replyTo),
        sender: record.sender
            ? {
                  id: toOptionalNumber(record.sender.id),
                  name: toOptionalString(record.sender.name),
                  email: toOptionalString(record.sender.email)
              }
            : undefined,
        testSent: record.testSent ?? undefined,
        abTesting: record.abTesting ?? undefined,
        sendAtBestTime: record.sendAtBestTime ?? undefined,
        recipients: record.recipients
            ? {
                  lists: record.recipients.lists,
                  exclusionLists: record.recipients.exclusionLists,
                  segments: record.recipients.segments ?? undefined,
                  excludedSegments: record.recipients.excludedSegments ?? undefined
              }
            : undefined,
        scheduledAt: toOptionalString(record.scheduledAt),
        sentDate: toOptionalString(record.sentDate),
        createdAt: record.createdAt,
        modifiedAt: record.modifiedAt,
        statistics: record.statistics
            ? {
                  globalStats: record.statistics.globalStats ? toStats(record.statistics.globalStats) : undefined,
                  campaignStats: record.statistics.campaignStats
                      ? record.statistics.campaignStats.map((listStats) => ({ ...toStats(listStats), listId: toOptionalNumber(listStats.listId) }))
                      : undefined,
                  mirrorClick: toOptionalNumber(record.statistics.mirrorClick),
                  remaining: toOptionalNumber(record.statistics.remaining)
              }
            : undefined
    };
}

const sync = createSync({
    description: 'Full refresh sync of email (classic) campaigns, including their status and delivery statistics.',
    version: '1.0.0',
    frequency: 'every hour',
    autoStart: true,
    models: {
        EmailCampaign: EmailCampaignSchema
    },

    exec: async (nango) => {
        // startDate/endDate filters exist, but the accepted datetime format was not
        // confirmed live for this registry pass, so this sync intentionally remains
        // full-refresh only instead of using an unverified incremental filter.
        await nango.trackDeletesStart('EmailCampaign');

        const proxyConfig: ProxyConfiguration = {
            // https://developers.brevo.com/reference/get-email-campaigns
            endpoint: '/emailCampaigns',
            params: {
                statistics: 'globalStats',
                excludeHtmlContent: 'true'
            },
            paginate: {
                type: 'offset',
                offset_name_in_request: 'offset',
                offset_start_value: 0,
                offset_calculation_method: 'by-response-size',
                limit_name_in_request: 'limit',
                limit: 50,
                response_path: 'campaigns'
            },
            retries: 3
        };

        for await (const page of nango.paginate<unknown>(proxyConfig)) {
            // Parse failures must throw here: skipping a record inside a delete-tracked
            // crawl would cause trackDeletesEnd() to falsely mark it as deleted.
            const campaigns = page.map((raw) => toEmailCampaign(ProviderEmailCampaignSchema.parse(raw)));
            if (campaigns.length > 0) {
                await nango.batchSave(campaigns, 'EmailCampaign');
            }
        }

        await nango.trackDeletesEnd('EmailCampaign');
    }
});

export type NangoSyncLocal = Parameters<(typeof sync)['exec']>[0];
export default sync;
