// ---------------------------
// This file was generated by Nango (v0.66.0)
// You can version this file
// ---------------------------

export interface SyncMetadata_hackerrank_work_interviews {
};

export interface HackerRankWorkInterview {
  id: string;
  status: string;
  created_at: Date;
  updated_at: Date;
  title: string;
  feedback: string;
  notes: string;
  metadata: {};
  quickpad: boolean;
  ended_at: Date;
  timezone: string;
  interview_template_id: string;
  from: Date;
  to: Date;
  url: string;
  user: string;
  thumbs_up: boolean;
  resume_url: string;
  interviewers: string[];
  candidate: {  name: string;
  email: string;};
  result_url: string;
  report_url: string;
};

export interface SyncMetadata_hackerrank_work_teams {
};

export interface HackerRankWorkTeam {
  id: string;
  name: string;
  owner: string;
  created_at: Date;
  recruiter_count: number;
  developer_count: number;
  interviewer_count: number;
  recruiter_cap: number;
  developer_cap: number;
  interviewer_cap: number;
  logo_id: string;
  library_access: boolean;
  invite_as: string;
  locations: string[];
  departments: string[];
};

export interface SyncMetadata_hackerrank_work_tests {
};

export interface HackerRankWorkTest {
  id: string;
  unique_id: string;
  name: string;
  duration: number;
  owner: string;
  instructions: string;
  created_at: Date;
  state: string;
  locked: boolean;
  test_type: string;
  starred: boolean;
  start_time: Date;
  end_time: Date;
  draft: boolean;
  questions: string[];
  sections: {};
  tags: string[];
  permission: number;
};

export interface SyncMetadata_hackerrank_work_users {
};

export interface HackerRankWorkUser {
  id: string;
  email: string;
  firstname: string;
  lastname: string;
  country: string;
  role: string;
  status: string;
  phone: string;
  timezone: string;
  questions_permission: number;
  tests_permission: number;
  interviews_permission: number;
  candidates_permission: number;
  shared_questions_permission: number;
  shared_tests_permission: number;
  shared_interviews_permission: number;
  shared_candidates_permission: number;
  created_at: Date;
  company_admin: boolean;
  team_admin: boolean;
  company_id: string;
  teams: any[];
  activated: boolean;
  last_activity_time: Date;
};

export interface ActionInput_hackerrank_work_createtest {
  name: string;
  starttime: Date;
  endtime: Date;
  duration: number;
  instructions: string;
  locked: boolean;
  draft: string;
  languages: string[];
  candidate_details: string[];
  custom_acknowledge_text: string;
  cutoff_score: number;
  master_password: string;
  hide_compile_test: boolean;
  tags: string[];
  role_ids: string[];
  experience: string[];
  questions: string[];
  mcq_incorrect_score: number;
  mcq_correct_score: number;
  secure: boolean;
  shuffle_questions: boolean;
  test_admins: string[];
  hide_template: boolean;
  enable_acknowledgement: boolean;
  enable_proctoring: boolean;
  candidate_tab_switch: boolean;
  track_editor_paste: boolean;
  show_copy_paste_prompt: boolean;
  ide_config: string;
};

export interface ActionOutput_hackerrank_work_createtest {
  id: string;
  unique_id: string;
  name: string;
  duration: number;
  owner: string;
  instructions: string;
  created_at: Date;
  state: string;
  locked: boolean;
  test_type: string;
  starred: boolean;
  start_time: Date;
  end_time: Date;
  draft: boolean;
  questions: string[];
  sections: {};
  tags: string[];
  permission: number;
};

export interface ActionInput_hackerrank_work_createinterview {
  id: string;
  status: string;
  created_at: Date;
  updated_at: Date;
  title: string;
  feedback: string;
  notes: string;
  metadata: {};
  quickpad: boolean;
  ended_at: Date;
  timezone: string;
  interview_template_id: string;
  from: Date;
  to: Date;
  url: string;
  user: string;
  thumbs_up: boolean;
  resume_url: string;
  interviewers: string[];
  candidate: {  name: string;
  email: string;};
  result_url: string;
  report_url: string;
  send_email: boolean;
  interview_metadata: {};
};

export interface ActionOutput_hackerrank_work_createinterview {
  id: string;
  status: string;
  created_at: Date;
  updated_at: Date;
  title: string;
  feedback: string;
  notes: string;
  metadata: {};
  quickpad: boolean;
  ended_at: Date;
  timezone: string;
  interview_template_id: string;
  from: Date;
  to: Date;
  url: string;
  user: string;
  thumbs_up: boolean;
  resume_url: string;
  interviewers: string[];
  candidate: {  name: string;
  email: string;};
  result_url: string;
  report_url: string;
};
