// ---------------------------
// This file was generated by Nango (v0.68.1)
// You can version this file
// ---------------------------

export interface SyncMetadata_discourse_activeusers {
};

export interface User {
  id: string;
  username: string;
  name: string;
  admin: boolean;
};

export interface SyncMetadata_discourse_categories {
};

export interface Category {
  id: string;
  name: string;
  color: string;
  description: string | null;
  slug: string;
};

export interface ActionInput_discourse_createcategory {
  name: string;
  color?: string | undefined;
  text_color?: string | undefined;
  parent_category_id?: string | undefined;
  slug?: string | undefined;
  search_priority?: string | undefined;
};

export interface ActionOutput_discourse_createcategory {
  id: string;
  name: string;
  color: string;
  description: string | null;
  slug: string;
};

export interface ActionInput_discourse_createtopic {
  title: string;
  category: number;
  raw: string;
};

export interface ActionOutput_discourse_createtopic {
  id: string;
  name: string;
  content: string;
};

export interface ActionInput_discourse_updatetopicstatus {
  id: string;
  status: 'closed' | 'pinned' | 'pinned_globally' | 'archived' | 'visible';
  enabled?: any | undefined | any | undefined;
  until: string;
};

export interface ActionOutput_discourse_updatetopicstatus {
  success: string;
  result: string;
};
