// ---------------------------
// This file was generated by Nango (v0.62.0)
// You can version this file
// ---------------------------

export interface User {
    id: number;
    username: string;
    name: string;
    admin: boolean;
}

export interface CreateCategory {
    name: string;
    color?: string;
    text_color?: string;
    parent_category_id?: string;
    slug?: string;
    search_priority?: string;
}

export interface Category {
    id: string;
    name: string;
    color: string;
    description: string | null;
    slug: string;
}

export interface CreateTopic {
    title: string;
    category: number;
    raw: string;
}

export interface Topic {
    id: string;
    name: string;
    content: string;
}

export interface TopicStatus {
    id: string;
    status: 'closed' | 'pinned' | 'pinned_globally' | 'archived' | 'visible';
    enabled: true | false;
    until: string;
}

export interface TopicStatusUpdated {
    success: string;
    result: string;
}
