// ---------------------------
// This file was generated by Nango (v0.58.7)
// You can version this file
// ---------------------------

export interface AttioWorkspaceMember {
    id: string;
    workspace_id: string;
    first_name: string;
    last_name: string;
    avatar_url?: string;
    email_address: string;
    created_at: string;
    access_level: string;
}

export interface AttioObject {
    id: string;
    workspace_id: string;
    api_slug: string;
    singular_noun: string;
    plural_noun: string;
    created_at: string;
}

export interface AttioUser {
    id: string;
    workspace_id: string;
    created_at: string;
    web_url: string;
    values: {
        person?: string;
        primary_email_address?: string;
        user_id?: string;
        workspace?: string;
        first_name?: string;
        last_name?: string;
        title?: string;
        phone?: string;
        mobile_phone?: string;
        department?: string;
        company?: string;
    };
}
