// ---------------------------
// This file was generated by Nango (v0.66.0)
// You can version this file
// ---------------------------

export interface SyncMetadata_lattice_users {
};

export interface User {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
};
