// Generated by ts-to-zod
import { z } from 'zod';

export const instantlySetCampaignNameResponseSchema = z.object({
    status: z.string()
});

export const instantlySetCampaignNameInputSchema = z.object({
    campaign_id: z.string(),
    name: z.string()
});
