name: Deploy integration templates to S3

on:
    workflow_dispatch:
    push:
        branches:
            - main

concurrency:
    group: deploy-templates-to-s3-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    template-upload:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  cache: 'npm'
                  node-version-file: '.nvmrc'

            - name: Install nango CLI and dependencies
              run: |
                  npm ci
                  NANGO_CLI_UPGRADE_MODE=ignore npx nango version --debug

            - name: Check if templates changed
              if: github.event_name != 'workflow_dispatch'
              id: templates-updated
              uses: tj-actions/changed-files@v41
              with:
                  files: |
                      integrations/*
                      integrations/**/*

            - name: Resolve aliases
              run: |
                  npm run resolve:aliases

            - name: Upload to S3 (Zero)
              if: steps.templates-updated.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch'
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
              run: |
                  if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
                    echo "Manual trigger detected. Uploading all templates."
                    dirs=$(find integrations -maxdepth 1 -type d | tail -n +2 | sort)
                  else
                    echo "Automatic trigger detected. Uploading changed templates."
                    all_dirs=$(echo "${{ steps.templates-updated.outputs.all_changed_files }}" | cut -d'/' -f1,2 | sort -u)

                    dirs=$(for dir in $all_dirs; do
                      integration=$(basename "$dir")
                      echo "$dir"
                      find integrations -maxdepth 1 -type d -name "$integration-*"
                    done | sort -u)
                  fi

                  for dir in $dirs; do
                    integration=$(basename "$dir")

                    if [ "$integration" = ".nango" ]; then
                      continue
                    fi

                    if [ ! -f "$dir/index.ts" ]; then
                      continue
                    fi

                    rm -rf integrations/build
                    npm run cli -- $integration compile
                    aws s3 sync $dir s3://${{ secrets.AWS_BUCKET_NAME }}/templates-zero/$integration
                    aws s3 sync integrations/build s3://${{ secrets.AWS_BUCKET_NAME }}/templates-zero/$integration/build --delete
                  done
