name: Nango Integration Flows Compile

on:
    push:
        branches:
            - main
            - staging/**
    pull_request:

concurrency:
    group: flows-compile--${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    flow-compilation:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  cache: 'npm'
                  node-version-file: '.nvmrc'

            - name: Install nango CLI
              run: |
                  # Build, install CLI and verify it can run
                  npm ci
                  NANGO_CLI_UPGRADE_MODE=ignore npx nango version --debug

            - name: Compile with Nango
              run: |
                  set -e
                  cd integrations
                  for dir in */; do
                    if [[ "$dir" != "." && "$dir" != "integrations/" ]]; then
                        cd "$dir"
                        mkdir -p nango-integrations/$dir
                        mv nango.yaml nango-integrations/
                        find . -maxdepth 1 ! -name '.' ! -name 'nango-integrations' -exec mv -t nango-integrations/$dir {} +
                        cd nango-integrations
                        NANGO_CLI_UPGRADE_MODE=ignore npx nango compile
                        cd ../../
                    fi
                  done
