name: Lint

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    lint-code:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: '0'

            - uses: actions/setup-node@v4
              with:
                  cache: 'npm'
                  node-version-file: '.nvmrc'

            - name: Install dependencies
              run: npm ci

            - name: Lint
              run: npm run lint-moved-integrations
