name: Run Unit & Integration Tests

on:
    push:
        branches:
            - main
            - staging/**
    pull_request:

concurrency:
    group: tests-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    tests:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [20.x, 22.x]

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: '0'

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  cache: 'npm'
                  node-version: ${{ matrix.node-version }}

            - run: npm ci
            - run: npm run test

            - name: Make sure flows.zero.json is compiled
              run: |
                  npm run build:flows

                  REPO_DIRTY=$(git status --short)
                  if [[ ! -z "$REPO_DIRTY" ]]; then
                    git diff
                    echo ""
                    echo -e "\r❌ flows.zero.json hasn't been compiled, please run:"
                    echo -e "npm run build:flows"
                    exit 1
                  fi
