name: Yaml Validation

on:
    push:
        branches:
            - master
            - staging/**
    pull_request:

concurrency:
    group: validation-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    yaml_validation_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: '0'

            - uses: actions/setup-node@v4
              with:
                  cache: 'npm'
                  node-version-file: '.nvmrc'
                  registry-url: 'https://registry.npmjs.org'

            - name: Validate YAML
              run: |
                  cd scripts/validation/providers
                  npm i
                  node validate.js
